syntax = "proto2";

import "AppSignal.proto";
import "Network.proto";

package Grpc;

message HandshakeRequest
{
	required Network.SoftwareInfo clientSoftwareInfo = 1;
}

message HandshakeReply
{
	required Network.SoftwareInfo serverSoftwareInfo = 1;
	required string authToken = 2;
}

//
// GetAppSignalList
//
message GetAppSignalListRequest
{
}

message GetAppSignalListReply
{
	optional uint32 totalSize = 2;				// How many signal IDs totally will be transfered.
	repeated string appSignalIds = 3;
}

//
// GetAppSignalParam
//
message GetAppSignalParamRequest
{
	repeated fixed64 signalHashes = 1;			// If empty then get all signals.
}

message GetAppSignalParamReply
{
	optional uint32 totalSize = 1;				// How many signal params totally will be transfered.
	optional uint32 replySignalIndex = 2;		// Start index for this reply
	repeated Proto.AppSignal signalParams = 3;
}

//
// Geetting application signal states
//
message GetAppSignalStateRequest
{
	repeated uint64 signalHashes = 1;						// Limited to ADS_GET_APP_SIGNAL_STATE_MAX (2000)
}

message GetAppSignalStateReply
{
	repeated Proto.AppSignalState appSignalStates = 1;		// Limited to ADS_GET_APP_SIGNAL_STATE_MAX (2000)
}

service AppDataSrv
{
	rpc Handshake(HandshakeRequest) returns (HandshakeReply) {}
	rpc GetAppSignalList(GetAppSignalListRequest) returns (stream GetAppSignalListReply) {}
	rpc GetAppSignalParam(GetAppSignalParamRequest) returns (stream GetAppSignalParamReply) {}
	rpc GetAppSignalState(GetAppSignalStateRequest) returns (GetAppSignalStateReply) {}
}
