syntax = "proto2";

import "GrpcAppDataSrv.proto";
import "Network.proto";

package Grpc;

//
//	GetFile
//
message GetFileRequest
{
    required string fileName = 1;
}

message GetFileReply
{
    required string fileName = 1;
	required int32 errorCode = 2 [default = 0];				// values of Tcp::FileTransferResult
	optional int64 fileSize = 3  [default = 0];
	optional int32 currentPart = 4 [default = 0];
	optional int32 totalParts = 5 [default = 0];
	optional bytes fileData = 6;
	optional bytes md5 = 7;
}

//
// GetSessionParams
//

message GetSessionParamsRequest
{
}

message GetSessionParamsReply
{
	required Network.SessionParams sessionParams = 1;
}

service FileSrv
{
	rpc Handshake(HandshakeRequest) returns (HandshakeReply) {}
	rpc GetFile(GetFileRequest) returns (stream GetFileReply) {}
	rpc GetSessionParams(GetSessionParamsRequest) returns (GetSessionParamsReply) {}
}
