#pragma once

#include "DeviceObject.h"

namespace Hardware
{
	//
	//
	// DeviceAppSignal
	//
	//
	class DeviceAppSignal : public DeviceObject
	{
		Q_OBJECT

	public:
		explicit DeviceAppSignal(bool preset = false, QObject* parent = nullptr) noexcept;
		virtual ~DeviceAppSignal() = default;

	protected:
		virtual void propertyDemand(const QString& prop) override;

		// Serialization
		//
	protected:
		virtual bool SaveData(Proto::Envelope* message, bool saveTree) const override;
		virtual bool LoadData(const Proto::Envelope& message) override;

		// Expand EquipmentIDTemplate, ValiditySignalId for this and for all children
		//
	public:
		virtual void expandEquipmentId() override;

		// Properties
		//
	public:
		[[nodiscard]] E::SignalType signalType() const;
		void setSignalType(E::SignalType value);

		[[nodiscard]] E::SignalFunction function() const;
		void setFunction(E::SignalFunction value);

		[[nodiscard]] E::ByteOrder byteOrder() const;
		void setByteOrder(E::ByteOrder value);

		[[nodiscard]] E::DataFormat format() const;
		void setFormat(E::DataFormat value);

		[[nodiscard]] E::MemoryArea memoryArea() const;
		void setMemoryArea(E::MemoryArea value);

		[[nodiscard]] int size() const;
		void setSize(int value);

		[[nodiscard]] int valueOffset() const;
		void setValueOffset(int value);

		[[nodiscard]] int valueBit() const;
		void setValueBit(int value);

		[[nodiscard]] QString validitySignalId() const;
		void setValiditySignalId(QString value);

		[[nodiscard]] bool isInputSignal() const;
		[[nodiscard]] bool isOutputSignal() const;
		[[nodiscard]] bool isDiagSignal() const;
		[[nodiscard]] bool isValiditySignal() const;

		[[nodiscard]] bool isAnalogSignal() const;
		[[nodiscard]] bool isDiscreteSignal() const;

		[[nodiscard]] int appSignalLowAdc() const;
		void setAppSignalLowAdc(int value);

		[[nodiscard]] int appSignalHighAdc() const;
		void setAppSignalHighAdc(int value);

		[[nodiscard]] double appSignalLowEngUnits() const;
		void setAppSignalLowEngUnits(double value);

		[[nodiscard]] double appSignalHighEngUnits() const;
		void setAppSignalHighEngUnits(double value);

		[[nodiscard]] E::AnalogAppSignalFormat appSignalDataFormat() const;
		void setAppSignalDataFormat(E::AnalogAppSignalFormat value);

		[[nodiscard]] QString appSignalBusTypeId() const;
		void setAppSignalBusTypeId(QString value);

		[[nodiscard]] QString signalSpecPropsStruct() const;
		void setSignalSpecPropsStruct(QString value);

		// Data
		//
	private:
		E::SignalType m_signalType = E::SignalType::Discrete;
		E::SignalFunction m_function = E::SignalFunction::Input;

		E::ByteOrder m_byteOrder = E::ByteOrder::LittleEndian;
		E::DataFormat m_format = E::DataFormat::UnsignedInt;

		E::MemoryArea m_memoryArea = E::MemoryArea::ApplicationData;

		int m_size = 0;
		int m_valueOffset = 0;
		int m_valueBit = 0;

		QString m_validitySignalId;

		// Properties for creating Analog AppSignal
		//
		int m_appSignalLowAdc = 0;
		int m_appSignalHighAdc = 65535;
		double m_appSignalLowEngUnits = 0.0;
		double m_appSignalHighEngUnits = 100.0;
		E::AnalogAppSignalFormat m_appSignalDataFormat = E::AnalogAppSignalFormat::Float32;

		// Properties for creating Bus AppSignal
		//
		QString m_appSignalBusTypeId;

		QString m_signalSpecPropsStruct;		// Description of the specific properties to be generated by AppSignal
	};
} // namespace Hardware