@startuml AppSignalLib
set namespaceSeparator ::

interface AppSignalLib::IAppSignalManager
{
}

'
' class AppSignalManager
'
class AppSignalLib::AppSignalManager implements AppSignalLib::IAppSignalManager
{
    -m_signalParams
    -m_signalParamByEquipmentId
    -m_tagToAppSignals
    -m_tags
    -m_signalStates
    -m_setpoints
}

@enduml