variables:
  GIT_DEPTH: "1"
  QT_VERSION: "6.3.2"
  COMPILER_TESTS_PROJECT_NAME: "compiler_tests_v381"
  SIMULATOR_PROJECT_NAME: "test_simulator_v381"
  
stages:
  - build
  - test
#  - deploy

before_script:
#  - echo before_script
  - cd
  - dir
  
#after_script:
#  - echo after_script


linux_build_job:
  stage: build
  only:
    - master
    - /^release.*$/
    - develop
    - /experimental/
    - /^.*exp.*$/
    - /^.*rpct-.*$/
    - /^.*RPCT-.*$/
  tags:
    - gcc
  script:
    - "printenv"
    - "pwd"
    - "whoami"
    - "gcc --version"
    - "echo $CI_COMMIT_SHA"
    - "cd $CI_PROJECT_DIR"
    - "git status"
    - "git log -1"
#generation version file
    - "echo '#pragma once' > gitlabci_version.h"
    - "echo >> gitlabci_version.h"
    - "echo '#define GITLAB_CI_BUILD' >> gitlabci_version.h"
    - echo '#define CI_BUILD_REF_SLUG' \"$CI_BUILD_REF_SLUG\" >> gitlabci_version.h
    - echo '#define CI_COMMIT_SHA' \"$CI_COMMIT_SHA\" >> gitlabci_version.h
    - echo '#define GITLAB_USER_NAME' \"$GITLAB_USER_NAME\" >> gitlabci_version.h
    - echo '#define CI_PIPELINE_ID' $CI_PIPELINE_ID >> gitlabci_version.h
    - echo '#define COMPUTERNAME' \"$HOSTNAME\" >> gitlabci_version.h
    - echo '#define BUILD_DATE' \"$(date)\" >> gitlabci_version.h

#Build Project
    - "# ----------------------------------------------"
    - "#               Build Project"
    - "# ----------------------------------------------"    
    - "/opt/Qt/${QT_VERSION}/gcc_64/bin/qmake u7set.pro -spec linux-g++"
    - "make -j12"

  artifacts:
    name: "u7set_linux_0.9.$CI_PIPELINE_ID $CI_BUILD_REF_SLUG $CI_COMMIT_SHA"
    paths:
      - bin_unix/*
    exclude:
      - bin_unix/**/*.a
#

windows_build_job:
  stage: build
  only:
    - master
    - /^release.*$/
    - develop
    - /experimental/
    - /^.*exp.*$/
    - /^.*rpct-.*$/
    - /^.*RPCT-.*$/
  tags:
    - vs2017
  script:
    - "# dir env:"
    - "echo $Env:CI_COMMIT_SHA"
    - "git status"
    - "git log -1"
    - $Env:QT_BIN_DIR="C:\\Qt\\${QT_VERSION}\\msvc2019_64"
#generation version file
    - "'#pragma once' > gitlabci_version.h"
    - "' ' >> gitlabci_version.h"
    - "'#define GITLAB_CI_BUILD' >> gitlabci_version.h"
    - "'#define CI_BUILD_REF_SLUG \"' + $env:CI_BUILD_REF_SLUG + '\"' >> gitlabci_version.h"
    - "'#define CI_COMMIT_SHA \"' + $env:CI_COMMIT_SHA + '\"' >> gitlabci_version.h"
    - "'#define GITLAB_USER_NAME \"' + $env:GITLAB_USER_NAME + '\"' >> gitlabci_version.h"
    - "'#define CI_PIPELINE_ID ' + $env:CI_PIPELINE_ID + '' >> gitlabci_version.h"
    - "'#define COMPUTERNAME \"' + $env:HOSTNAME + '\"' >> gitlabci_version.h"
    - "$Env:timestamp = Get-Date -Format 'dd MMMM yyyy HH:mm (K)'"
    - "'#define BUILD_DATE \"' + $Env:timestamp + '\"' >> gitlabci_version.h"
#Build Project
    - "# ----------------------------------------------"
    - "#               Build Project"
    - "# ----------------------------------------------"    
    - "& './gitlab_ci_build.bat'"
#Copy Qt DLLs to bin/release
    - "# ----------------------------------------------"
    - "#               Copy Qt DLL's"
    - "# ----------------------------------------------"
    - "& './CI/windeploy.bat'"
#Copy PostgreSQL DLL to bin/release
    - "copy C:\\libpq_my_build\\libpq.dll \"$Env:CI_PROJECT_DIR/bin/release/\""
# Copy Metrology plugins
    - "copy $Env:CI_PROJECT_DIR\\bin_Win64\\visa64.dll \"$Env:CI_PROJECT_DIR/bin/release/\""
    - "copy $Env:CI_PROJECT_DIR\\bin_Win64\\visaConfMgr.dll \"$Env:CI_PROJECT_DIR/bin/release/\""
    - "copy $Env:CI_PROJECT_DIR\\bin_Win64\\visaUtilities.dll \"$Env:CI_PROJECT_DIR/bin/release/\""
# Copy documents
    - "mkdir \"$Env:CI_PROJECT_DIR/bin/release/docs\""
    - "copy $Env:CI_PROJECT_DIR\\Metrology\\docs\\Metrology_User_Manual.pdf \"$Env:CI_PROJECT_DIR/bin/release/docs/\""
# Copy GlobalScript library
    - "mkdir \"$Env:CI_PROJECT_DIR/bin/release/scripting\""
    - "copy $Env:CI_PROJECT_DIR\\Scripts\\GlobalScript\\*.* \"$Env:CI_PROJECT_DIR/bin/release/scripting/\""

#Remove some files not requiered for releases
    - "# ----------------------------------------------"
    - "#               Remove some files not requiered for releases"
    - "# ----------------------------------------------"
    - "del -Force $Env:CI_PROJECT_DIR/bin/release/DiagDataSrv.exe"
    
#Signing Files
    - "# ----------------------------------------------"
    - "#               Sign Files"
    - "# ----------------------------------------------"
#    - "$SIGNTOOL='C:/Program Files (x86)/Windows Kits/10/App Certification Kit/signtool.exe'"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD bin\\release\\AppDataSrv.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD bin\\release\\ArchSrv.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD bin\\release\\CfgSrv.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD bin\\release\\mconf.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD bin\\release\\PacketSource.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD bin\\release\\PacketViewer.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD bin\\release\\Metrology.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD bin\\release\\Monitor.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD bin\\release\\scm.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD bin\\release\\TuningClient.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD bin\\release\\TuningSrv.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD bin\\release\\u7.exe"    

#Generate ScriptHelp
    - "# ----------------------------------------------"
    - "#               Generate ScriptHelp"
    - "# ----------------------------------------------"
    - "pushd ."	
    - "cd $Env:CI_PROJECT_DIR\\u7\\ScriptHelp"
    - "&./ScriptHelp.bat"
    - "popd"

#Request documents from SVN
    - "# ----------------------------------------------"
    - "#               Request documents from SVN"
    - "# ----------------------------------------------"
    - "pushd ."	
    - "cd $Env:CI_PROJECT_DIR/doc"
    - "&./SvnGetDocs.bat"
    - "popd"

#Build Installer
    - "# ----------------------------------------------"
    - "#               Build Installer"
    - "# ----------------------------------------------"
    - "pushd ."	
    - "cd $Env:CI_PROJECT_DIR/u7setinstall"
    - "&./createinstall.bat"
    - "popd"	
#    - "&$SIGNTOOL sign /v /a  /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD bin\\*.exe"

  artifacts:
    name: "u7set_0.9.$CI_PIPELINE_ID $CI_BUILD_REF_SLUG $CI_COMMIT_SHA"
    paths:
      - bin/*.exe
      - bin/release/*.exe
      - bin/release/*.dll
      - bin/release/iconengines/*.dll
      - bin/release/imageformats/*.dll
      - bin/release/networkinformation/*.dll
      - bin/release/platforms/*.dll
      - bin/release/sqldrivers/*.dll
      - bin/release/styles/*.dll
      - bin/release/tls/*.dll
      - bin/release/translations/*.qm
      - bin/release/scripting/*.*
      - bin/release/scripthelp/*.*
      - bin/release/scripthelp/search/*.*
      - bin/release/docs/*.pdf
      - bin/release/docs/Appendixes/*.pdf


windows_test_job:
  stage: test
  needs: ["windows_build_job"]
  tags:
    - test
  only:
    - master
    - /^release.*$/
    - develop
    - /experimental/
    - /^.*exp.*$/
    - /^.*rpct-.*$/
    - /^.*RPCT-.*$/
  script:
    - "# dir env:"
    - "echo $Env:CI_COMMIT_SHA"
    - "git status"
    - "git log -1"
#Run Create databases for compiler and simulator tests
    - echo Creating PostgreSQL databases...
    - psql -U postgres -c "CREATE DATABASE u7_%COMPILER_TESTS_PROJECT_NAME% OWNER u7;"
    - cmd '/c psql -U postgres u7_%COMPILER_TESTS_PROJECT_NAME% < c:\Data\u7_%COMPILER_TESTS_PROJECT_NAME%.sql'
    - psql -U postgres -c "CREATE DATABASE u7_%SIMULATOR_PROJECT_NAME% OWNER u7;"
    - cmd '/c psql -U postgres u7_%SIMULATOR_PROJECT_NAME% < c:\Data\u7_%SIMULATOR_PROJECT_NAME%.sql'
#Run XML validation
    - "# ----------------------------------------------"
    - "#               Run XML validation"
    - "# ----------------------------------------------"
    - "pushd ."	
    - "cd $Env:CI_PROJECT_DIR/Presets/LogicModuleDescription"
    - "&./validate_xmls.bat"
    - "popd"

#Run unit tests
    - "# ----------------------------------------------"
    - "#               Run unit tests"
    - "# ----------------------------------------------"
    - "&$Env:CI_PROJECT_DIR/bin/release/u7databasetests.exe -config=\"$Env:CI_PROJECT_DIR/Test/u7databasetestsArgs.xml\" -o u7databasetests.xml,junitxml -o -,txt"
    - "&$Env:CI_PROJECT_DIR/bin/release/ClientTests.exe --gtest_filter=-ConfigControllerTests.*  --gtest_output=xml:ClientTestsLinux.xml"
    - "&$Env:CI_PROJECT_DIR/bin/release/SimulatorTests.exe -o SimulatorTests.xml,junitxml -o -,txt"
    - "&$Env:CI_PROJECT_DIR/bin/release/MetrologyTests.exe -o MetrologyTests.xml,junitxml -o -,txt"

#Run Builder test
    - "# ----------------------------------------------"
    - "#               Run BuilderConsole tests"
    - "# ----------------------------------------------"
    - "if (Test-Path c:/temp/build/test_simulator) { Remove-Item c:/temp/build/test_simulator -Recurse -Force; }"
    - "&$Env:CI_PROJECT_DIR/bin/release/BuilderConsole.exe $Env:CI_PROJECT_DIR/Test/BuilderConsoleArgs.xml"
    
#Run Compiler tests
    - "# ----------------------------------------------"
    - "#               Run Compiler tests"
    - "# ----------------------------------------------"
    - "&$Env:CI_PROJECT_DIR/bin/release/BuilderConsole.exe $Env:CI_PROJECT_DIR/Test/CompilerTestsArgs.xml"

#Run Sim AFB Tests
    - "# ----------------------------------------------"
    - "#               Run Simulator AFBs tests"
    - "# ----------------------------------------------"
    - "&$Env:CI_PROJECT_DIR/bin/release/SimulatorConsole.exe -build=c:/temp/build/%SIMULATOR_PROJECT_NAME%/build -script=\"$Env:CI_PROJECT_DIR/Simulator/SimProjectTests.js\""

#Run ROVT to check configuration generation
    - "# ----------------------------------------------"
    - "#               Run ROVT tests"
    - "# ----------------------------------------------"
    - "#&C:/ROVT/ROVT_C.exe /b:C:\\Temp\\build\\%SIMULATOR_PROJECT_NAME%\\build"
  artifacts:
    name: "u7set_test_windows_0.9.$CI_PIPELINE_ID $CI_BUILD_REF_SLUG $CI_COMMIT_SHA"
    paths:
      - u7databasetests.xml
      - ClientTests.xml
      - SimulatorTests.xml
      - MetrologyTests.xml
    reports:
      junit: 
        - u7databasetests.xml
        - ClientTests.xml
        - SimulatorTests.xml
        - MetrologyTests.xml


linux_test_job:
  stage: test
  needs: ["linux_build_job"]
  tags:
    - gcctest
  only:
    - master
    - /^release.*$/
    - develop
    - /experimental/
    - /^.*exp.*$/
    - /^.*rpct-.*$/
    - /^.*RPCT-.*$/
  script:
    - "printenv"
    - "echo $CI_COMMIT_SHA"
    - "cd $CI_PROJECT_DIR"
    - "git status"
    - "git log -1"
#Run XML validation
#    - "# ----------------------------------------------"
#    - "#               Run XML validation"
#    - "# ----------------------------------------------"
    - "pushd $CI_PROJECT_DIR/Presets/LogicModuleDescription"
    - "chmod a+x validate_xmls.sh"
    - "./validate_xmls.sh"
    - "popd"

#Create databases for compiler and simulator tests
    - "echo Creating PostgreSQL databases..."
    - "cp $CI_PROJECT_DIR/Test/ImportDatabase.sh /tmp"
    - "pushd /mnt/f/TestDatabase"
    - "echo P2ssw0rd | su postgres /tmp/ImportDatabase.sh u7_${COMPILER_TESTS_PROJECT_NAME}"
    - "echo P2ssw0rd | su postgres /tmp/ImportDatabase.sh u7_${SIMULATOR_PROJECT_NAME}"
    - "popd"
    - "rm /tmp/ImportDatabase.sh"
    - "echo Creating PostgreSQL databases complete

#Run Builder test
    - "# ----------------------------------------------"
    - "#               Run BuilderConsole tests"
    - "# ----------------------------------------------"
    - "if [ -d \"/tmp/build/test_simulator\" ]; then rm -Rf /tmp/build/test_simulator; fi"
    - "$CI_PROJECT_DIR/bin_unix/release/BuilderConsole $CI_PROJECT_DIR/Test/BuilderConsoleArgsLinux.xml"
    
#Run Compiler tests
    - "# ----------------------------------------------"
    - "#               Run Compiler tests"
    - "# ----------------------------------------------"
    - "$CI_PROJECT_DIR/bin_unix/release/BuilderConsole $CI_PROJECT_DIR/Test/CompilerTestsArgsLinux.xml"

#Run Sim AFB Tests
    - "# ----------------------------------------------"
    - "#               Run Simulator AFBs tests"
    - "# ----------------------------------------------"
    - "$CI_PROJECT_DIR/bin_unix/release/SimulatorConsole -build=/tmp/build/${SIMULATOR_PROJECT_NAME}/build -script=\"$CI_PROJECT_DIR/Simulator/SimProjectTests.js\""

#Run unit tests
    - "# ----------------------------------------------"
    - "#               Run client tests"
    - "# ----------------------------------------------"
    - "$CI_PROJECT_DIR/bin_unix/release/CfgSrv -e -id=SYSTEMID_CLIENTTEST_WS01_CFGS -profile=Default -b=/tmp/build/${SIMULATOR_PROJECT_NAME}/build -ip=127.0.0.1:13312 < /dev/null > cfgsrv.out 2>&1 &"
    - "sleep 3"
    - "jobs"
    - "$CI_PROJECT_DIR/bin_unix/release/ClientTests --gtest_output=xml:ClientTestsLinux.xml"
    - "pkill CfgSrv"
    - "sleep 1"
    - "jobs"

#Run unit tests
    - "# ----------------------------------------------"
    - "#               Run unit tests"
    - "# ----------------------------------------------"
    - "$CI_PROJECT_DIR/bin_unix/release/SimulatorTests -o SimulatorTestsLinux.xml,junitxml -o -,txt"
    - "$CI_PROJECT_DIR/bin_unix/release/MetrologyTests -o MetrologyTests.xml,junitxml -o -,txt"
    - "$CI_PROJECT_DIR/bin_unix/release/u7databasetests -config=$CI_PROJECT_DIR/Test/u7databasetestsArgsLinux.xml -o u7databasetestslinux.xml,junitxml -o -,txt"

#Run ROVT to check configuration generation
#    - "# ----------------------------------------------"
#    - "#               Run ROVT tests"
#    - "# ----------------------------------------------"
#    - "#&C:/ROVT/ROVT_C.exe /b:C:\\Temp\\build\\${SIMULATOR_PROJECT_NAME}\\build"

  artifacts:
    name: "u7set_test_linux_0.9.$CI_PIPELINE_ID $CI_BUILD_REF_SLUG $CI_COMMIT_SHA"
    paths:
      - u7databasetestslinux.xml
      - ClientTestsLinux.xml
      - SimulatorTestsLinux.xml
      - MetrologyTests.xml
    reports:
      junit: 
        - u7databasetestslinux.xml
        - ClientTestsLinux.xml
        - SimulatorTestsLinux.xml
        - MetrologyTests.xml


linux_code_coverage_job:
  stage: test
  needs: []
  tags:
    - testlinux
  only:
    - master
    - /^release.*$/
    - develop
    - /experimental/
    - /^.*exp.*$/
    - /^.*rpct-.*$/
    - /^.*RPCT-.*$/
  script:
    - "printenv"
    - "echo $CI_COMMIT_SHA"
    - "cd $CI_PROJECT_DIR"
    - "git status"
    - "git log -1"
    - "# ----------------------------------------------"
    - "#               Import DB Projects              "
    - "# ----------------------------------------------"
    - "echo Creating PostgreSQL databases..."
    - "cp $CI_PROJECT_DIR/Test/ImportDatabase.sh /tmp"
    - "pushd /mnt/f/TestDatabase"
    - "echo P2ssw0rd | su postgres /tmp/ImportDatabase.sh u7_${SIMULATOR_PROJECT_NAME}"
    - "popd"
    - "rm /tmp/ImportDatabase.sh"
    - "echo Creating PostgreSQL databases complete      
    - "# ----------------------------------------------"
    - "#               Build Test Project              "
    - "# ----------------------------------------------"
    - "/opt/Qt/${QT_VERSION}/gcc_64/bin/qmake u7set_tests.pro -spec linux-g++ CONFIG+=debug CONFIG-=qml_debug CONFIG-=qtquickcompiler CONFIG+=separate_debug_info CONFIG+=CODE_COVERAGE "
    - "make -j12"
    - "# ----------------------------------------------"
    - "#               Run BuilderConsole tests"
    - "# ----------------------------------------------"
    - "if [ -d \"/tmp/build/test_simulator\" ]; then rm -Rf /tmp/build/test_simulator; fi"
    - "$CI_PROJECT_DIR/bin_unix/release/BuilderConsole $CI_PROJECT_DIR/Test/BuilderConsoleArgsCoverage.xml"
    - "# ----------------------------------------------"
    - "#       Run services for functional tests       "
    - "# ----------------------------------------------"
    - "$CI_PROJECT_DIR/bin_unix/release/CfgSrv -e -id=SYSTEMID_CLIENTTEST_WS01_CFGS -profile=Default -b=/tmp/build/${SIMULATOR_PROJECT_NAME}/build -ip=127.0.0.1:13312 < /dev/null > cfgsrv.out 2>&1 &"
    - "sleep 3"
    - "jobs"
    - "# ----------------------------------------------"
    - "#           Collect Test Coverage Data          "
    - "# ----------------------------------------------"
    - "./Test/CodeCoverage.sh"
    - "# ----------------------------------------------"
    - "#       Stop services for functional tests      "
    - "# ----------------------------------------------"
    - "pkill CfgSrv"
    - "sleep 1"
    - "jobs"

  coverage: '/lines......: \d+\.\d+/'
  artifacts:
    name: "coverage_report.$CI_PIPELINE_ID $CI_BUILD_REF_SLUG $CI_COMMIT_SHA"
    paths:
      - CodeCoverage/coverage.xml
      - CodeCoverage/Report/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: CodeCoverage/coverage.xml

