variables:
  GIT_DEPTH: "1"
  
stages:
  - build
  - test
#  - deploy

before_script:
#  - echo before_script
  - cd
  - dir
  
#after_script:
#  - echo after_script


linux build job:
  stage: build
  only:
    - master
    - /^release.*$/
    - develop
    - /experimental/
  tags:
    - gcc
  script:
    - "printenv"
    - "pwd"
    - "whoami"
    - "gcc --version"
    - "echo $CI_COMMIT_SHA"
    - "cd $CI_PROJECT_DIR"
    - "git status"
    - "git log -1"
#generation version file
    - "echo '#pragma once' > gitlabci_version.h"
    - "echo >> gitlabci_version.h"
    - "echo '#define GITLAB_CI_BUILD' >> gitlabci_version.h"
    - echo '#define CI_BUILD_REF_SLUG' \"$CI_BUILD_REF_SLUG\" >> gitlabci_version.h
    - echo '#define CI_COMMIT_SHA' \"$CI_COMMIT_SHA\" >> gitlabci_version.h
    - echo '#define GITLAB_USER_NAME' \"$GITLAB_USER_NAME\" >> gitlabci_version.h
    - echo '#define CI_PIPELINE_ID' $CI_PIPELINE_ID >> gitlabci_version.h
    - echo '#define COMPUTERNAME' \"$HOSTNAME\" >> gitlabci_version.h
    - echo '#define BUILD_DATE' \"$(date)\" >> gitlabci_version.h

#Build Project
    - "# ----------------------------------------------"
    - "#               Build Project"
    - "# ----------------------------------------------"    
    - "~/Qt/5.15.2/gcc_64/bin/qmake u7set.pro -spec linux-g++"
    - "make -j6"


windows build job:
  stage: build
  only:
    - master
    - /^release.*$/
    - develop
    - /experimental/
  tags:
    - vs2017
  script:
    - "dir env:"
    - "echo $Env:CI_COMMIT_SHA"
    - "git status"
    - "git log -1"
    - $Env:QT_BIN_DIR="C:\\Qt\\5.15.2\\msvc2019_64"
#generation version file
    - "'#pragma once' > gitlabci_version.h"
    - "' ' >> gitlabci_version.h"
    - "'#define GITLAB_CI_BUILD' >> gitlabci_version.h"
    - "'#define CI_BUILD_REF_SLUG \"' + $env:CI_BUILD_REF_SLUG + '\"' >> gitlabci_version.h"
    - "'#define CI_COMMIT_SHA \"' + $env:CI_COMMIT_SHA + '\"' >> gitlabci_version.h"
    - "'#define GITLAB_USER_NAME \"' + $env:GITLAB_USER_NAME + '\"' >> gitlabci_version.h"
    - "'#define CI_PIPELINE_ID ' + $env:CI_PIPELINE_ID + '' >> gitlabci_version.h"
    - "'#define COMPUTERNAME \"' + $env:HOSTNAME + '\"' >> gitlabci_version.h"
    - "$Env:timestamp = Get-Date -Format 'dd MMMM yyyy HH:mm (K)'"
    - "'#define BUILD_DATE \"' + $Env:timestamp + '\"' >> gitlabci_version.h"
#Build Project
    - "# ----------------------------------------------"
    - "#               Build Project"
    - "# ----------------------------------------------"    
    - "& './gitlab_ci_build.bat'"
#Copy Qt DLLs to bin/release
    - "# ----------------------------------------------"
    - "#               Copy Qt DLL's"
    - "# ----------------------------------------------"
    - "copy \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Redist\\MSVC\\v142\\vcredist_x64.exe\" \"$Env:CI_PROJECT_DIR/bin/release/\""    
    - "copy C:\\libpq_my_build\\libpq.dll \"$Env:CI_PROJECT_DIR/bin/release/\""
    - "copy $Env:QT_BIN_DIR\\bin\\libEGL.dll \"$Env:CI_PROJECT_DIR/bin/release/\""
    - "copy $Env:QT_BIN_DIR\\bin\\libGLESv2.dll \"$Env:CI_PROJECT_DIR/bin/release/\""
    - "copy $Env:QT_BIN_DIR\\bin\\Qt5Core.dll \"$Env:CI_PROJECT_DIR/bin/release/\""
    - "copy $Env:QT_BIN_DIR\\bin\\Qt5Gui.dll \"$Env:CI_PROJECT_DIR/bin/release/\""
    - "copy $Env:QT_BIN_DIR\\bin\\Qt5Network.dll \"$Env:CI_PROJECT_DIR/bin/release/\""
    - "copy $Env:QT_BIN_DIR\\bin\\Qt5PrintSupport.dll \"$Env:CI_PROJECT_DIR/bin/release/\""
    - "copy $Env:QT_BIN_DIR\\bin\\Qt5Qml.dll \"$Env:CI_PROJECT_DIR/bin/release/\""
    - "copy $Env:QT_BIN_DIR\\bin\\Qt5Quick.dll \"$Env:CI_PROJECT_DIR/bin/release/\""
    - "copy $Env:QT_BIN_DIR\\bin\\Qt5SerialPort.dll \"$Env:CI_PROJECT_DIR/bin/release/\""
    - "copy $Env:QT_BIN_DIR\\bin\\Qt5Sql.dll \"$Env:CI_PROJECT_DIR/bin/release/\""
    - "copy $Env:QT_BIN_DIR\\bin\\Qt5Svg.dll \"$Env:CI_PROJECT_DIR/bin/release/\""
    - "copy $Env:QT_BIN_DIR\\bin\\Qt5Test.dll \"$Env:CI_PROJECT_DIR/bin/release/\""
    - "copy $Env:QT_BIN_DIR\\bin\\Qt5Widgets.dll \"$Env:CI_PROJECT_DIR/bin/release/\""
    - "copy $Env:QT_BIN_DIR\\bin\\Qt5WinExtras.dll \"$Env:CI_PROJECT_DIR/bin/release/\""
    - "copy $Env:QT_BIN_DIR\\bin\\Qt5Xml.dll \"$Env:CI_PROJECT_DIR/bin/release/\""
    - "copy $Env:QT_BIN_DIR\\bin\\Qt5Charts.dll \"$Env:CI_PROJECT_DIR/bin/release/\""
# Copy Qt plugins
    - "mkdir \"$Env:CI_PROJECT_DIR/bin/release/bearer\""
    - "copy $Env:QT_BIN_DIR\\plugins\\bearer\\qgenericbearer.dll \"$Env:CI_PROJECT_DIR/bin/release/bearer/\""
    - "mkdir \"$Env:CI_PROJECT_DIR\\bin\\release\\iconengines\""
    - "copy $Env:QT_BIN_DIR\\plugins\\iconengines\\qsvgicon.dll \"$Env:CI_PROJECT_DIR/bin/release/iconengines/\""
    - "mkdir \"$Env:CI_PROJECT_DIR\\bin\\release\\imageformats\""
    - "copy $Env:QT_BIN_DIR\\plugins\\imageformats\\qgif.dll \"$Env:CI_PROJECT_DIR/bin/release/imageformats/\""
    - "copy $Env:QT_BIN_DIR\\plugins\\imageformats\\qicns.dll \"$Env:CI_PROJECT_DIR/bin/release/imageformats/\""
    - "copy $Env:QT_BIN_DIR\\plugins\\imageformats\\qico.dll \"$Env:CI_PROJECT_DIR/bin/release/imageformats/\""
    - "copy $Env:QT_BIN_DIR\\plugins\\imageformats\\qjpeg.dll \"$Env:CI_PROJECT_DIR/bin/release/imageformats/\""
    - "copy $Env:QT_BIN_DIR\\plugins\\imageformats\\qsvg.dll \"$Env:CI_PROJECT_DIR/bin/release/imageformats/\""
    - "copy $Env:QT_BIN_DIR\\plugins\\imageformats\\qtga.dll \"$Env:CI_PROJECT_DIR/bin/release/imageformats/\""
    - "copy $Env:QT_BIN_DIR\\plugins\\imageformats\\qtiff.dll \"$Env:CI_PROJECT_DIR/bin/release/imageformats/\""
    - "copy $Env:QT_BIN_DIR\\plugins\\imageformats\\qwbmp.dll \"$Env:CI_PROJECT_DIR/bin/release/imageformats/\""
    - "copy $Env:QT_BIN_DIR\\plugins\\imageformats\\qwebp.dll \"$Env:CI_PROJECT_DIR/bin/release/imageformats/\""
    - "mkdir \"$Env:CI_PROJECT_DIR\\bin\\release\\platforms\""
    - "copy $Env:QT_BIN_DIR\\plugins\\platforms\\qdirect2d.dll \"$Env:CI_PROJECT_DIR/bin/release/platforms/\""
    - "copy $Env:QT_BIN_DIR\\plugins\\platforms\\qminimal.dll \"$Env:CI_PROJECT_DIR/bin/release/platforms/\""
    - "copy $Env:QT_BIN_DIR\\plugins\\platforms\\qoffscreen.dll \"$Env:CI_PROJECT_DIR/bin/release/platforms/\""
    - "copy $Env:QT_BIN_DIR\\plugins\\platforms\\qwindows.dll \"$Env:CI_PROJECT_DIR/bin/release/platforms/\""
    - "mkdir \"$Env:CI_PROJECT_DIR\\bin\\release\\sqldrivers\""
    - "copy $Env:QT_BIN_DIR\\plugins\\sqldrivers\\qsqlite.dll \"$Env:CI_PROJECT_DIR/bin/release/sqldrivers/\""
    - "copy $Env:QT_BIN_DIR\\plugins\\sqldrivers\\qsqlpsql.dll \"$Env:CI_PROJECT_DIR/bin/release/sqldrivers/\""
    - "mkdir \"$Env:CI_PROJECT_DIR\\bin\\release\\printsupport\""
    - "copy $Env:QT_BIN_DIR\\plugins\\printsupport\\windowsprintersupport.dll \"$Env:CI_PROJECT_DIR/bin/release/printsupport/\""
    - "mkdir \"$Env:CI_PROJECT_DIR\\bin\\release\\styles\""
    - "copy $Env:QT_BIN_DIR\\plugins\\styles\\qwindowsvistastyle.dll \"$Env:CI_PROJECT_DIR/bin/release/styles/\""

#Remove some files not requiered for releases
    - "# ----------------------------------------------"
    - "#               Remove some files not requiered for releases"
    - "# ----------------------------------------------"
    - "del -Force $Env:CI_PROJECT_DIR/bin/release/BaseSrv.exe"
    - "del -Force $Env:CI_PROJECT_DIR/bin/release/CommView.exe"
    - "del -Force $Env:CI_PROJECT_DIR/bin/release/DiagDataSrv.exe"
    
#Signing Files
    - "# ----------------------------------------------"
    - "#               Sign Files"
    - "# ----------------------------------------------"
    - "$SIGNTOOL='C:/Program Files (x86)/Windows Kits/10/App Certification Kit/signtool.exe'"
    - "$K8S_SECRET_DIGITAL_SIGN_CERT = Get-Content c:\\radiy-code-signing\\password.txt"
    - "&$SIGNTOOL sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $K8S_SECRET_DIGITAL_SIGN_CERT bin\\release\\VFrame30.dll"
    - "&$SIGNTOOL sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $K8S_SECRET_DIGITAL_SIGN_CERT bin\\release\\AppDataSrv.exe"
    - "&$SIGNTOOL sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $K8S_SECRET_DIGITAL_SIGN_CERT bin\\release\\ArchSrv.exe"
    - "&$SIGNTOOL sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $K8S_SECRET_DIGITAL_SIGN_CERT bin\\release\\CfgSrv.exe"
    - "&$SIGNTOOL sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $K8S_SECRET_DIGITAL_SIGN_CERT bin\\release\\mconf.exe"
    - "&$SIGNTOOL sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $K8S_SECRET_DIGITAL_SIGN_CERT bin\\release\\PacketSource.exe"
    - "&$SIGNTOOL sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $K8S_SECRET_DIGITAL_SIGN_CERT bin\\release\\PacketViewer.exe"
    - "&$SIGNTOOL sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $K8S_SECRET_DIGITAL_SIGN_CERT bin\\release\\Metrology.exe"
    - "&$SIGNTOOL sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $K8S_SECRET_DIGITAL_SIGN_CERT bin\\release\\Monitor.exe"
    - "&$SIGNTOOL sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $K8S_SECRET_DIGITAL_SIGN_CERT bin\\release\\scm.exe"
    - "&$SIGNTOOL sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $K8S_SECRET_DIGITAL_SIGN_CERT bin\\release\\TuningClient.exe"
    - "&$SIGNTOOL sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $K8S_SECRET_DIGITAL_SIGN_CERT bin\\release\\TuningSrv.exe"
    - "&$SIGNTOOL sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $K8S_SECRET_DIGITAL_SIGN_CERT bin\\release\\u7.exe"    

#Generate ScriptHelp
    - "# ----------------------------------------------"
    - "#               Generate ScriptHelp"
    - "# ----------------------------------------------"
    - "pushd ."	
    - "cd $Env:CI_PROJECT_DIR\\u7\\ScriptHelp"
    - "&./ScriptHelp.bat"
    - "popd"

#Request documents from SVN
    - "# ----------------------------------------------"
    - "#               Request documents from SVN"
    - "# ----------------------------------------------"
    - "pushd ."	
    - "cd $Env:CI_PROJECT_DIR/doc"
    - "&./SvnGetDocs.bat"
    - "popd"

#Build Installer
    - "# ----------------------------------------------"
    - "#               Build Installer"
    - "# ----------------------------------------------"
    - "pushd ."	
    - "cd $Env:CI_PROJECT_DIR/u7setinstall"
    - "&./createinstall.bat"
    - "popd"	
    - "&$SIGNTOOL sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $K8S_SECRET_DIGITAL_SIGN_CERT bin\\*.exe"
    - "$K8S_SECRET_DIGITAL_SIGN_CERT="

  artifacts:
    name: "u7set_0.8.$Env:CI_PIPELINE_ID $Env:CI_BUILD_REF_SLUG $Env:CI_COMMIT_SHA"
    paths:
      - bin/*.exe
      - bin/release/*.exe
      - bin/release/*.dll
      - bin/release/bearer/*.dll
      - bin/release/iconengines/*.dll
      - bin/release/imageformats/*.dll
      - bin/release/platforms/*.dll
      - bin/release/sqldrivers/*.dll
      - bin/release/printsupport/*.dll
      - bin/release/styles/*.dll
      - bin/release/scripthelp/*.*
      - bin/release/scripthelp/search/*.*
      - bin/release/docs/*.pdf
      - bin/release/docs/Appendixes/*.pdf


test job:
  stage: test
  tags:
    - test
  only:
    - master
    - /^release.*$/
    - develop
    - /experimental/
  script:
    - "dir env:"    
    - "echo $Env:CI_COMMIT_SHA"
    - "git status"
    - "git log -1"
#Run XML validation
    - "# ----------------------------------------------"
    - "#               Run XML validation"
    - "# ----------------------------------------------"
    - "pushd ."	
    - "cd $Env:CI_PROJECT_DIR/u7/LogicModuleDescription"
    - "&./validate_xmls.bat"
    - "popd"

#Run unit tests
    - "# ----------------------------------------------"
    - "#               Run unit tests"
    - "# ----------------------------------------------"
    - "&$Env:CI_PROJECT_DIR/bin/release/u7databasetests.exe"
    - "&$Env:CI_PROJECT_DIR/bin/release/SimulatorTests.exe"

#Run Builder test
    - "# ----------------------------------------------"
    - "#               Run BuilderConsole tests"
    - "# ----------------------------------------------"
    - "if (Test-Path c:/temp/build/test_simulator) { Remove-Item c:/temp/build/test_simulator -Recurse -Force; }"
    - "&$Env:CI_PROJECT_DIR/bin/release/BuilderConsole.exe $Env:CI_PROJECT_DIR/Test/BuilderConsoleArgs.xml"

#Run Sim AFB Tests
    - "# ----------------------------------------------"
    - "#               Run Simulator AFBs tests"
    - "# ----------------------------------------------"
    - "&$Env:CI_PROJECT_DIR/bin/release/SimulatorConsole.exe -build=c:/temp/build/test_simulator_v349/build -script=\"$Env:CI_PROJECT_DIR/Simulator/SimProjectTests.js\""

#Run ROVT to check configuration generation
    - "# ----------------------------------------------"
    - "#               Run ROVT tests"
    - "# ----------------------------------------------"
    - "&C:/ROVT/ROVT_C.exe /b:C:\\Temp\\build\\test_simulator_v349\\build"
