variables:
  GIT_DEPTH: "1"

  # Version. Set to the desired release type "Default" or "Stable"
  #
  CI_RELEASE_TYPE: "Default"    # Set to the desired release type "Default" or "Stable"
  CI_MAJOR_VERSION: "11"        # Odd is for development, even is for release
  CI_MINOR_VERSION: "0"
  CI_PATCH_VERSION: "0"         # Path version for Default release is ignored and set to pipeline id.

  # Build and test data
  #
  QT_VERSION: "6.8.1"
  COMPILER_TESTS_PROJECT_NAME: "compiler_tests_v425"
  SIMULATOR_PROJECT_NAME: "test_simulator_v425"
  PGPASSWORD: "P2ssw0rd"

  CTEST_OUTPUT_ON_FAILURE: "1"

stages:
  - prepare
  - build
  - test

before_script:
#  - echo before_script
  - cd
  - dir
  
#after_script:
#  - echo after_script
project_backup_job:
  stage: prepare
  variables:
    GIT_STRATEGY: none
  only:
    - master
    - /^release.*$/
    - develop
    - /experimental/
    - /^.*exp.*$/
    - /^.*rpct-.*$/
    - /^.*RPCT-.*$/
  tags:
    - projectbackup
  script:
    - "# ----------------------------------------------"
    - "#               Create backup of database files "
    - "# ----------------------------------------------"
    - "if (Test-Path \"f:\\u7_${Env:COMPILER_TESTS_PROJECT_NAME}.sql.1\") {  Remove-Item -Verbose -Force \"f:\\TestDatabase\\u7_${Env:COMPILER_TESTS_PROJECT_NAME}.sql.1\" }"
    - "if (Test-Path \"f:\\u7_${Env:SIMULATOR_PROJECT_NAME}.sql.1\") {  Remove-Item -Verbose -Force \"f:\\TestDatabase\\u7_${Env:SIMULATOR_PROJECT_NAME}.sql.1\" }"
    - "pg_dump -h 192.168.75.10 -U u7 -f f:\\TestDatabase\\u7_${Env:COMPILER_TESTS_PROJECT_NAME}.sql.1 u7_${Env:COMPILER_TESTS_PROJECT_NAME}"
    - "pg_dump -h 192.168.75.10 -U u7 -f f:\\TestDatabase\\u7_${Env:SIMULATOR_PROJECT_NAME}.sql.1 u7_${Env:SIMULATOR_PROJECT_NAME}"
    - "f:\\TestDatabase\\UpdateFileIfDifferent.ps1 f:\\TestDatabase\\u7_${Env:COMPILER_TESTS_PROJECT_NAME}.sql.1 f:\\TestDatabase\\u7_${Env:COMPILER_TESTS_PROJECT_NAME}.sql"
    - "f:\\TestDatabase\\UpdateFileIfDifferent.ps1 f:\\TestDatabase\\u7_${Env:SIMULATOR_PROJECT_NAME}.sql.1 f:\\TestDatabase\\u7_${Env:SIMULATOR_PROJECT_NAME}.sql"


linux_build_job:
  stage: build
  needs: ["project_backup_job"]
  only:
    - master
    - /^release.*$/
    - develop
    - /experimental/
    - /^.*exp.*$/
    - /^.*rpct-.*$/
    - /^.*RPCT-.*$/
  tags:
    - gcc
  before_script:
    - export PATH="/home/gitlab-runner/vcpkg:$PATH"
    - export VCPKG_ROOT="/home/gitlab-runner/vcpkg"
  script:
    - "printenv"
    - "pwd"
    - "whoami"
    - "gcc --version"
    - "echo $CI_COMMIT_SHA"
    - "cd $CI_PROJECT_DIR"
    - "git status"
    - "git log -1"

#Build Project
    - "# ----------------------------------------------"
    - "#               Build Project"
    - "# ----------------------------------------------"    
    - "cmake -S . -B ./build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/opt/Qt/${QT_VERSION}/gcc_64 -DBIN_OUT_DIR=$CI_PROJECT_DIR/bin/release"
    - "cmake --build ./build"

  artifacts:
    name: "u7set-linux-x64-${CI_MAJOR_VERSION}.${CI_MINOR_VERSION}.${CI_PATCH_VERSION}-p${CI_PIPELINE_ID}-${CI_RELEASE_TYPE}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}"
    paths:
      - bin/release/*
    exclude:
      - bin/release/**/*.a
#

windows_build_job:
  stage: build
  needs: ["project_backup_job"]
  only:
    - master
    - /^release.*$/
    - develop
    - /experimental/
    - /^.*exp.*$/
    - /^.*rpct-.*$/
    - /^.*RPCT-.*$/
  tags:
    - vs2017
  before_script:
    - $Env:VCPKG_ROOT="C:/data/vcpkg/vcpkg"
    - $Env:VCPKG_DEFAULT_BINARY_CACHE="C:/data/vcpkg/cache_windows_build"
    - $env:Path += ";C:/data/vcpkg/vcpkg"
  script:
    - "dir env:"
    - "echo $Env:CI_COMMIT_SHA"
    - "git status"
    - "git log -1"
    - $Env:QT_BIN_DIR="C:\\Qt\\${Env:QT_VERSION}\\msvc2022_64"
    - $Env:BIN_OUT_DIR="$Env:CI_PROJECT_DIR\\bin\\release"
#Build Project
    - "# ----------------------------------------------"
    - "#               Build Project"
    - "# ----------------------------------------------"    
    - "& './gitlab_ci_build.bat'"
#Copy Qt DLLs to bin/release
    - "# ----------------------------------------------"
    - "#               Copy Qt DLL's"
    - "# ----------------------------------------------"
    - "& './CI/windeploy.bat'"
#Copy PostgreSQL DLL to bin/release
    - "copy C:\\libpq_my_build\\libpq.dll $Env:BIN_OUT_DIR\\"
#Copy FTDI Drivers to release
    - "mkdir \"$Env:BIN_OUT_DIR/ftdi\""
    - "copy C:\\ftdi\\CDM-v2.12.36.4-WHQL-Certified.zip $Env:BIN_OUT_DIR\\ftdi\\"
# Copy documents
    - "mkdir \"$Env:BIN_OUT_DIR/docs\""
    - "copy $Env:CI_PROJECT_DIR\\Metrology\\docs\\Metrology_User_Manual.pdf $Env:BIN_OUT_DIR\\docs\\"
# Copy GlobalScript library
    - "mkdir \"$Env:BIN_OUT_DIR/scripting\""
    - "copy $Env:CI_PROJECT_DIR\\Scripts\\GlobalScript\\*.* $Env:BIN_OUT_DIR\\scripting\\"

#Remove some files not requiered for releases
    - "# ----------------------------------------------"
    - "#               Remove some files not requiered for releases"
    - "# ----------------------------------------------"
    - "del -Force $Env:BIN_OUT_DIR/DiagDataSrv.exe"
    
#Signing Files
    - "# ----------------------------------------------"
    - "#               Sign Files"
    - "# ----------------------------------------------"
#    - "$SIGNTOOL='C:/Program Files (x86)/Windows Kits/10/App Certification Kit/signtool.exe'"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\AppDataSrv.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\ArchSrv.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\CfgSrv.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\mconf.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\PacketSource.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\PacketViewer.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\Metrology.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\Monitor.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\scm.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\TuningClient.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\TuningSrv.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\u7.exe"    

#Request documents from SVN
    - "# ----------------------------------------------"
    - "#               Request documents from SVN"
    - "# ----------------------------------------------"
    - "pushd ."	
    - "cd $Env:CI_PROJECT_DIR/doc"
    - "&./SvnGetDocs.bat"
    - "popd"

#Build Installer
    - "# ----------------------------------------------"
    - "#               Build Installer"
    - "# ----------------------------------------------"
    - "cmake --build ./build --target create_install"	
#    - "&$SIGNTOOL sign /v /a  /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\..\\*.exe"

  artifacts:
    name: "u7set-win-x64-${CI_MAJOR_VERSION}.${CI_MINOR_VERSION}.${CI_PATCH_VERSION}-p${CI_PIPELINE_ID}-${CI_RELEASE_TYPE}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}"
    paths:
      - bin/*.exe
      - bin/release/*.exe
      - bin/release/*.dll
      - bin/release/iconengines/*.dll
      - bin/release/imageformats/*.dll
      - bin/release/networkinformation/*.dll
      - bin/release/platforms/*.dll
      - bin/release/sqldrivers/*.dll
      - bin/release/styles/*.dll
      - bin/release/tls/*.dll
      - bin/release/translations/*.qm
      - bin/release/scripting/*.*
      - bin/release/scripthelp/*.*
      - bin/release/scripthelp/search/*.*
      - bin/release/docs/*.pdf
      - bin/release/docs/Appendixes/*.pdf
      - bin/release/dev/**/*
      - bin/release/ftdi/**/*
      - bin/release/license/**/*

windows_test_job:
  stage: test
  needs: ["windows_build_job"]
  tags:
    - test
  only:
    - master
    - /^release.*$/
    - develop
    - /experimental/
    - /^.*exp.*$/
    - /^.*rpct-.*$/
    - /^.*RPCT-.*$/
  script:
    - "# dir env:"
    - "echo $Env:CI_COMMIT_SHA"
    - "git status"
    - "git log -1"
#Run Create databases for compiler and simulator tests
    - echo Creating PostgreSQL databases...
    - psql -U postgres -c "CREATE DATABASE u7_${Env:COMPILER_TESTS_PROJECT_NAME} OWNER u7;"
    - Get-Content c:\Data\u7_${Env:COMPILER_TESTS_PROJECT_NAME}.sql | psql -U postgres u7_${Env:COMPILER_TESTS_PROJECT_NAME}
    - psql -U postgres -c "CREATE DATABASE u7_${Env:SIMULATOR_PROJECT_NAME} OWNER u7;"
    - Get-Content c:\Data\u7_${Env:SIMULATOR_PROJECT_NAME}.sql | psql -U postgres u7_${Env:SIMULATOR_PROJECT_NAME}
#Run XML validation
    - "# ----------------------------------------------"
    - "#               Run XML validation"
    - "# ----------------------------------------------"
    - "pushd ."	
    - "cd $Env:CI_PROJECT_DIR/Presets/LogicModuleDescription/generated"
    - "&./validate_xmls.bat"
    - "popd"

#Run unit tests
    - "# ----------------------------------------------"
    - "#               Run unit tests"
    - "# ----------------------------------------------"
    - "&$Env:CI_PROJECT_DIR/bin/release/ClientTests.exe --gtest_filter=-AdsConnectionTests.*:ConfigControllerTests.*:AdsSourceStateConnectionTests.*:TuningConnectionTests.*:RtDataProviderTests.*"
    - "&$Env:CI_PROJECT_DIR/bin/release/SimulatorTests.exe"
    - "&$Env:CI_PROJECT_DIR/bin/release/TestSuiteLibUnitTests.exe"
    - "&$Env:CI_PROJECT_DIR/bin/release/MetrologyTests.exe"
    #- "&$Env:CI_PROJECT_DIR/bin/release/LicenseLibTests.exe"
    - "&$Env:CI_PROJECT_DIR/bin/release/u7databasetests.exe -config=\"$Env:CI_PROJECT_DIR/Tests/u7databasetestsArgs.xml\""

#Run Builder test
    - "# ----------------------------------------------"
    - "#               Run BuilderConsole tests"
    - "# ----------------------------------------------"
    - "if (Test-Path c:/temp/build/test_simulator) { Remove-Item c:/temp/build/test_simulator -Recurse -Force; }"
    - "&$Env:CI_PROJECT_DIR/bin/release/BuilderConsole.exe $Env:CI_PROJECT_DIR/Tests/BuilderConsoleArgs.xml"

#Run Compiler tests
    - "# ----------------------------------------------"
    - "#               Run Compiler tests"
    - "# ----------------------------------------------"
    - "&$Env:CI_PROJECT_DIR/bin/release/BuilderConsole.exe $Env:CI_PROJECT_DIR/Tests/CompilerTestsArgs.xml"

#Run Sim AFB Tests
    - "# ----------------------------------------------"
    - "#               Run Simulator AFBs tests"
    - "# ----------------------------------------------"
    - "&$Env:CI_PROJECT_DIR/bin/release/SimulatorConsole.exe -build=c:/temp/build/$Env:SIMULATOR_PROJECT_NAME/build -script=\"$Env:CI_PROJECT_DIR/libs/SimulatorLib/Scripts/SimProjectTests.js\""

#Run AdsBridge tests (limited - without AppDataService)
    - "# ----------------------------------------------"
    - "#               Run AdsBridge tests"
    - "# ----------------------------------------------"
    - "&$Env:CI_PROJECT_DIR/bin/release/AdsBridgeTests.exe --config=c:/temp/build/$Env:SIMULATOR_PROJECT_NAME/build/SYSTEMID_CLIENTTEST_WS03_ADSBRIDGE/Configuration.xml --gtest_filter=-AdsBridgeTests.AdsGetTcpConnectionStatuses:AdsBridgeTests.AdsSignalParamsAndStatesLoaded:AdsBridgeTests.AdsGetSignalList:AdsBridgeTests.AdsGetSignalParams:AdsBridgeTests.AdsGetSignalStates:AdsBridgeTests.AdsGetSignalStatesRequestSignal"

#Run ROVT to check configuration generation
    - "# ----------------------------------------------"
    - "#               Run ROVT tests"
    - "# ----------------------------------------------"
    - "#&C:/ROVT/ROVT_C.exe /b:C:\\Temp\\build\\$Env:SIMULATOR_PROJECT_NAME\\build"


linux_test_job:
  stage: test
  needs: ["linux_build_job"]
  tags:
    - gcctest
  only:
    - master
    - /^release.*$/
    - develop
    - /experimental/
    - /^.*exp.*$/
    - /^.*rpct-.*$/
    - /^.*RPCT-.*$/
  script:
    - "printenv"
    - "echo $CI_COMMIT_SHA"
    - "cd $CI_PROJECT_DIR"
    - "git status"
    - "git log -1"
#Run XML validation
#    - "# ----------------------------------------------"
#    - "#               Run XML validation"
#    - "# ----------------------------------------------"
    - "pushd $CI_PROJECT_DIR/Presets/LogicModuleDescription/generated"
    - "chmod a+x validate_xmls.sh"
    - "./validate_xmls.sh"
    - "popd"

#Create databases for compiler and simulator tests
    - "echo Creating PostgreSQL databases..."
    - "pushd /tmp"
    - "cp $CI_PROJECT_DIR/Tests/ImportDatabase.sh /tmp"
    - "cp /mnt/f/TestDatabase/u7_${COMPILER_TESTS_PROJECT_NAME}.sql /tmp"
    - "cp /mnt/f/TestDatabase/u7_${SIMULATOR_PROJECT_NAME}.sql /tmp"
    - "echo P2ssw0rd | su postgres /tmp/ImportDatabase.sh /tmp/u7_${COMPILER_TESTS_PROJECT_NAME}.sql u7_${COMPILER_TESTS_PROJECT_NAME} 5433"
    - "echo P2ssw0rd | su postgres /tmp/ImportDatabase.sh /tmp/u7_${SIMULATOR_PROJECT_NAME}.sql u7_${SIMULATOR_PROJECT_NAME} 5433"
    - "rm /tmp/ImportDatabase.sh"
    - "rm /tmp/u7_${COMPILER_TESTS_PROJECT_NAME}.sql"
    - "rm /tmp/u7_${SIMULATOR_PROJECT_NAME}.sql"
    - "popd"
    - "echo Creating PostgreSQL databases complete"

#Run Builder test
    - "# ----------------------------------------------"
    - "#               Run BuilderConsole tests"
    - "# ----------------------------------------------"
    - "if [ -d \"/tmp/build/test_simulator\" ]; then rm -Rf /tmp/build/test_simulator; fi"
    - "$CI_PROJECT_DIR/bin/release/BuilderConsole $CI_PROJECT_DIR/Tests/BuilderConsoleArgsLinux.xml"
    
#Run Compiler tests
    - "# ----------------------------------------------"
    - "#               Run Compiler tests"
    - "# ----------------------------------------------"
    - "$CI_PROJECT_DIR/bin/release/BuilderConsole $CI_PROJECT_DIR/Tests/CompilerTestsArgsLinux.xml"

#Run Sim AFB Tests
    - "# ----------------------------------------------"
    - "#               Run Simulator AFBs tests"
    - "# ----------------------------------------------"
    - "$CI_PROJECT_DIR/bin/release/SimulatorConsole -build=/tmp/build/${SIMULATOR_PROJECT_NAME}/build -script=\"$CI_PROJECT_DIR/libs/SimulatorLib/Scripts/SimProjectTests.js\""

#Run unit tests
    - "# ----------------------------------------------"
    - "#               Run client tests"
    - "# ----------------------------------------------"
    - "function StopServices () { pkill CfgSrv || true; pkill AppDataSrv || true; pkill TuningSrv || true; pkill SimulatorConsol || true; sleep 2; }"
    - "trap StopServices EXIT"
    - "pushd $CI_PROJECT_DIR/bin/release"
    - "StopServices || true"
    - "cp /tmp/build/${SIMULATOR_PROJECT_NAME}/build/RunServiceScripts/Linux/linux_test_job_systemid_clienttest*.sh ."
    - "chmod +x *.sh"
    - "./linux_test_job_systemid_clienttest_ws01_cfgs.sh simulation < /dev/null > clienttest_ws01_cfgs.out 2>&1 &"
    - "sleep 5"
    - "./linux_test_job_systemid_clienttest_ws02_cfgs.sh simulation < /dev/null > clienttest_ws02_cfgs.out 2>&1 &"
    - "sleep 5"
    - "./linux_test_job_systemid_clienttest_ws01_ads.sh < /dev/null > clienttest_ws01_ads.out 2>&1 &"
    - "./linux_test_job_systemid_clienttest_ws02_ads.sh < /dev/null > clienttest_ws02_ads.out 2>&1 &"
    - "./linux_test_job_systemid_clienttest_ws01_tuns.sh < /dev/null > clienttest_ws01_tuns.out 2>&1 &"
    - "./linux_test_job_systemid_clienttest_ws01_tuns2.sh < /dev/null > clienttest_ws01_tuns2.out 2>&1 &"
    - "./linux_test_job_systemid_clienttest_ws02_tuns.sh < /dev/null > clienttest_ws02_tuns.out 2>&1 &"
    - "./linux_test_job_systemid_clienttest_ws04_tuns.sh < /dev/null > clienttest_ws04_tuns.out 2>&1 &"
    - "./SimulatorConsole -build=/tmp/build/${SIMULATOR_PROJECT_NAME}/build -profile=linux_test_job -enable_lan -script=\"$CI_PROJECT_DIR/Tests/ClientTests/Scripts/TuningTests.js\" > SimulatorConsole.out 2>&1 &"
    - "sleep 6"
    - "jobs"
    - "./ClientTests -build=/tmp/build/${SIMULATOR_PROJECT_NAME}/build -profile=linux_test_job"
    - "./AdsBridgeTests --config=/tmp/build/${SIMULATOR_PROJECT_NAME}/build/SYSTEMID_CLIENTTEST_WS03_ADSBRIDGE/Configuration.xml --profile=linux_test_job"
    - "export QT_QPA_PLATFORM=offscreen"
    - "./TestSuiteConsole -settings=\"../../Tests/TestSuiteConsoleLinuxTest.xml\" -nosecurity"
    - "./TestSuiteConsole -settings=\"../../Tests/TestSuiteConsoleLinuxTest.xml\" -scripts_path=/tmp/build/${SIMULATOR_PROJECT_NAME}/build/SYSTEMID_CLIENTTEST_WS01_TESTSUITE -nosecurity"
    - "StopServices || true"
    - "popd"

#Run unit tests
    - "# ----------------------------------------------"
    - "#               Run unit tests"
    - "# ----------------------------------------------"
    - "$CI_PROJECT_DIR/bin/release/SimulatorTests"
    - "$CI_PROJECT_DIR/bin/release/TestSuiteLibUnitTests"
    - "$CI_PROJECT_DIR/bin/release/MetrologyTests"
    #- "$CI_PROJECT_DIR/bin/release/LicenseLibTests"
    - "$CI_PROJECT_DIR/bin/release/u7databasetests -config=$CI_PROJECT_DIR/Tests/u7databasetestsArgsLinux.xml"

#Run ROVT to check configuration generation
#    - "# ----------------------------------------------"
#    - "#               Run ROVT tests"
#    - "# ----------------------------------------------"
#    - "#&C:/ROVT/ROVT_C.exe /b:C:\\Temp\\build\\${SIMULATOR_PROJECT_NAME}\\build"


linux_code_coverage_job:
  stage: test
  needs: ["project_backup_job"]
  tags:
    - testlinux
  only:
    - master
    - /^release.*$/
    - develop
    - /experimental/
    - /^.*exp.*$/
    - /^.*rpct-.*$/
    - /^.*RPCT-.*$/
  before_script:
    - export PATH="/home/gitlab-runner/vcpkg:$PATH"
    - export VCPKG_ROOT="/home/gitlab-runner/vcpkg"
  script:
    - "printenv"
    - "echo $CI_COMMIT_SHA"
    - "cd $CI_PROJECT_DIR"
    - "git status"
    - "git log -1"
    - "# ----------------------------------------------"
    - "#               Import DB Projects              "
    - "# ----------------------------------------------"
    - "echo Creating PostgreSQL databases..."
    - "pushd /tmp"
    - "cp $CI_PROJECT_DIR/Tests/ImportDatabase.sh /tmp"
    - "cp /mnt/f/TestDatabase/u7_${SIMULATOR_PROJECT_NAME}.sql /tmp"
    - "echo P2ssw0rd | su postgres /tmp/ImportDatabase.sh /tmp/u7_${SIMULATOR_PROJECT_NAME}.sql u7_${SIMULATOR_PROJECT_NAME} 5434"
    - "rm /tmp/ImportDatabase.sh"
    - "rm /tmp/u7_${SIMULATOR_PROJECT_NAME}.sql"
    - "popd"
    - "echo Creating PostgreSQL databases complete"
    - "# ----------------------------------------------"
    - "#                    Build                      "
    - "# ----------------------------------------------"
    - "cmake -S . -B ./build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=/opt/Qt/${QT_VERSION}/gcc_64 -DBIN_OUT_DIR=$CI_PROJECT_DIR/bin/debug -DCODE_COVERAGE=ON -DADDRESS_SANITIZER=ON"
    - "cmake --build ./build"    
    - "# ----------------------------------------------"
    - "#           Collect Test Coverage Data          "
    - "# ----------------------------------------------"
    - "./Tests/CodeCoverage.sh"

  coverage: '/lines......: \d+\.\d+/'
  artifacts:
    name: "coverage_report.$CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"
    paths:
#      - CodeCoverage/coverage.xml
      - CodeCoverage/Report/
#    reports:
#      coverage_report:
#        coverage_format: cobertura
#        path: CodeCoverage/coverage.xml


