variables:
  GIT_DEPTH: "3"
  
stages:
  - build
#  - test
#  - deploy

before_script:
#  - echo before_script
  - cd
  - dir
  - set
  
#after_script:
#  - echo after_script

windows build job:
  stage: build
  only:
#    - /^release.*$/
    - master
    - develop
    - experimental
  tags:
    - vs2017
  script:
    - "IF \"%CI_BUILD_REF_SLUG%\"==\"master\" (signtool.exe sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p %K8S_SECRET_DIGITAL_SIGN_CERT_PASSWORD% bin_Win32\\*.dll)"
    - "echo %CI_COMMIT_SHA%"
    - "git status"
    - "git log -1"
#generation version file
    - "echo #pragma once > gitlabci_version.h"
    - "echo. >> gitlabci_version.h"
    - "echo #define GITLAB_CI_BUILD >> gitlabci_version.h"
    - "echo #define CI_BUILD_REF_SLUG \"%CI_BUILD_REF_SLUG%\" >> gitlabci_version.h"
    - "echo #define CI_COMMIT_SHA \"%CI_COMMIT_SHA%\" >> gitlabci_version.h"
    - "echo #define GITLAB_USER_NAME \"%GITLAB_USER_NAME%\" >> gitlabci_version.h"
    - "echo #define CI_PIPELINE_ID %CI_PIPELINE_ID% >> gitlabci_version.h"
    - "echo #define COMPUTERNAME \"%COMPUTERNAME%\" >> gitlabci_version.h"
    - "echo #define BUILD_DATE \"%date% %time%\" >> gitlabci_version.h"
    - "call \"C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Auxiliary/Build/vcvarsall.bat\" x86_amd64"
    - "cl.exe"
    - "C:/Qt/5.12.2/msvc2017_64/bin/qmake --version"
    - "C:/Qt/5.12.2/msvc2017_64/bin/qmake.exe %CI_PROJECT_DIR%/u7set.pro -spec win32-msvc"
    - "C:/Qt/Tools/QtCreator/bin/jom.exe qmake_all"
    - "C:/Qt/Tools/QtCreator/bin/jom.exe"
#Copy Qt DLLs to bin/release
    - "echo off"
    - "echo ----------------------------------------------"
    - "echo               Copy Qt DLL's"
    - "echo ----------------------------------------------"
    - "echo on"
    - "copy \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Redist\\MSVC\\14.16.27012\\vcredist_x64.exe\" \"%CI_PROJECT_DIR%/bin/release/\""
    - "copy C:\\libpq_my_build\\libpq.dll \"%CI_PROJECT_DIR%/bin/release/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\bin\\libEGL.dll \"%CI_PROJECT_DIR%/bin/release/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\bin\\libGLESv2.dll \"%CI_PROJECT_DIR%/bin/release/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\bin\\Qt5Core.dll \"%CI_PROJECT_DIR%/bin/release/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\bin\\Qt5Gui.dll \"%CI_PROJECT_DIR%/bin/release/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\bin\\Qt5Network.dll \"%CI_PROJECT_DIR%/bin/release/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\bin\\Qt5PrintSupport.dll \"%CI_PROJECT_DIR%/bin/release/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\bin\\Qt5Qml.dll \"%CI_PROJECT_DIR%/bin/release/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\bin\\Qt5Quick.dll \"%CI_PROJECT_DIR%/bin/release/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\bin\\Qt5SerialPort.dll \"%CI_PROJECT_DIR%/bin/release/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\bin\\Qt5Sql.dll \"%CI_PROJECT_DIR%/bin/release/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\bin\\Qt5Svg.dll \"%CI_PROJECT_DIR%/bin/release/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\bin\\Qt5Test.dll \"%CI_PROJECT_DIR%/bin/release/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\bin\\Qt5Widgets.dll \"%CI_PROJECT_DIR%/bin/release/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\bin\\Qt5Xml.dll \"%CI_PROJECT_DIR%/bin/release/\""
# Copy Qt plugins
    - "mkdir \"%CI_PROJECT_DIR%/bin/release/bearer\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\plugins\\bearer\\qgenericbearer.dll \"%CI_PROJECT_DIR%/bin/release/bearer/\""
    - "mkdir \"%CI_PROJECT_DIR%/bin/release/iconengines\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\plugins\\iconengines\\qsvgicon.dll \"%CI_PROJECT_DIR%/bin/release/iconengines/\""
    - "mkdir \"%CI_PROJECT_DIR%/bin/release/imageformats\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\plugins\\imageformats\\qgif.dll \"%CI_PROJECT_DIR%/bin/release/imageformats/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\plugins\\imageformats\\qicns.dll \"%CI_PROJECT_DIR%/bin/release/imageformats/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\plugins\\imageformats\\qico.dll \"%CI_PROJECT_DIR%/bin/release/imageformats/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\plugins\\imageformats\\qjpeg.dll \"%CI_PROJECT_DIR%/bin/release/imageformats/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\plugins\\imageformats\\qsvg.dll \"%CI_PROJECT_DIR%/bin/release/imageformats/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\plugins\\imageformats\\qtga.dll \"%CI_PROJECT_DIR%/bin/release/imageformats/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\plugins\\imageformats\\qtiff.dll \"%CI_PROJECT_DIR%/bin/release/imageformats/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\plugins\\imageformats\\qwbmp.dll \"%CI_PROJECT_DIR%/bin/release/imageformats/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\plugins\\imageformats\\qwebp.dll \"%CI_PROJECT_DIR%/bin/release/imageformats/\""
    - "mkdir \"%CI_PROJECT_DIR%/bin/release/platforms\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\plugins\\platforms\\qdirect2d.dll \"%CI_PROJECT_DIR%/bin/release/platforms/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\plugins\\platforms\\qminimal.dll \"%CI_PROJECT_DIR%/bin/release/platforms/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\plugins\\platforms\\qoffscreen.dll \"%CI_PROJECT_DIR%/bin/release/platforms/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\plugins\\platforms\\qwindows.dll \"%CI_PROJECT_DIR%/bin/release/platforms/\""
    - "mkdir \"%CI_PROJECT_DIR%/bin/release/sqldrivers\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\plugins\\sqldrivers\\qsqlite.dll \"%CI_PROJECT_DIR%/bin/release/sqldrivers/\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\plugins\\sqldrivers\\qsqlpsql.dll \"%CI_PROJECT_DIR%/bin/release/sqldrivers/\""
    - "mkdir \"%CI_PROJECT_DIR%/bin/release/printsupport\""
    - "copy C:\\Qt\\5.12.2\\msvc2017_64\\plugins\\printsupport\\windowsprintersupport.dll \"%CI_PROJECT_DIR%/bin/release/printsupport/\""

#Run XML validation
    - "echo ----------------------------------------------"
    - "echo               Run XML validation"
    - "echo ----------------------------------------------"
    - "pushd ."	
    - "cd %CI_PROJECT_DIR%\\u7\\LogicModuleDescription"
    - "call validate_xmls.bat"
    - "popd ."

#Run unit tests
    - "echo ----------------------------------------------"
    - "echo               Run unit tests"
    - "echo ----------------------------------------------"
    - "%CI_PROJECT_DIR%\\bin\\release\\u7databasetests.exe"

#Run Builder test
    - "echo ----------------------------------------------"
    - "echo               Run BuilderConsole tests"
    - "echo ----------------------------------------------"
    - "rmdir /Q /S c:\\temp\\build\\test_simulator-debug"    
    - "%CI_PROJECT_DIR%\\bin\\release\\BuilderConsole.exe 127.0.0.1 5432 u7 P2ssw0rd test_simulator_v286 Administrator P2ssw0rd c:\\temp\\build\\ debug"    

#Remove some files not requiered for releases
    - "echo ----------------------------------------------"
    - "echo               Remove some files not requiered for releases"
    - "echo ----------------------------------------------"
    - "del /F /Q bin\\release\\BuilderConsole.exe"
    - "del /F /Q bin\\release\\CommView.exe"
    - "del /F /Q bin\\release\\DiagDataSrv.exe"
    - "del /F /Q bin\\release\\SimulatorConsole.exe"
    - "del /F /Q bin\\release\\TuningIPEN.exe"
    - "del /F /Q bin\\release\\u7databasetests.exe"

#Build Installer
    - "echo ----------------------------------------------"
    - "echo               Build Installer"
    - "echo ----------------------------------------------"
    - "call u7setinstall\\createinstall.bat"
    
#Signing Files
    - "echo ----------------------------------------------"
    - "echo               Sign Files"
    - "echo ----------------------------------------------"
    - "dir"
    - "set"
    - "signtool.exe sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p %K8S_SECRET_DIGITAL_SIGN_CERT_PASSWORD% bin\\release\\VFrame30.dll"
    - "signtool.exe sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p %K8S_SECRET_DIGITAL_SIGN_CERT_PASSWORD% bin\\release\\AppDataSrv.exe"
    - "signtool.exe sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p %K8S_SECRET_DIGITAL_SIGN_CERT_PASSWORD% bin\\release\\ArchSrv.exe"
    - "signtool.exe sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p %K8S_SECRET_DIGITAL_SIGN_CERT_PASSWORD% bin\\release\\CfgSrv.exe"
    - "signtool.exe sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p %K8S_SECRET_DIGITAL_SIGN_CERT_PASSWORD% bin\\release\\mconf.exe"
    - "signtool.exe sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p %K8S_SECRET_DIGITAL_SIGN_CERT_PASSWORD% bin\\release\\Metrology.exe"
    - "signtool.exe sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p %K8S_SECRET_DIGITAL_SIGN_CERT_PASSWORD% bin\\release\\Monitor.exe"
    - "signtool.exe sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p %K8S_SECRET_DIGITAL_SIGN_CERT_PASSWORD% bin\\release\\scm.exe"
    - "signtool.exe sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p %K8S_SECRET_DIGITAL_SIGN_CERT_PASSWORD% bin\\release\\TuningClient.exe"
    - "signtool.exe sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p %K8S_SECRET_DIGITAL_SIGN_CERT_PASSWORD% bin\\release\\TuningSrv.exe"
    - "signtool.exe sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p %K8S_SECRET_DIGITAL_SIGN_CERT_PASSWORD% bin\\release\\u7.exe"
    - "signtool.exe sign /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p %K8S_SECRET_DIGITAL_SIGN_CERT_PASSWORD% *.exe"
    - "echo %K8S_SECRET_DIGITAL_SIGN_CERT_PASSWORD%"

  
  artifacts:
    name: "u7set_0.8.%CI_PIPELINE_ID%_%CI_BUILD_REF_SLUG%_%CI_COMMIT_SHA%"
    paths:
      - bin/*.exe
      - bin/release/*.exe
      - bin/release/*.dll
      - bin/release/bearer/*.dll
      - bin/release/iconengines/*.dll
      - bin/release/imageformats/*.dll
      - bin/release/platforms/*.dll
      - bin/release/sqldrivers/*.dll
      - bin/release/printsupport/*.dll

#deploy job:
#  stage: deploy
#  tags:
#    - vs2017  
#  only:
#    - /^release.*$/
#    - master
#    - develop
#  script:
    # cannot create a tag as REPO is read only (((  
    #- "git tag v0.8.%CI_BUILD_ID%"
    #- "git push --tags"

