variables:
  GIT_DEPTH: "1"

  # Version. Set to the desired release type "Default" or "Stable"/
  #
  CI_RELEASE_TYPE: "Default"    # Set to the desired release type "Default" or "Stable".
  CI_MAJOR_VERSION: "13"        # Odd is for development, even is for release.
  CI_MINOR_VERSION: "0"
  CI_PATCH_VERSION: "0"         # Path version for Default release is ignored and set to pipeline id.

  # Build and test data
  #
  QT_VERSION: "6.8.1"
  COMPILER_TESTS_PROJECT_NAME: "compiler_tests_v441"
  SIMULATOR_PROJECT_NAME: "test_simulator_v441"
  PGPASSWORD: "P2ssw0rd"

  CTEST_OUTPUT_ON_FAILURE: "1"
  
  CI_RV_MODEL: "1"              # Build RV Model projects (RAES NTC), comment out to disable.

  GIT_TERMINAL_PROMPT: "0"      # Prevent Git from ever prompting

stages:
  - prepare
  - build
  - test

before_script:
  - cd
  - dir

include:
# stage: prepare
  - local: 'CI/.gitlab-job-project-backup.yml'

# stage: build
  - local: 'CI/.gitlab-job-gateway-example.yml'
  - local: 'CI/.gitlab-job-linux-build.yml'
  - local: 'CI/.gitlab-job-windows-adsbridge-build.yml'
  - local: 'CI/.gitlab-job-windows-build.yml'

# stage: test
  - local: 'CI/.gitlab-job-linux-cc.yml'
  - local: 'CI/.gitlab-job-linux-test.yml'
  - local: 'CI/.gitlab-job-windows-test.yml'
