stages:
  - build
  - test
  - deploy

before_script:
  - echo before_script
  - cd
  - dir
  - set
  
after_script:
  - echo after_script

windows build job:
  stage: build
  tags:
    - vs2017
  script:
    - "echo ------------------------------------"
    - "echo -   JOB STARTED: windows build     -"
    - "echo ------------------------------------"
    - "@echo i'm a result >> aaa.zip"
#    - ToDo Pack bin to zip
  after_script:
#    - "echo ToDo: Clean up build stuff and evering else"
  artifacts:
    paths:
      - bin/*.zip