variables:
  GIT_DEPTH: "3"
  
stages:
  - build
  - test
  - deploy

before_script:
  - echo before_script
  - cd
  - dir
  - set
  
after_script:
  - echo after_script

windows build job:
  stage: build
  tags:
    - vs2017
  script:
    - "echo ------------------------------------"
    - "echo -   JOB STARTED: windows build     -"
    - "echo ------------------------------------"
    - "echo %CI_COMMIT_SHA%"
  after_script:
#    - "echo ToDo: Clean up build stuff and evering else"
  artifacts:
    paths:
      - bin/release/*.exe
      - bin/release/*.dll
      - bin/release/*.lib
      - bin/release/*.exp

deploy job:
  stage: deploy
  only:
    - /^release.*$/
  script:
    - "echo ------------------------------------"
    - "echo -   JOB STARTED: deploy            -"
    - "echo ------------------------------------"
#    - TO DO Upload zopped exe to drive.goodle...
