cmake_minimum_required(VERSION 3.16)

enable_testing()

add_subdirectory(AdsGatewayTests)
add_subdirectory(ArchV3Tests)
add_subdirectory(ClientTests)
add_subdirectory(GatewayTests)
add_subdirectory(MetrologyTests)
add_subdirectory(TestSuiteLibUnitTests)
add_subdirectory(u7databaseTests)
add_subdirectory(UtilsTests)