#pragma once

#include <QSqlQuery>

#include "../lib/SimpleThread.h"
#include "../lib/CircularLogger.h"
#include "../lib/TimeStamp.h"
#include "../lib/Hash.h"
#include "../lib/Queue.h"
#include "../lib/SocketIO.h"

class TcpArchRequestsServer;

struct ArchRequestParam
{
	// params from ARCHS_GET_APP_SIGNALS_STATES_START request
	//
	TimeType timeType = TimeType::System;

	qint64 startTime = 0;
	qint64 endTime = 0;

	int signalHashesCount = 0;

	Hash signalHashes[ARCH_REQUEST_MAX_SIGNALS];

	// requestID generated by TcpArchiveRequestServer
	//
	quint32 requestID = 0;
};


class ArchRequestContext
{
public:
	ArchRequestContext(const ArchRequestParam& param);
	~ArchRequestContext();

	quint32 requestID() const { return m_param.requestID; }
	bool isDataReady() const { return m_dataReady; }

	int totalStates() const { return m_totalStates; }
	int sentStates() const { return m_sentStates; }

	ArchiveError archError() const { return m_archError; }

private:
	void setArchError(ArchiveError err) { m_archError = err; }
	void setDataReady(bool ready) { m_dataReady = ready; }

	bool createQuery(QSqlDatabase& db, const QString& queryStr);

	TimeType timeType() const { return m_param.timeType; }

	qint64 startTime() const { return m_param.startTime; }
	qint64 endTime() const { return m_param.endTime; }

	int signalHashesCount() const { return m_param.signalHashesCount; }
	const Hash* signalHashes() const { return m_param.signalHashes; }

	bool executeQuery(CircularLoggerShared& logger);

private:
	ArchRequestParam m_param;

	QSqlQuery* m_query = nullptr;
	QString m_queryStr;

	ArchiveError m_archError = ArchiveError::Success;

	bool m_dataReady = false;

	int m_totalStates = 0;
	int m_sentStates = 0;

	friend class ArchRequestThreadWorker;
};

typedef std::shared_ptr<ArchRequestContext> ArchRequestContextShared;


class ArchRequestThreadWorker : public SimpleThreadWorker
{
	Q_OBJECT

public:
	ArchRequestThreadWorker(const QString& projectID, const QHash<Hash, bool>& archSignals, CircularLoggerShared& logger);

	ArchRequestContextShared startNewRequest(ArchRequestParam& param);
	void finalizeRequest(quint32 requestID);

signals:
	void newRequest(ArchRequestContextShared context);

private:
	virtual void onThreadStarted() override;
	virtual void onThreadFinished() override;

	bool tryConnectToDatabase();

	void onNewRequest(ArchRequestContextShared context);
	bool createQueryStr(ArchRequestContextShared context, QString& queryStr);

	QString getCmpField(TimeType timeType);

private:
	static const char* FIELD_PLANT_TIME;
	static const char* FIELD_SYSTEM_TIME;
	static const char* FIELD_LOCAL_TIME;
	static const char* FIELD_ARCH_ID;
	static const char* FIELD_VALUE;
	static const char* FIELD_FLAGS;

	QString m_projectID;
	CircularLoggerShared m_logger;

	QSqlDatabase* m_db = nullptr;				// project archive database

	QMutex m_requestContextsMutex;

	QHash<quint32, ArchRequestContextShared> m_requestContexts;		//	requestID => ArchRequestContext

	QQueue<ArchRequestContextShared> m_newRequests;

	ArchRequestContextShared m_currentRequest;

	const QHash<Hash, bool>& m_archSignals;
};


class ArchRequestThread : public SimpleThread
{
public:
	ArchRequestThread(const QString &projectID, const QHash<Hash, bool>& archSignals, CircularLoggerShared& logger);

	ArchRequestContextShared startNewRequest(ArchRequestParam& param);
	void finalizeRequest(quint32 requestID);

private:
	ArchRequestThreadWorker* m_worker = nullptr;
};

