@startuml

!include ./CommonLib.puml
!include ./OnlineLib.puml
!include ./UtilsLib.puml
!include ./Protobuf.puml
!include ./ServiceLib.puml
!include ./AppSignalLib.puml
!include ./HardwareLib.puml

[AppDataService]
AppDataService -up-> [CommonLib]
AppDataService -up-> [OnlineLib]
AppDataService -up-> [UtilsLib]
AppDataService -up-> [Protobuf]
AppDataService -up-> [ServiceLib]
AppDataService -up-> [AppSignalLib]
AppDataService -up-> [HardwareLib]

@enduml