@startuml

!include ./CommonLib.puml
!include ./UtilsLib.puml
!include ./Protobuf.puml

[AppSignalLib]

AppSignalLib -up-> UtilsLib
AppSignalLib -up-> CommonLib
AppSignalLib -up-> Protobuf


@enduml  