@startuml

!include ./CommonLib.puml
!include ./UtilsLib.puml
!include ./OnlineLib.puml
!include ./Protobuf.puml
!include ./ServiceLib.puml
!include ./AppSignalLib.puml

[ArchivingService]
ArchivingService -up-> [CommonLib]
ArchivingService -up-> [UtilsLib]
ArchivingService -up-> [OnlineLib]
ArchivingService -up-> [Protobuf]
ArchivingService -up-> [ServiceLib]
ArchivingService -up-> [AppSignalLib]

@enduml