@startuml

!include ./Protobuf.puml
!include ./Builder.puml
!include ./UtilsLib.puml

[BuilderConsole]
BuilderConsole -up-> [Protobuf]
BuilderConsole -up-> [Builder]
BuilderConsole -up-> [HardwareLib]
BuilderConsole -up-> [VFrame30]

@enduml