@startuml

!include ./CommonLib.puml
!include ./UtilsLib.puml
!include ./Protobuf.puml
!include ./HardwareLib.puml
!include ./AppSignalLib.puml
!include ./OnlineLib.puml
!include ./DbLib.puml
'!include ./VFrame30.puml
'!include ./TuningService.puml
'!include ./Simulator.puml
'!include ./Metrology.puml

[Builder]
Builder -up-> CommonLib
Builder -up-> UtilsLib
Builder -up-> Protobuf
Builder -up-> HardwareLib
Builder -up-> AppSignalLib  
Builder -up-> OnlineLib
Builder -up-> DbLib
Builder -up-> [VFrame30]
Builder -up-> [TuningService]
Builder -up-> [Simulator]
Builder -up-> [Metrology]

@enduml