@startuml

!include ./CommonLib.puml
!include ./AppSignalLib.puml
!include ./Protobuf.puml
!include ./UtilsLib.puml
!include ./OnlineLib.puml
!include ./TrendView.puml

[ClientLib]
ClientLib -up-> [Protobuf]
ClientLib -up-> [CommonLib]
ClientLib -up-> [UtilsLib]
ClientLib -up-> [AppSignalLib]
ClientLib -up-> [OnlineLib]
ClientLib -up-> [TrendView]

@enduml