@startuml

!include ./CommonLib.puml
!include ./UtilsLib.puml
!include ./OnlineLib.puml
!include ./Protobuf.puml
!include ./ServiceLib.puml

[ConfigurationService]
ConfigurationService -up-> [CommonLib]
ConfigurationService -up-> [UtilsLib]
ConfigurationService -up-> [OnlineLib]
ConfigurationService -up-> [Protobuf]
ConfigurationService -up-> [ServiceLib]

@enduml