@startuml

!include ./OnlineLib.puml
!include ./ServiceLib.puml
!include ./AppSignalLib.puml
!include ./HardwareLib.puml

[DiagDataService]
DiagDataService -up-> [OnlineLib]
DiagDataService -up-> [ServiceLib]
DiagDataService -up-> [AppSignalLib]
DiagDataService -up-> [HardwareLib]

@enduml