@startuml

!include ./CommonLib.puml
!include ./Protobuf.puml
!include ./UtilsLib.puml
!include ./AppSignalLib.puml
!include ./HardwareLib.puml
!include ./OnlineLib.puml


[Metrology]
Metrology -up-> [CommonLib]
Metrology -up-> [Protobuf]  
Metrology -up-> [UtilsLib]
Metrology -up-> [AppSignalLib]
Metrology -up-> [HardwareLib]
Metrology -up-> [OnlineLib]

@enduml