@startuml

!include ./CommonLib.puml
!include ./UtilsLib.puml
!include ./OnlineLib.puml
!include ./Protobuf.puml
!include ./AppSignalLib.puml
!include ./TrendView.puml
!include ./VFrame30.puml
!include ./ClientLib.puml
!include ./HardwareLib.puml

[Monitor]
Monitor -up-> [CommonLib]
Monitor -up-> [UtilsLib]
Monitor -up-> [OnlineLib]
Monitor -up-> [Protobuf]
Monitor -up-> [AppSignalLib]
Monitor -up-> [ClientLib]
Monitor -up-> [TrendView]
Monitor -up-> [VFrame30]
Monitor -up-> [HardwareLib]

@enduml