@startuml

!include ./CommonLib.puml
!include ./UtilsLib.puml
!include ./Protobuf.puml
!include ./AppSignalLib.puml

[OnlineLib]
OnlineLib -up-> CommonLib
OnlineLib -up-> UtilsLib
OnlineLib -up-> AppSignalLib
OnlineLib -up-> Protobuf

@enduml