@startuml

!include ./CommonLib.puml
!include ./UtilsLib.puml
!include ./OnlineLib.puml
!include ./Protobuf.puml
!include ./ServiceLib.puml
!include ./AppSignalLib.puml
!include ./HardwareLib.puml
!include ./AppDataService.puml
!include ./ClientLib.puml

[ServiceControlManager]
ServiceControlManager -up-> [CommonLib]
ServiceControlManager -up-> [UtilsLib]
ServiceControlManager -up-> [OnlineLib]
ServiceControlManager -up-> [Protobuf]
ServiceControlManager -up-> [ServiceLib]
ServiceControlManager -up-> [AppSignalLib]
ServiceControlManager -up-> [HardwareLib]
ServiceControlManager -up-> [AppDataService]
ServiceControlManager -up-> [ClientLib]

@enduml