@startuml

!include ./CommonLib.puml
!include ./Protobuf.puml
!include ./UtilsLib.puml
!include ./OnlineLib.puml

[ServiceLib]
ServiceLib -up-> CommonLib
ServiceLib -up-> Protobuf
ServiceLib -up-> UtilsLib
ServiceLib -up-> OnlineLib

@enduml  