@startuml

!include ./CommonLib.puml
!include ./Protobuf.puml
!include ./UtilsLib.puml
!include ./AppSignalLib.puml
!include ./HardwareLib.puml
!include ./OnlineLib.puml
!include ./TrendView.puml

[Simulator]
Simulator -up-> [CommonLib]
Simulator -up-> [Protobuf]
Simulator -up-> [UtilsLib]
Simulator -up-> [AppSignalLib]
Simulator -up-> [HardwareLib]
Simulator -up-> [OnlineLib]
Simulator -up-> [TrendView]

@enduml