@startuml

!include ./Protobuf.puml
!include ./HardwareLib.puml
!include ./Simulator.puml

[SimulatorTests]
SimulatorTests -up-> [Protobuf]
SimulatorTests -up-> [HardwareLib]
SimulatorTests -up-> [Simulator]

@enduml