@startuml

!include ./CommonLib.puml
!include ./UtilsLib.puml
!include ./AppSignalLib.puml
!include ./OnlineLib.puml
!include ./VFrame30.puml
!include ./ClientLib.puml

[TuningClient]
TuningClient -up-> [CommonLib]
TuningClient -up-> [UtilsLib]
TuningClient -up-> [AppSignalLib]
TuningClient -up-> [OnlineLib]
TuningClient -up-> [ClientLib]
TuningClient -up-> [VFrame30]

@enduml