@startuml

!include ./CommonLib.puml
!include ./UtilsLib.puml
!include ./OnlineLib.puml
!include ./Protobuf.puml
!include ./ServiceLib.puml
!include ./AppSignalLib.puml
!include ./HardwareLib.puml

[TuningService]
TuningService -up-> [CommonLib]
TuningService -up-> [UtilsLib]
TuningService -up-> [OnlineLib]
TuningService -up-> [Protobuf]
TuningService -up-> [ServiceLib]
TuningService -up-> [AppSignalLib]
TuningService -up-> [HardwareLib]

@enduml