@startuml

!include ./CommonLib.puml
!include ./UtilsLib.puml
!include ./Protobuf.puml
!include ./AppSignalLib.puml
!include ./HardwareLib.puml
!include ./DbLib.puml
!include ./OnlineLib.puml

'!include ./TrendView.puml
'!include ./VFrame30.puml

'!include ./Metrology.puml
'!include ./Builder.puml
'!include ./Simulator.puml

[u7]
u7 -up-> [CommonLib]
u7 -up-> [Protobuf]
u7 -up-> [UtilsLib]
u7 -up-> [AppSignalLib]
u7 -up-> [HardwareLib]
u7 -up-> [DbLib]
u7 -up-> [TrendView]
u7 -up-> [VFrame30]
u7 -up-> [Metrology]
u7 -up-> [Builder]
u7 -up-> [Simulator]
u7 -up-> [OnlineLib]


@enduml