@startuml

!include ./CommonLib.puml
!include ./UtilsLib.puml
!include ./Protobuf.puml
!include ./TrendView.puml
!include ./AppSignalLib.puml
!include ./HardwareLib.puml

[VFrame30]
VFrame30 -up-> CommonLib
VFrame30 -up-> UtilsLib
VFrame30 -up-> Protobuf
VFrame30 -up-> TrendView  
VFrame30 -up-> AppSignalLib
VFrame30 -up-> HardwareLib

@enduml