@startuml VFrame30
!include ../../doc/uml/Namespace.puml

together {
	class VFrame30::BaseSchemaWidget #F0FFF0
	class VFrame30::QScrollArea #F0FFF0
}

class VFrame30::BaseSchemaWidget #F0FFF0 extends VFrame30::QScrollArea {
	SchemaViewWidget* : m_schemaView
}

<> BaseSchemaWidget_m_schemaView

VFrame30::BaseSchemaWidget *-- BaseSchemaWidget_m_schemaView
BaseSchemaWidget_m_schemaView *.. VFrame30::SchemaViewWidget

' connecteted to diamond
'VFrame30::SchemaViewWidget --* VFrame30::BaseSchemaWidget

@enduml