@startuml VFrame30
!include ../../doc/uml/Namespace.puml

!include ../../UtilsLib/uml/ILogFile.puml

class VFrame30::LogController #F0FFF0
{
	public QObject
	--
	-ILogFile* m_logFile
}

UtilsLib::ILogFile ..o VFrame30::LogController


@enduml
