@startuml VFrame30
!include ../../doc/uml/Namespace.puml

!include ../../TrendView/uml/ITrendDataProvider.puml

abstract class VFrame30::SchemaManager #F0FFF0 implements TrendLib::ITrendDataProvider
{
	public QObject
	--
	QString : m_globalScript
}

@enduml