@startuml VFrame30
!include ../../doc/uml/Namespace.puml

interface VFrame30::ISchemaItemPropertiesPos #F0FFF0
{
}

interface VFrame30::IPointList #F0FFF0
{
}

class VFrame30::SchemaItem #F0FFF0 implements VFrame30::ISchemaItemPropertiesPos, VFrame30::IPointList
{
	public PropertyObject
	--
}

'
'	IPosLine
'
interface VFrame30::IPosLine
{
}

class VFrame30::PosLineImpl extends VFrame30::SchemaItem implements VFrame30::IPosLine
{
}

'
'	IPosRect
'
class VFrame30::PosRectImpl extends VFrame30::SchemaItem implements VFrame30::IPosRect
{
}

'
'	FblItemLine
'
class VFrame30::FblItemLine extends VFrame30::PosConnectionImpl, VFrame30::FblItem
{
}

class VFrame30::PosConnectionImpl extends VFrame30::SchemaItem implements VFrame30::IPosConnection
{
}

'
'	FblItem
'
class VFrame30::AfbPin
{
}

class VFrame30::FblItem
{
	std::vector<VFrame30::AfbPin> : m_inputPoints
	std::vector<VFrame30::AfbPin> : m_outputPoints
}

VFrame30::AfbPin "*" --* VFrame30::FblItem : inputs
VFrame30::AfbPin "*" --* VFrame30::FblItem : outputs

class VFrame30::FblItemRect extends VFrame30::PosRectImpl, VFrame30::FblItem
{
}

class VFrame30::SchemaItemAfb extends VFrame30::FblItemRect
{
}

'
'	SchemaItemBus
'
class VFrame30::SchemaItemBus extends VFrame30::FblItemRect
{
}

class VFrame30::SchemaItemBusComposer extends VFrame30::SchemaItemBus
{
}

class VFrame30::SchemaItemBusExtractor extends VFrame30::SchemaItemBus
{
}

'
'	SchemaItemConnection
'
class VFrame30::SchemaItemConnection extends VFrame30::FblItemRect
{
}

class VFrame30::SchemaItemTransmitter extends VFrame30::SchemaItemConnection
{
}

class VFrame30::SchemaItemReceiver extends VFrame30::SchemaItemConnection
{
}

'
'	SchemaItemConst
'
class VFrame30::SchemaItemConst extends VFrame30::FblItemRect
{
}

'
'	SchemaItemControl
'
class VFrame30::SchemaItemControl extends VFrame30::PosRectImpl
{
	QString : m_styleSheet
	QString : m_toolTip
}

'
'	SchemaItemImage
'
class VFrame30::SchemaItemImage extends VFrame30::PosRectImpl
{
	ImageItem : m_image
}

'
'	SchemaItemImageValue
'
class VFrame30::SchemaItemImageValue extends VFrame30::PosRectImpl
{
	ImageItem : m_image
}

class VFrame30::ImageItem
{
}

VFrame30::ImageItem "*" --* "1" VFrame30::SchemaItemImageValue

'
'	SchemaItemIndicator
'
class VFrame30::SchemaItemIndicator extends VFrame30::PosRectImpl
{
	IndicatorObjectPtr : m_indicatorObjects
}

VFrame30::Indicator "1" --* "1" VFrame30::SchemaItemIndicator

class VFrame30::Indicator
{
}

class VFrame30::IndicatorArrowIndicator extends VFrame30::Indicator
{
}

class VFrame30::IndicatorHistogramVert extends VFrame30::Indicator
{
}

class VFrame30::IndicatorTrend extends VFrame30::Indicator
{
}

'
'	SchemaItemLine
'
class VFrame30::SchemaItemLine extends VFrame30::PosLineImpl
{
}

'
'	SchemaItemLineEdit
'
class VFrame30::SchemaItemLineEdit extends VFrame30::SchemaItemControl
{
}

'
'	SchemaItemLink
'
class VFrame30::SchemaItemLink extends VFrame30::FblItemLine
{
}

'
'	SchemaItemLoopback
'
class VFrame30::SchemaItemLoopback extends VFrame30::FblItemRect
{
}

class VFrame30::SchemaItemLoopbackSource extends VFrame30::SchemaItemLoopback
{
}

class VFrame30::SchemaItemLoopbackTarget extends VFrame30::SchemaItemLoopback
{
}

together {
	class VFrame30::SchemaItemLoopback
	class VFrame30::SchemaItemLoopbackSource
	class VFrame30::SchemaItemLoopbackTarget
}

'
'	SchemaItemPath
'
class VFrame30::SchemaItemPath extends VFrame30::PosConnectionImpl
{
}

'
'	SchemaItemPushButton
'
class VFrame30::SchemaItemPushButton extends VFrame30::SchemaItemControl
{
}

'
'	SchemaItemRect
'
class VFrame30::SchemaItemRect extends VFrame30::PosRectImpl
{
}

'
'	SchemaItemSignal
'
class VFrame30::SchemaItemSignal extends VFrame30::FblItemRect
{
}

class VFrame30::SchemaItemInput extends VFrame30::SchemaItemSignal
{
}

class VFrame30::SchemaItemOutput extends VFrame30::SchemaItemSignal
{
}

class VFrame30::SchemaItemInOut extends VFrame30::SchemaItemSignal
{
}

together {
	class VFrame30::SchemaItemSignal
	class VFrame30::SchemaItemInput
	class VFrame30::SchemaItemOutput
	class VFrame30::SchemaItemInOut
}

'
'	SchemaItemTerminator
'
class VFrame30::SchemaItemTerminator extends VFrame30::FblItemRect
{
}

'
'	SchemaItemUfb
'
class VFrame30::SchemaItemUfb extends VFrame30::FblItemRect
{
	QString : m_ufbSchemaId
}

'
'	SchemaItemValue
'
class VFrame30::SchemaItemValue extends VFrame30::PosRectImpl
{
	QStringList : m_signalIds
}


'
'
'
together {
	class VFrame30::SchemaItemControl
	class VFrame30::SchemaItemLineEdit
	class VFrame30::SchemaItemPushButton
}

@enduml