@startuml VFrame30
!include ../../doc/uml/Namespace.puml

class VFrame30::ScriptSchema #F0FFF0
{
	public QObject
	--
	std::shared_ptr<Schema> : m_schema
}

VFrame30::Schema ..o VFrame30::ScriptSchema

'
'  class Schema
'
class VFrame30::Schema #F0FFF0
{
	public PropertyObject
	--
	SchemaUnit : m_unit	

	std::vector<SchemaLayerPtr> : m_layers
}

VFrame30::SchemaLayer "*" ..* "1" VFrame30::Schema


' LogicSchema
class VFrame30::LogicSchema #F0FFF0 extends VFrame30::Schema
{
}


' UfbSchema
class VFrame30::UfbSchema #F0FFF0 extends VFrame30::Schema
{
}


' MonitorSchema
class VFrame30::MonitorSchema #F0FFF0 extends VFrame30::Schema
{
}


' TuningSchema
class VFrame30::TuningSchema #F0FFF0 extends VFrame30::Schema
{
}

together {
	class VFrame30::Schema #F0FFF0
	class VFrame30::ScriptSchema #F0FFF0
}

together {
	class VFrame30::LogicSchema #F0FFF0
	class VFrame30::UfbSchema #F0FFF0
	class VFrame30::MonitorSchema #F0FFF0
	class VFrame30::TuningSchema #F0FFF0
}

@enduml