@startuml VFrame30
!include ../../doc/uml/Namespace.puml

interface VFrame30::ISchemaItemPropertiesPos #F0FFF0
{
}

interface VFrame30::IPointList #F0FFF0
{
}

class VFrame30::SchemaItem #F0FFF0 implements VFrame30::ISchemaItemPropertiesPos, VFrame30::IPointList
{
	public PropertyObject
	--
}

@enduml