@startuml VFrame30
!include ../../doc/uml/Namespace.puml

!include ../../lib/Tuning/uml/ITuningSignalManager.puml
!include ../../lib/Tuning/uml/ITuningTcpClient.puml


class VFrame30::TuningController #F0FFF0
{
	public QObject
	--
	ITuningSignalManager* m_signalManager = nullptr;
	std::vector<ITuningTcpClient*> m_tcpClients;
}

TuningLib::ITuningSignalManager -[#green]-o VFrame30::TuningController
TuningLib::ITuningTcpClient "*" --* "1" VFrame30::TuningController

@enduml