syntax = "proto2";

package Network;

import "AppSignal.proto";
import "BuildInfo.proto";

// Get signal list
// 1. Request GetSignalListStartRequest, wait for reply GetSignalListStartReply
// 2. Request GetSignalListStartReply.partCount times GetSignalListNextRequest (and get GetSignalListNextReply in reply)
//
message GetSignalListStartRequest
{
}

message GetSignalListStartReply
{
	optional int32 error = 1 [default = 0];
	optional int32 totalItemCount = 2;
	optional int32 partCount = 3;
	optional int32 itemsPerPart = 4;
}

message GetSignalListNextRequest
{
	optional int32 part = 1;
}

message GetSignalListNextReply
{
	optional int32 error = 1 [default = 0];
	optional int32 part = 2;
	repeated string appSignalIds = 3;
}

// Geetting class AppSignalParam
//
message GetAppSignalParamRequest
{
	repeated uint64 signalHashes = 1;						// Limited to ADS_GET_APP_SIGNAL_PARAM_MAX (500)
}

message GetAppSignalParamReply
{
	optional int32 error = 1 [default = 0];
	repeated Proto.AppSignal appSignals = 2;				// Limited to ADS_GET_APP_SIGNAL_PARAM_MAX (500)
}

// Get class Signal
//
message GetAppSignalRequest
{
    repeated uint64 signalHashes = 1;						// Limited to ADS_GET_APP_SIGNAL_PARAM_MAX (500)
}

message GetAppSignalReply
{
    optional int32 error = 1 [default = 0];
	repeated Proto.AppSignal appSignals = 2;					// Limited to ADS_GET_APP_SIGNAL_PARAM_MAX (500)
}

// Geetting application signal states
//
message GetAppSignalStateRequest
{
	repeated uint64 signalHashes = 1;						// Limited to ADS_GET_APP_SIGNAL_STATE_MAX (2000)
}

message GetAppSignalStateReply
{
	optional int32 error = 1 [default = 0];

	optional int64 serverTimeUtc = 2 [default = 0];
	optional int64 serverTimeLocal = 3 [default = 0];

	optional int32 stateChangesQueueSize = 4  [default = 0];
	optional int32 gatewayStateChangesQueueSize = 5  [default = 0];

	repeated Proto.AppSignalState appSignalStates = 6;		// Limited to ADS_GET_APP_SIGNAL_STATE_MAX (2000)
}

// Getting application signal states changes
//
message GetAppSignalStateChangesRequest
{
}

message GetAppSignalStateChangesReply
{
	optional int32 error = 1 [default = 0];

	optional int64 serverTimeUtc = 2;
	optional int64 serverTimeLocal = 3;

	optional int32 pendingStatesCount = 4 [default = 0];

	repeated Proto.AppSignalState appSignalStates = 5;		// Limited to ADS_GET_APP_SIGNAL_STATE_MAX (2000)
}

// Getting application signal states changes for GatewayService
//
message GatewayGetAppSignalStateChangesRequest
{
	repeated uint64 signalsHashes = 1;
}

message GatewayAppSignalState
{
	required Proto.AppSignalState prevState = 1;
	required Proto.AppSignalState curState = 2;
}

message GatewayGetAppSignalStateChangesReply
{
	optional int32 error = 1 [default = 0];
	optional int32 pendingStatesCount = 2 [default = 0];

	repeated GatewayAppSignalState appSignalStates = 3;		// Limited to ADS_GET_APP_SIGNAL_STATE_MAX (2000)
}

//

message LanControllerInfo
{
	optional string equipmentID = 1;
	optional int32 controllerNo = 2 [default = -1];
	optional int32 lanControllerType = 3 [default = 0];		// E::LanControllerType values

	// tuning parameters

	optional bool tuningEnable = 10 [default = false];
	optional string tuningIP = 11;
	optional int32 tuningPort = 12 [default = 0];
	optional string tuningServiceID = 13;
	optional string tuningServiceIP = 14;
	optional int32 tuningServicePort = 15 [default = 0];
	optional string tuningServiceNetmask = 16;
	optional uint32 rupTuningDataUID = 17  [default = 0];
	optional uint64 fotipTuningDataUID = 18  [default = 0];

	// app data parameters

	optional bool appDataEnable = 20 [default = false];
	optional string appDataIP = 21;
	optional int32 appDataPort = 22 [default = 0];
	optional string appDataServiceID = 23;
	optional string appDataServiceIP = 24;
	optional int32 appDataServicePort = 25 [default = 0];
	optional string appDataServiceNetmask = 26;
	optional uint32 rupAppDataUID = 27 [default = 0];
	optional int32 appDataSizeBytes = 28 [default = 0];
	optional int32 appDataFramesQuantity = 29 [default = 0];
	optional int32 overrideAppDataWordCount = 30 [default = -1];

	// diag data parameters

	optional bool diagDataEnable = 40 [default = false];
	optional string diagDataIP = 41;
	optional int32 diagDataPort = 42 [default = 0];
	optional string diagDataServiceID = 43;
	optional string diagDataServiceIP = 44;
	optional int32 diagDataServicePort = 45 [default = 0];
	optional string diagDataServiceNetmask = 46;
	optional uint32 rupDiagDataUID = 47 [default = 0];
	optional int32 diagDataSizeBytes = 48 [default = 0];
	optional int32 diagDataFramesQuantity = 49 [default = 0];
	optional int32 overrideDiagDataWordCount = 50 [default = -1];
}

// Getting Data Sources info
//

message DataSourceInfo
{
    optional uint64 id = 1 [default = 0];		    // unique id

	optional string moduleEquipmentID = 2;
	optional string modulePresetName = 3;
	optional int32 moduleType = 4 [default = 0];
	optional string moduleCaption = 5;
	optional uint64 moduleUniqueID = 6;

	optional string subsystemID = 7;
	optional int32 subsystemKey = 8 [default = 0];
	optional int32 lmNumber = 9 [default = 0];
	optional string subsystemChannel = 10;

	repeated LanControllerInfo lanControllerInfo = 11;

	optional string profile = 12;
	optional int32 acquiredSignalsCount = 13 [default = 0];
	optional uint32 expectedDataUID = 14 [default = 0];
	optional int32 workcycle_mcs = 15 [default = 0];
}

message GetDataSourcesInfoRequest
{
}

message GetDataSourcesInfoReply
{
    optional int32 error = 1 [default = 0];
    repeated DataSourceInfo dataSourceInfo = 2;
}

message AppDataReceiveState
{
	optional int32 receivingSpeed = 1 [default = 0];
	optional int32 rupFramesReceivingSpeed = 3 [default = 0];

    optional int64 rupFramesCount = 4 [default = 0];
	optional int64 simFramesCount = 5 [default = 0];

    optional int64 errDatagramSize = 6 [default = 0];
	optional int64 errSimVersion = 7 [default = 0];
	optional int64 errUnknownAppDataSourceIP = 8 [default = 0];
	optional int64 errRupFrameCRC = 9 [default = 0];

	optional int64 errNotExpectedSimPacket = 10 [default = 0];
}

// Getting Application Data Sources states
//
message AppDataSourceState
{
	optional uint64 id = 1 [default = 0];				// unique id
	optional string lmEquipmentID = 2;

	optional bool dataProcessingEnabled = 3 [default = false];
	optional bool receivesData = 4 [default = false];
	optional int64 uptime = 5 [default = 0];					// time from start of data receiving
	optional uint32 receivedDataID = 6 [default = 0];
	optional int64 lmTime = 7 [default = 0];
	optional uint32 rupFrameNumerator = 8 [default = 0];

	optional double dataReceivingSpeed = 9 [default = 0];	    // bytes/sec
	optional int64 receivedDataSize = 10 [default = 0];
	optional int64 receivedFramesCount = 11 [default = 0];
	optional int64 receivedPacketCount = 12 [default = 0];
	optional int64 lostPacketCount = 13 [default = 0];
	optional int32 signalStatesQueueCurSize = 14 [default = 0];
	optional int32 signalStatesQueueCurMaxSize = 15 [default = 0];

	optional int64 errorProtocolVersion = 16 [default = 0];
	optional int64 errorFramesQuantity = 17 [default = 0];
	optional int64 errorFrameNo = 18 [default = 0];
	optional int64 errorFrameCRC = 19 [default = 0];
	optional int64 errorDataID = 20 [default = 0];
	optional int64 errorDuplicatePlantTime = 21 [default = 0];
	optional int64 errorNonmonotonicPlantTime = 22 [default = 0];
	optional int64 errorPlantTimeFormat = 23 [default = 0];

	optional string lanControllerID = 24;
	optional uint32 lanControllerIP = 25;
	optional uint32 lanControllerPort = 26;
}

// Getting Diagnostic Data Sources states
//
message DiagDataSourceState
{
	optional uint64 id = 1 [default = 0];				// unique id
	optional string lmEquipmentID = 2;

	optional bool dataProcessingEnabled = 3 [default = false];
	optional bool receivesData = 4 [default = false];
	optional int64 uptime = 5 [default = 0];					// time from start of data receiving
	optional uint32 receivedDataID = 6 [default = 0];
	optional int64 lmTime = 7 [default = 0];
	optional uint32 rupFrameNumerator = 8 [default = 0];

	optional double dataReceivingSpeed = 9 [default = 0];	    // bytes/sec
	optional int64 receivedDataSize = 10 [default = 0];
	optional int64 receivedFramesCount = 11 [default = 0];
	optional int64 receivedPacketCount = 12 [default = 0];
	optional int64 lostPacketCount = 13 [default = 0];
	optional int32 signalStatesQueueCurSize = 14 [default = 0];
	optional int32 signalStatesQueueCurMaxSize = 15 [default = 0];

	optional int64 errorProtocolVersion = 16 [default = 0];
	optional int64 errorFramesQuantity = 17 [default = 0];
	optional int64 errorFrameNo = 18 [default = 0];
	optional int64 errorFrameCRC = 19 [default = 0];
	optional int64 errorDataID = 20 [default = 0];
	optional int64 errorDuplicatePlantTime = 21 [default = 0];
	optional int64 errorNonmonotonicPlantTime = 22 [default = 0];
	optional int64 errorPlantTimeFormat = 23 [default = 0];
}

message GetAppDataSourcesStatesReply
{
    optional int32 error = 1 [default = 0];
    repeated AppDataSourceState appDataSourcesStates = 2;
}

message AppDataServiceState
{
    required bool CfgServiceIsConnected = 1 [default = false];
    optional uint32 CfgServiceIp = 2 [default = 0];
    optional int32 CfgServicePort = 3 [default = 0];

    required bool ArchiveServiceIsConnected = 4 [default = false];
    optional uint32 ArchiveServiceIp = 5 [default = 0];
    optional int32 ArchiveServicePort = 6 [default = 0];

    optional AppDataReceiveState appDataReceiveState = 7;
}

message SoftwareInfo
{
    required int32 softwareType = 1 [default = 8000];		// E::SoftwareType::Unknown = 8000
    required string equipmentId = 2;

    required int32 majorVersion = 3 [default = 0];
    required int32 minorVersion = 4 [default = 0];
	required int32 patchVersion = 5 [default = 0];

	required string releaseType = 6;

	optional string branchName = 7;
	optional string commitHash = 8;
	optional string buildUserName = 9;
	optional string buildDate = 10;
	optional string buildHostname = 11;
	optional int32 pipelineID = 12 [default = 0];

	optional string hostname = 13;
	optional string osUsername = 14;
}

message SecurityLevelReply
{
	required int32 connectionNo = 1;
	required int32 securityLevel = 2 [default = 0];			// E::securityLevel::Base
}

message IntroduceMyselfRequest
{
	required SoftwareInfo clientSoftwareInfo = 1;
}

message IntroduceMyselfReply
{
	required SoftwareInfo serverSoftwareInfo = 1;

	required int32 setConnectionResult = 2;					// Tcp::SetConnectionResult values
	optional string errorMsg = 3;
}

// Get Service Info
//
message SessionParams
{
	optional string currentSettingsProfile = 1;
	optional int32 softwareRunMode = 2 [default = 0 /* E::SoftwareRunMode::Normal */];	// enum E::SoftwareRunMode values
}

message ArchSignalInfo
{
	required string appSignalID = 1;
	required int32 apertureType = 2;
	required double fineAperture = 3;
	required double coarseAperture = 4;
	required double absFineAperture = 5;
	required double absCoarseAperture = 6;
	required bool apertureOverrided = 7;
	required int32 recordsPerMin = 8;
	required double highEngineeringUnits = 9;
	required double lowEngineeringUnits = 10;
}

message ApertureRecord
{
	required string signalID = 1;
	required int32 apertureType = 2;
	required double coarseAperture = 3;
	required double fineAperture = 4;
}

message ServiceClientInfo
{
	required int32 requestIP = 1;
	required int32 requestPort = 2;
	required int32 clientIP = 3;
	required int32 clientPort = 4;
	required int64 uptime = 5;
	required bool isActual = 6;
	required int64 replyQuantity = 7;
	required SoftwareInfo softwareInfo = 8;
}

message ServiceInfo
{
    required SoftwareInfo softwareInfo = 1;

    optional int64 uptime = 2 [default = 0];
    optional int32 serviceState = 3 [default = 0];		// ServiceState::Undefined;
	optional int64 serviceRuntime = 4 [default = 0];

	optional SessionParams sessionParams = 5;

	optional string settingsXml = 6;					// current service settings XML

	optional Proto.BuildInfo buildInfo = 7;

	repeated ServiceClientInfo clients = 8;

	// CfgService specific
	//
	optional string autoloadBuildPath = 20;
	optional string workDirectory = 21;
	optional int32 cfgCheckerState = 22;

	// Common service settings
	//
	optional uint32 cfgServiceIP1 = 30;
	optional uint32 cfgServicePort1 = 31;

	optional uint32 cfgServiceIP2 = 32;
	optional uint32 cfgServicePort2 = 33;

	// AppDataService specific
	//
	repeated AppDataSourceState appDataSourcesStates = 40;

	optional double archSignalsUpdateProgress = 50 [default = 0];
	repeated ArchSignalInfo archSignalsInfo = 51;
}

message GetServiceInfoRequest
{
	repeated ApertureRecord apertureRecords = 1;
}

message ConfigurationServiceState
{
    required string currentBuildDirectory = 1;
    required int32 checkBuildAttemptQuantity = 2;
    required int32 buildCheckerState = 3;
}

message ConfigurationServiceSettings
{
    required string equipmentID = 1;
    required string autoloadBuildPath = 2;
    required string workDirectory = 3;
}

message ServiceSettings
{
    required string equipmentID = 1;
    required string configIP1 = 2;
    required string configIP2 = 3;
}


// TuningService requests and replies
//

// Tuning sources info request - TDS_GET_TUNING_SOURCES_INFO
//
message GetTuningSourcesInfo
{
}

message GetTuningSourcesInfoReply
{
    optional int32 error = 1 [default = 0];
    repeated DataSourceInfo tuningSourceInfo= 2;

    optional bool singleLmControlMode = 3 [default = true];
    optional string activeClientID = 4;				    // if singleLmControlMode == true then EquipmentID of activeClient
                                                                    // else - empty string
    optional string activeClientIP = 5;				    // similar to activeClientID
}

// Tuning sources states request - TDS_GET_TUNING_SOURCES_STATES
//
message GetTuningSourcesStates
{
}

message SignalsAssociatedToTuningSource
{
    required uint64 sourceID = 1;
    repeated uint64 signalHash = 2;
}

message TuningSourceFilling
{
    required uint64 signalCount = 1;
    repeated SignalsAssociatedToTuningSource signalsPerSource = 2;
}

message TuningSourceState
{
	// Tuning Source channel identification
	//
    optional uint64 sourceID = 1 [default = 0];
	optional string lanEquipmentID = 2;

	// Tuning Source processing states
	//
	optional bool isReply = 10 [default = false];
	optional int64 requestCount = 11 [default = 0];
	optional int64 replyCount = 12 [default = 0];
	optional int32 commandQueueSize = 13 [default = 0];
	optional bool controlIsActive = 14 [default = false];
	optional bool setSOR = 15 [default = false];
	optional bool writingDisabled = 16 [default = false];
	optional bool hasUnappliedParams = 17 [default = false];

	// flags reported by LM in reply FotipHeader.flags
	//
	optional int64 fotipFlagBoundsCheckSuccess = 30 [default = 0];
	optional int64 fotipFlagWriteSuccess = 31 [default = 0];
	optional int64 fotipFlagDataTypeErr = 32 [default = 0];
	optional int64 fotipFlagOpCodeErr = 33 [default = 0];
	optional int64 fotipFlagStartAddrErr = 34 [default = 0];
	optional int64 fotipFlagRomSizeErr = 35 [default = 0];
	optional int64 fotipFlagRomFrameSizeErr = 36 [default = 0];
	optional int64 fotipFlagFrameSizeErr = 37 [default = 0];
	optional int64 fotipFlagProtocolVersionErr = 38 [default = 0];
	optional int64 fotipFlagSubsystemKeyErr = 39 [default = 0];
	optional int64 fotipFlagUniueIDErr = 40 [default = 0];
	optional int64 fotipFlagOffsetErr = 41 [default = 0];
	optional int64 fotipFlagApplySuccess = 42 [default = 0];
	optional int64 fotipFlagSetSOR = 43 [default = 0];
	optional int64 fotipFlagWritingDisabled = 44 [default = 0];
	optional uint64 fotipProcessingNumerator = 45 [default = 0];

    // errors in reply RupFrameHeader
    //
	optional int64 errRupProtocolVersion = 50 [default = 0];
	optional int64 errRupFrameSize = 51 [default = 0];
	optional int64 errRupNonTuningData = 52 [default = 0];
	optional int64 errRupModuleType = 53 [default = 0];
	optional int64 errRupFramesQuantity = 54 [default = 0];
	optional int64 errRupFrameNumber = 55 [default = 0];
	optional int64 errRupCRC = 56 [default = 0];

    // errors in reply FotipHeader
    //
	optional int64 errFotipProtocolVersion = 60 [default = 0];
	optional int64 errFotipUniqueID = 61 [default = 0];
	optional int64 errFotipLmNumber = 62 [default = 0];
	optional int64 errFotipSubsystemCode = 63 [default = 0];
	optional int64 errFotipOperationCode = 64 [default = 0];
	optional int64 errFotipFrameSize = 65 [default = 0];
	optional int64 errFotipRomSize = 66 [default = 0];
	optional int64 errFotipRomFrameSize = 67 [default = 0];
	optional int64 errAnalogLowBoundCheck = 68 [default = 0];
	optional int64 errAnalogHighBoundCheck = 69 [default = 0];

	// Tuning Source processing errors
	//
	optional int64 errUntimelyReplay = 70 [default = 0];
	optional int64 errSent = 71 [default = 0];
	optional int64 errPartialSent = 72 [default = 0];
	optional int64 errReplySize = 73 [default = 0];
	optional int64 errNoReply = 74 [default = 0];
	optional int64 errTuningFrameUpdate = 75 [default = 0];

	optional int64 lmTime = 76 [ default = 0];
}

message GetTuningSourcesStatesReply
{
    optional int32 error = 1 [default = 0];
    repeated TuningSourceState tuningSourcesState = 2;

    optional bool singleLmControlMode = 3 [default = true];
    optional string activeClientID = 4;				    // if singleLmControlMode == true then EquipmentID of activeClient
														// else - empty string
    optional string activeClientIP = 5;				    // similar to activeClientID
}

//  Change current controlled TuningSource request - TDS_CHANGE_CONTROLLED_TUNING_SOURCE
//
//  Allowed only if SingleLMControl mode of TuningService is set to TRUE.
//  Otherwise reply is returning error NetworkError::SingleLmControlDisabled.
//
message ChangeConrolledTuningSourceRequest
{
    optional bool takeControl = 1;				    // true - to force control to current client

    optional string tuningSourceEquipmentID = 2;		    // not empty - to change controlled source
                                                                    // empty - to request current controlled source (activateControl field is ignored)

    optional bool activateControl = 3 [default = false];	    // if tuningSourceEquipmentID is not empty:
																//	    true - to activate tuning source control
																//	    false - to deactivate tuning source control
}

message ChangeConrolledTuningSourceReply
{
    optional int32 error = 1 [default = 0];
    optional string controlledTuningSourceEquipmentID = 2;	    // if error == Success - current controlled TuningSource
                                                                    // else - empty string
    optional bool controlIsActive = 3 [default = false];
}

// Tuning signals read request - TDS_TUNING_SIGNALS_READ
//
message TuningSignalsRead
{
    repeated uint64 signalHash = 2;
}

message TuningSignalState
{
    optional fixed64 signalHash = 1 [default = 0];
    optional int32 error = 2 [default = 0];

    optional bool valid = 3 [default = false];
    optional Proto.TuningValue value = 4;
    optional Proto.TuningValue readLowBound = 5;
    optional Proto.TuningValue readHighBound = 6;

    optional bool writeInProgress = 7 [default = false];
    optional int32 writeErrorCode = 8 [default = 0];			// NetworkError:  Success, TuningValueOutOfRange, TuningNoReply
	optional fixed64 writeClient = 9 [default = 0];				// Hash code of Client's EquipmentID

    optional sfixed64 successfulReadTime = 10 [default = 0];	// time of last succesfull signal reading (UTC)
    optional sfixed64 writeRequestTime = 11 [default = 0];		// time of last write request (UTC)
	optional sfixed64 successfulWriteTime = 12 [default = 0];	// time of last succesfull signal writing (UTC)
	optional sfixed64 unsuccessfulWriteTime = 13 [default = 0];	// time of last unsuccesfull signal writing (UTC)

	optional bool setSOR = 14 [default = false];
	optional bool writingDisabled = 15 [default = false];

	optional bool tuningDefault = 16 [default = false];			// flag, sets to 1 if current tunable signal value is equal to tuning default value,

	optional sfixed64 lmTime = 17 [default = 0];
	optional fixed64 fotipProcessingNumerator = 18 [default = 0];
}

message TuningSignalsReadReply
{
    optional int32 error = 1 [default = 0];
    repeated TuningSignalState tuningSignalState = 2;
	optional int32 pendingSignalsStateChanges = 3 [default = 0];
}

// Get tuning signals state changes request - TDS_GET_SIGNALS_STATE_CHANGES
//
message GetTuningSignalsStateChangesRequest
{
}

message GetTuningSignalsStateChangesReply
{
	optional int32 error = 1 [default = 0];
	repeated TuningSignalState tuningSignalState = 2;
	optional int32 pendingSignalsStateChanges = 3 [default = 0];
}

// Write tuning signals request - TDS_TUNING_SIGNALS_WRITE
//
message TuningWriteCommand
{
    optional uint64 signalHash = 1 [default = 0];
    optional Proto.TuningValue value = 2;
}

message TuningSignalsWrite
{
	optional string matsUser = 1;
    optional bool autoApply = 2 [default = false];
    repeated TuningWriteCommand commands = 3;
}

message TuningSignalWriteResult
{
    optional uint64 signalHash = 1 [default = 0];
    optional int32 error = 2 [default = 0];
}

message TuningSignalsWriteReply
{
    optional int32 error = 1 [default = 0];
    repeated TuningSignalWriteResult writeResult = 2;
}

// Request to applying tuning signals values - TDS_TUNING_SIGNALS_APPLY
//
message TuningSignalsApply
{
}

message TuningSignalsApplyReply
{
    optional int32 error = 1 [default = 0];
}

// Request to change PacketSource(Console) data source state - TDS_DATA_SOURCE_WTITE
//
message DataSourceWrite
{
    optional string sourceEquipmentID = 1;			// EquipmentID of data source
	optional bool state = 2 [default = false];		// state of data source: run (true) or stop (false)
}

message DataSourceWriteReply
{
    optional int32 error = 1 [default = 0];
}

// Request to close application PacketSourceConsole  - TDS_PS_EXIT
//
message PacketSourceExit
{
}

message PacketSourceExitReply
{
    optional int32 error = 1 [default = 0];
}

// ArchService requests and replies
//

message SaveAppSignalsStatesToArchiveRequest
{
    optional string clientEquipmentID = 1;
    repeated Proto.AppSignalState appSignalStates = 2;
}

message SaveAppSignalsStatesToArchiveReply
{
    optional int32 error = 1 [default = 0];

    optional int32 archError = 2 [default = 100];
}

//

message GetAppSignalStatesFromArchiveStartRequest
{
    optional string clientEquipmentID = 1;
	optional int32 timeType = 2 [default = 1];		// enum TimeType values:
	                                                // 0 - plant time
													// 1 - system time
													// 2 - local time
													// 3 - archive id
    optional sfixed64 startTime = 3 [default = 0];
    optional sfixed64 endTime = 4 [default = 0];

    repeated uint64 signalHashes = 5;				// max hashes count should be less or equal to 32 (ARCH_REQUEST_MAX_SIGNALS at SocketIO.h)

    optional bool removePeriodic = 6 [default = true];
}

message GetAppSignalStatesFromArchiveStartReply
{
    optional int32 error = 1 [default = 0];
    optional int32 archError = 2 [default = 100];
	optional string errorString = 4;
    optional uint32 requestID = 3 [default = 0];
}

//

message GetAppSignalStatesFromArchiveNextRequest
{
    optional uint32 requestID = 1 [default = 0];
}

message GetAppSignalStatesFromArchiveNextReply
{
    optional int32 error = 1 [default = 0];
    optional int32 archError = 2 [default = 100];
    optional uint32 requestID = 3 [default = 0];
	optional string errorString = 10;
    optional bool dataReady = 4 [default = false];
    optional int32 totalStatesCount = 5 [default = 0];		// The actual number of transmitted states can be less than totalStatesCount
    optional int32 sentStatesCount = 6 [default = 0];
    optional int32 statesInPartCount = 7 [default = 0];
    optional bool isLastPart = 8 [default = false];
    repeated Proto.AppSignalState appSignalStates = 9;
}

//

message GetAppSignalStatesFromArchiveCancelRequest
{
    optional uint32 requestID = 1 [default = 0];
}

message GetAppSignalStatesFromArchiveCancelReply
{
    optional int32 error = 1 [default = 0];
    optional int32 archError = 2 [default = 100];
	optional string errorString = 3;
}

// Real-time trends requests and replies
//

message RtTrendsManagementRequest
{
    optional string clientEquipmentID = 1;
    optional int32 samplePeriod = 2;			    // enum E::RtTrandSamplePeriod
    repeated uint64 appendSignalHashes = 3;
    repeated uint64 deleteSignalHashes = 4;
}

message RtTrendsManagementReply
{
    optional int32 error = 1 [default = 0];
    optional string errorString = 2;
	optional int32 samplePeriod = 3;			    // enum E::RtTrandSamplePeriod
	repeated uint64 trackedSignalHashes = 4;
}

//

message RtTrendsGetStateChangesRequest
{
}

message RtTrendsGetStateChangesReply
{
    optional int32 error = 1 [default = 0];
    optional string errorString = 2;

    repeated Proto.AppSignalState signalStates = 3;
}

//

message GetFileReply
{
	required int32 errorCode = 1 [default = 0 /* FileTransferResult::Ok */];	// enum FileTransferResult values
	optional int64 fileSize = 2 [default = 0];
	optional int32 totalParts = 3 [default = 0];
	optional int32 currentPart = 4 [default = 0];			// valid values begins from 1
	optional int32 currentPartSize = 5 [default = 0];
	optional bytes md5 = 6;
	optional bytes filePartData = 10;
}

//

message AcquiredDiagObject
{
	required string equipmentID = 1;
	required int32 deviceType = 2 [default = 0];			// enum Hardware::DeviceType value
	required uint64 parentHash = 3 [default = 0];			// calcHash(parent.equipmentID)
}

message AcquiredDiagSignal
{
	required uint64 equipmentIdHash = 1  [default = 0];
	required uint64 parentHash = 2 [default = 0];			// calcHash(parent.equipmentID)
	required int32 diagLevel = 3 [default = 0];				// enum E::DiagLevel value
	required uint64 diagSignalTypeIdHash = 4 [default = 0];

	optional bool isReflection = 5 [default = false];
	optional uint64 reflectedSignalIdHash = 6  [default = 0];
	optional uint64 validitySignalIdHash = 7  [default = 0];
	optional int32 valueSizeBit = 8 [default = 0];
	optional int32 discreteContainerSize = 9 [default = 0];
	optional bool logChanges = 10 [default = false];
	optional bool archive = 11 [default = false];
	optional bool reserved = 12 [default = false];
	optional int32 apertureType = 13 [default = 0];			// enum E::ApertureType value
	optional double coarseAperture = 14  [default = 0];
	optional double fineAperture = 15  [default = 0];
	optional int32 absAddrBit = 16 [default = 0];
}

message LmDiagSignals
{
	required string lmEquipmentID = 1;
	repeated AcquiredDiagSignal diagSignals = 2;
}

message AcquiredDiagSignalsAndObjects
{
	repeated LmDiagSignals lmDiagSignals = 1;
	repeated AcquiredDiagObject diagObjects = 2;
}
