#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable : 4100)
#pragma warning(disable : 4244)
#pragma warning(disable : 4125)
#pragma warning(disable : 4127)
#pragma warning(disable : 4267)
#pragma warning(disable : 4512)
#pragma warning(disable : 4996)
#pragma warning(disable : 6011)
#pragma warning(disable : 6326)
#pragma warning(disable : 6385)
#pragma warning(disable : 6387)
#endif
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AppSignalList.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_AppSignalList_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_AppSignalList_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Common.pb.h"
#include "Envelope.pb.h"
#include "AppSignal.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_AppSignalList_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_AppSignalList_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_AppSignalList_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_AppSignalList_2eproto_metadata_getter(int index);
namespace Proto {
class AppSignalList;
struct AppSignalListDefaultTypeInternal;
extern AppSignalListDefaultTypeInternal _AppSignalList_default_instance_;
class AppSignalListSignal;
struct AppSignalListSignalDefaultTypeInternal;
extern AppSignalListSignalDefaultTypeInternal _AppSignalListSignal_default_instance_;
}  // namespace Proto
PROTOBUF_NAMESPACE_OPEN
template<> ::Proto::AppSignalList* Arena::CreateMaybeMessage<::Proto::AppSignalList>(Arena*);
template<> ::Proto::AppSignalListSignal* Arena::CreateMaybeMessage<::Proto::AppSignalListSignal>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Proto {

// ===================================================================

class AppSignalListSignal PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.AppSignalListSignal) */ {
 public:
  inline AppSignalListSignal() : AppSignalListSignal(nullptr) {}
  virtual ~AppSignalListSignal();
  explicit constexpr AppSignalListSignal(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AppSignalListSignal(const AppSignalListSignal& from);
  AppSignalListSignal(AppSignalListSignal&& from) noexcept
    : AppSignalListSignal() {
    *this = ::std::move(from);
  }

  inline AppSignalListSignal& operator=(const AppSignalListSignal& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppSignalListSignal& operator=(AppSignalListSignal&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AppSignalListSignal& default_instance() {
    return *internal_default_instance();
  }
  static inline const AppSignalListSignal* internal_default_instance() {
    return reinterpret_cast<const AppSignalListSignal*>(
               &_AppSignalListSignal_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AppSignalListSignal& a, AppSignalListSignal& b) {
    a.Swap(&b);
  }
  inline void Swap(AppSignalListSignal* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppSignalListSignal* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AppSignalListSignal* New() const final {
    return CreateMaybeMessage<AppSignalListSignal>(nullptr);
  }

  AppSignalListSignal* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AppSignalListSignal>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AppSignalListSignal& from);
  void MergeFrom(const AppSignalListSignal& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppSignalListSignal* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.AppSignalListSignal";
  }
  protected:
  explicit AppSignalListSignal(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_AppSignalList_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAppSignalIdFieldNumber = 1,
    kValueFieldNumber = 3,
  };
  // optional string appSignalId = 1;
  bool has_appsignalid() const;
  private:
  bool _internal_has_appsignalid() const;
  public:
  void clear_appsignalid();
  const std::string& appsignalid() const;
  void set_appsignalid(const std::string& value);
  void set_appsignalid(std::string&& value);
  void set_appsignalid(const char* value);
  void set_appsignalid(const char* value, size_t size);
  std::string* mutable_appsignalid();
  std::string* release_appsignalid();
  void set_allocated_appsignalid(std::string* appsignalid);
  private:
  const std::string& _internal_appsignalid() const;
  void _internal_set_appsignalid(const std::string& value);
  std::string* _internal_mutable_appsignalid();
  public:

  // optional .Proto.TuningValue value = 3;
  bool has_value() const;
  private:
  bool _internal_has_value() const;
  public:
  void clear_value();
  const ::Proto::TuningValue& value() const;
  ::Proto::TuningValue* release_value();
  ::Proto::TuningValue* mutable_value();
  void set_allocated_value(::Proto::TuningValue* value);
  private:
  const ::Proto::TuningValue& _internal_value() const;
  ::Proto::TuningValue* _internal_mutable_value();
  public:
  void unsafe_arena_set_allocated_value(
      ::Proto::TuningValue* value);
  ::Proto::TuningValue* unsafe_arena_release_value();

  // @@protoc_insertion_point(class_scope:Proto.AppSignalListSignal)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr appsignalid_;
  ::Proto::TuningValue* value_;
  friend struct ::TableStruct_AppSignalList_2eproto;
};
// -------------------------------------------------------------------

class AppSignalList PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.AppSignalList) */ {
 public:
  inline AppSignalList() : AppSignalList(nullptr) {}
  virtual ~AppSignalList();
  explicit constexpr AppSignalList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AppSignalList(const AppSignalList& from);
  AppSignalList(AppSignalList&& from) noexcept
    : AppSignalList() {
    *this = ::std::move(from);
  }

  inline AppSignalList& operator=(const AppSignalList& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppSignalList& operator=(AppSignalList&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AppSignalList& default_instance() {
    return *internal_default_instance();
  }
  static inline const AppSignalList* internal_default_instance() {
    return reinterpret_cast<const AppSignalList*>(
               &_AppSignalList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AppSignalList& a, AppSignalList& b) {
    a.Swap(&b);
  }
  inline void Swap(AppSignalList* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppSignalList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AppSignalList* New() const final {
    return CreateMaybeMessage<AppSignalList>(nullptr);
  }

  AppSignalList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AppSignalList>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AppSignalList& from);
  void MergeFrom(const AppSignalList& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppSignalList* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.AppSignalList";
  }
  protected:
  explicit AppSignalList(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_AppSignalList_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kListSignalsFieldNumber = 10,
    kIdFieldNumber = 2,
    kCaptionFieldNumber = 3,
    kTagsFieldNumber = 5,
    kCustomAppSignalIDMasksFieldNumber = 6,
    kEquipmentIDMasksFieldNumber = 7,
    kAppSignalIDMasksFieldNumber = 8,
    kAppSignalTagsFieldNumber = 9,
    kUuidFieldNumber = 1,
    kSignalTypeFieldNumber = 4,
  };
  // repeated .Proto.AppSignalListSignal listSignals = 10;
  int listsignals_size() const;
  private:
  int _internal_listsignals_size() const;
  public:
  void clear_listsignals();
  ::Proto::AppSignalListSignal* mutable_listsignals(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::AppSignalListSignal >*
      mutable_listsignals();
  private:
  const ::Proto::AppSignalListSignal& _internal_listsignals(int index) const;
  ::Proto::AppSignalListSignal* _internal_add_listsignals();
  public:
  const ::Proto::AppSignalListSignal& listsignals(int index) const;
  ::Proto::AppSignalListSignal* add_listsignals();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::AppSignalListSignal >&
      listsignals() const;

  // optional string id = 2;
  bool has_id() const;
  private:
  bool _internal_has_id() const;
  public:
  void clear_id();
  const std::string& id() const;
  void set_id(const std::string& value);
  void set_id(std::string&& value);
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  std::string* mutable_id();
  std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // optional string caption = 3;
  bool has_caption() const;
  private:
  bool _internal_has_caption() const;
  public:
  void clear_caption();
  const std::string& caption() const;
  void set_caption(const std::string& value);
  void set_caption(std::string&& value);
  void set_caption(const char* value);
  void set_caption(const char* value, size_t size);
  std::string* mutable_caption();
  std::string* release_caption();
  void set_allocated_caption(std::string* caption);
  private:
  const std::string& _internal_caption() const;
  void _internal_set_caption(const std::string& value);
  std::string* _internal_mutable_caption();
  public:

  // optional string tags = 5;
  bool has_tags() const;
  private:
  bool _internal_has_tags() const;
  public:
  void clear_tags();
  const std::string& tags() const;
  void set_tags(const std::string& value);
  void set_tags(std::string&& value);
  void set_tags(const char* value);
  void set_tags(const char* value, size_t size);
  std::string* mutable_tags();
  std::string* release_tags();
  void set_allocated_tags(std::string* tags);
  private:
  const std::string& _internal_tags() const;
  void _internal_set_tags(const std::string& value);
  std::string* _internal_mutable_tags();
  public:

  // optional string customAppSignalIDMasks = 6;
  bool has_customappsignalidmasks() const;
  private:
  bool _internal_has_customappsignalidmasks() const;
  public:
  void clear_customappsignalidmasks();
  const std::string& customappsignalidmasks() const;
  void set_customappsignalidmasks(const std::string& value);
  void set_customappsignalidmasks(std::string&& value);
  void set_customappsignalidmasks(const char* value);
  void set_customappsignalidmasks(const char* value, size_t size);
  std::string* mutable_customappsignalidmasks();
  std::string* release_customappsignalidmasks();
  void set_allocated_customappsignalidmasks(std::string* customappsignalidmasks);
  private:
  const std::string& _internal_customappsignalidmasks() const;
  void _internal_set_customappsignalidmasks(const std::string& value);
  std::string* _internal_mutable_customappsignalidmasks();
  public:

  // optional string equipmentIDMasks = 7;
  bool has_equipmentidmasks() const;
  private:
  bool _internal_has_equipmentidmasks() const;
  public:
  void clear_equipmentidmasks();
  const std::string& equipmentidmasks() const;
  void set_equipmentidmasks(const std::string& value);
  void set_equipmentidmasks(std::string&& value);
  void set_equipmentidmasks(const char* value);
  void set_equipmentidmasks(const char* value, size_t size);
  std::string* mutable_equipmentidmasks();
  std::string* release_equipmentidmasks();
  void set_allocated_equipmentidmasks(std::string* equipmentidmasks);
  private:
  const std::string& _internal_equipmentidmasks() const;
  void _internal_set_equipmentidmasks(const std::string& value);
  std::string* _internal_mutable_equipmentidmasks();
  public:

  // optional string appSignalIDMasks = 8;
  bool has_appsignalidmasks() const;
  private:
  bool _internal_has_appsignalidmasks() const;
  public:
  void clear_appsignalidmasks();
  const std::string& appsignalidmasks() const;
  void set_appsignalidmasks(const std::string& value);
  void set_appsignalidmasks(std::string&& value);
  void set_appsignalidmasks(const char* value);
  void set_appsignalidmasks(const char* value, size_t size);
  std::string* mutable_appsignalidmasks();
  std::string* release_appsignalidmasks();
  void set_allocated_appsignalidmasks(std::string* appsignalidmasks);
  private:
  const std::string& _internal_appsignalidmasks() const;
  void _internal_set_appsignalidmasks(const std::string& value);
  std::string* _internal_mutable_appsignalidmasks();
  public:

  // optional string appSignalTags = 9;
  bool has_appsignaltags() const;
  private:
  bool _internal_has_appsignaltags() const;
  public:
  void clear_appsignaltags();
  const std::string& appsignaltags() const;
  void set_appsignaltags(const std::string& value);
  void set_appsignaltags(std::string&& value);
  void set_appsignaltags(const char* value);
  void set_appsignaltags(const char* value, size_t size);
  std::string* mutable_appsignaltags();
  std::string* release_appsignaltags();
  void set_allocated_appsignaltags(std::string* appsignaltags);
  private:
  const std::string& _internal_appsignaltags() const;
  void _internal_set_appsignaltags(const std::string& value);
  std::string* _internal_mutable_appsignaltags();
  public:

  // optional .Proto.Uuid uuid = 1;
  bool has_uuid() const;
  private:
  bool _internal_has_uuid() const;
  public:
  void clear_uuid();
  const ::Proto::Uuid& uuid() const;
  ::Proto::Uuid* release_uuid();
  ::Proto::Uuid* mutable_uuid();
  void set_allocated_uuid(::Proto::Uuid* uuid);
  private:
  const ::Proto::Uuid& _internal_uuid() const;
  ::Proto::Uuid* _internal_mutable_uuid();
  public:
  void unsafe_arena_set_allocated_uuid(
      ::Proto::Uuid* uuid);
  ::Proto::Uuid* unsafe_arena_release_uuid();

  // optional int32 signalType = 4;
  bool has_signaltype() const;
  private:
  bool _internal_has_signaltype() const;
  public:
  void clear_signaltype();
  ::PROTOBUF_NAMESPACE_ID::int32 signaltype() const;
  void set_signaltype(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_signaltype() const;
  void _internal_set_signaltype(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:Proto.AppSignalList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::AppSignalListSignal > listsignals_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr caption_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr tags_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr customappsignalidmasks_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr equipmentidmasks_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr appsignalidmasks_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr appsignaltags_;
  ::Proto::Uuid* uuid_;
  ::PROTOBUF_NAMESPACE_ID::int32 signaltype_;
  friend struct ::TableStruct_AppSignalList_2eproto;
};
// ===================================================================

static const int kAppSignalListFieldNumber = 220;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::Proto::Envelope,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::Proto::AppSignalList >, 11, false >
  appSignalList;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AppSignalListSignal

// optional string appSignalId = 1;
inline bool AppSignalListSignal::_internal_has_appsignalid() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool AppSignalListSignal::has_appsignalid() const {
  return _internal_has_appsignalid();
}
inline void AppSignalListSignal::clear_appsignalid() {
  appsignalid_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& AppSignalListSignal::appsignalid() const {
  // @@protoc_insertion_point(field_get:Proto.AppSignalListSignal.appSignalId)
  return _internal_appsignalid();
}
inline void AppSignalListSignal::set_appsignalid(const std::string& value) {
  _internal_set_appsignalid(value);
  // @@protoc_insertion_point(field_set:Proto.AppSignalListSignal.appSignalId)
}
inline std::string* AppSignalListSignal::mutable_appsignalid() {
  // @@protoc_insertion_point(field_mutable:Proto.AppSignalListSignal.appSignalId)
  return _internal_mutable_appsignalid();
}
inline const std::string& AppSignalListSignal::_internal_appsignalid() const {
  return appsignalid_.Get();
}
inline void AppSignalListSignal::_internal_set_appsignalid(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  appsignalid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppSignalListSignal::set_appsignalid(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  appsignalid_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:Proto.AppSignalListSignal.appSignalId)
}
inline void AppSignalListSignal::set_appsignalid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  appsignalid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:Proto.AppSignalListSignal.appSignalId)
}
inline void AppSignalListSignal::set_appsignalid(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  appsignalid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:Proto.AppSignalListSignal.appSignalId)
}
inline std::string* AppSignalListSignal::_internal_mutable_appsignalid() {
  _has_bits_[0] |= 0x00000001u;
  return appsignalid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppSignalListSignal::release_appsignalid() {
  // @@protoc_insertion_point(field_release:Proto.AppSignalListSignal.appSignalId)
  if (!_internal_has_appsignalid()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return appsignalid_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppSignalListSignal::set_allocated_appsignalid(std::string* appsignalid) {
  if (appsignalid != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  appsignalid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), appsignalid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:Proto.AppSignalListSignal.appSignalId)
}

// optional .Proto.TuningValue value = 3;
inline bool AppSignalListSignal::_internal_has_value() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || value_ != nullptr);
  return value;
}
inline bool AppSignalListSignal::has_value() const {
  return _internal_has_value();
}
inline const ::Proto::TuningValue& AppSignalListSignal::_internal_value() const {
  const ::Proto::TuningValue* p = value_;
  return p != nullptr ? *p : reinterpret_cast<const ::Proto::TuningValue&>(
      ::Proto::_TuningValue_default_instance_);
}
inline const ::Proto::TuningValue& AppSignalListSignal::value() const {
  // @@protoc_insertion_point(field_get:Proto.AppSignalListSignal.value)
  return _internal_value();
}
inline void AppSignalListSignal::unsafe_arena_set_allocated_value(
    ::Proto::TuningValue* value) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(value_);
  }
  value_ = value;
  if (value) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.AppSignalListSignal.value)
}
inline ::Proto::TuningValue* AppSignalListSignal::release_value() {
  _has_bits_[0] &= ~0x00000002u;
  ::Proto::TuningValue* temp = value_;
  value_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Proto::TuningValue* AppSignalListSignal::unsafe_arena_release_value() {
  // @@protoc_insertion_point(field_release:Proto.AppSignalListSignal.value)
  _has_bits_[0] &= ~0x00000002u;
  ::Proto::TuningValue* temp = value_;
  value_ = nullptr;
  return temp;
}
inline ::Proto::TuningValue* AppSignalListSignal::_internal_mutable_value() {
  _has_bits_[0] |= 0x00000002u;
  if (value_ == nullptr) {
    auto* p = CreateMaybeMessage<::Proto::TuningValue>(GetArena());
    value_ = p;
  }
  return value_;
}
inline ::Proto::TuningValue* AppSignalListSignal::mutable_value() {
  // @@protoc_insertion_point(field_mutable:Proto.AppSignalListSignal.value)
  return _internal_mutable_value();
}
inline void AppSignalListSignal::set_allocated_value(::Proto::TuningValue* value) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(value_);
  }
  if (value) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, value, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  value_ = value;
  // @@protoc_insertion_point(field_set_allocated:Proto.AppSignalListSignal.value)
}

// -------------------------------------------------------------------

// AppSignalList

// optional .Proto.Uuid uuid = 1;
inline bool AppSignalList::_internal_has_uuid() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  PROTOBUF_ASSUME(!value || uuid_ != nullptr);
  return value;
}
inline bool AppSignalList::has_uuid() const {
  return _internal_has_uuid();
}
inline const ::Proto::Uuid& AppSignalList::_internal_uuid() const {
  const ::Proto::Uuid* p = uuid_;
  return p != nullptr ? *p : reinterpret_cast<const ::Proto::Uuid&>(
      ::Proto::_Uuid_default_instance_);
}
inline const ::Proto::Uuid& AppSignalList::uuid() const {
  // @@protoc_insertion_point(field_get:Proto.AppSignalList.uuid)
  return _internal_uuid();
}
inline void AppSignalList::unsafe_arena_set_allocated_uuid(
    ::Proto::Uuid* uuid) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(uuid_);
  }
  uuid_ = uuid;
  if (uuid) {
    _has_bits_[0] |= 0x00000080u;
  } else {
    _has_bits_[0] &= ~0x00000080u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.AppSignalList.uuid)
}
inline ::Proto::Uuid* AppSignalList::release_uuid() {
  _has_bits_[0] &= ~0x00000080u;
  ::Proto::Uuid* temp = uuid_;
  uuid_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Proto::Uuid* AppSignalList::unsafe_arena_release_uuid() {
  // @@protoc_insertion_point(field_release:Proto.AppSignalList.uuid)
  _has_bits_[0] &= ~0x00000080u;
  ::Proto::Uuid* temp = uuid_;
  uuid_ = nullptr;
  return temp;
}
inline ::Proto::Uuid* AppSignalList::_internal_mutable_uuid() {
  _has_bits_[0] |= 0x00000080u;
  if (uuid_ == nullptr) {
    auto* p = CreateMaybeMessage<::Proto::Uuid>(GetArena());
    uuid_ = p;
  }
  return uuid_;
}
inline ::Proto::Uuid* AppSignalList::mutable_uuid() {
  // @@protoc_insertion_point(field_mutable:Proto.AppSignalList.uuid)
  return _internal_mutable_uuid();
}
inline void AppSignalList::set_allocated_uuid(::Proto::Uuid* uuid) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(uuid_);
  }
  if (uuid) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(uuid)->GetArena();
    if (message_arena != submessage_arena) {
      uuid = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, uuid, submessage_arena);
    }
    _has_bits_[0] |= 0x00000080u;
  } else {
    _has_bits_[0] &= ~0x00000080u;
  }
  uuid_ = uuid;
  // @@protoc_insertion_point(field_set_allocated:Proto.AppSignalList.uuid)
}

// optional string id = 2;
inline bool AppSignalList::_internal_has_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool AppSignalList::has_id() const {
  return _internal_has_id();
}
inline void AppSignalList::clear_id() {
  id_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& AppSignalList::id() const {
  // @@protoc_insertion_point(field_get:Proto.AppSignalList.id)
  return _internal_id();
}
inline void AppSignalList::set_id(const std::string& value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Proto.AppSignalList.id)
}
inline std::string* AppSignalList::mutable_id() {
  // @@protoc_insertion_point(field_mutable:Proto.AppSignalList.id)
  return _internal_mutable_id();
}
inline const std::string& AppSignalList::_internal_id() const {
  return id_.Get();
}
inline void AppSignalList::_internal_set_id(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppSignalList::set_id(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:Proto.AppSignalList.id)
}
inline void AppSignalList::set_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:Proto.AppSignalList.id)
}
inline void AppSignalList::set_id(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:Proto.AppSignalList.id)
}
inline std::string* AppSignalList::_internal_mutable_id() {
  _has_bits_[0] |= 0x00000001u;
  return id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppSignalList::release_id() {
  // @@protoc_insertion_point(field_release:Proto.AppSignalList.id)
  if (!_internal_has_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppSignalList::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:Proto.AppSignalList.id)
}

// optional string caption = 3;
inline bool AppSignalList::_internal_has_caption() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool AppSignalList::has_caption() const {
  return _internal_has_caption();
}
inline void AppSignalList::clear_caption() {
  caption_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& AppSignalList::caption() const {
  // @@protoc_insertion_point(field_get:Proto.AppSignalList.caption)
  return _internal_caption();
}
inline void AppSignalList::set_caption(const std::string& value) {
  _internal_set_caption(value);
  // @@protoc_insertion_point(field_set:Proto.AppSignalList.caption)
}
inline std::string* AppSignalList::mutable_caption() {
  // @@protoc_insertion_point(field_mutable:Proto.AppSignalList.caption)
  return _internal_mutable_caption();
}
inline const std::string& AppSignalList::_internal_caption() const {
  return caption_.Get();
}
inline void AppSignalList::_internal_set_caption(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  caption_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppSignalList::set_caption(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  caption_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:Proto.AppSignalList.caption)
}
inline void AppSignalList::set_caption(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  caption_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:Proto.AppSignalList.caption)
}
inline void AppSignalList::set_caption(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  caption_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:Proto.AppSignalList.caption)
}
inline std::string* AppSignalList::_internal_mutable_caption() {
  _has_bits_[0] |= 0x00000002u;
  return caption_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppSignalList::release_caption() {
  // @@protoc_insertion_point(field_release:Proto.AppSignalList.caption)
  if (!_internal_has_caption()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return caption_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppSignalList::set_allocated_caption(std::string* caption) {
  if (caption != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  caption_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), caption,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:Proto.AppSignalList.caption)
}

// optional int32 signalType = 4;
inline bool AppSignalList::_internal_has_signaltype() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool AppSignalList::has_signaltype() const {
  return _internal_has_signaltype();
}
inline void AppSignalList::clear_signaltype() {
  signaltype_ = 0;
  _has_bits_[0] &= ~0x00000100u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 AppSignalList::_internal_signaltype() const {
  return signaltype_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 AppSignalList::signaltype() const {
  // @@protoc_insertion_point(field_get:Proto.AppSignalList.signalType)
  return _internal_signaltype();
}
inline void AppSignalList::_internal_set_signaltype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000100u;
  signaltype_ = value;
}
inline void AppSignalList::set_signaltype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_signaltype(value);
  // @@protoc_insertion_point(field_set:Proto.AppSignalList.signalType)
}

// optional string tags = 5;
inline bool AppSignalList::_internal_has_tags() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool AppSignalList::has_tags() const {
  return _internal_has_tags();
}
inline void AppSignalList::clear_tags() {
  tags_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& AppSignalList::tags() const {
  // @@protoc_insertion_point(field_get:Proto.AppSignalList.tags)
  return _internal_tags();
}
inline void AppSignalList::set_tags(const std::string& value) {
  _internal_set_tags(value);
  // @@protoc_insertion_point(field_set:Proto.AppSignalList.tags)
}
inline std::string* AppSignalList::mutable_tags() {
  // @@protoc_insertion_point(field_mutable:Proto.AppSignalList.tags)
  return _internal_mutable_tags();
}
inline const std::string& AppSignalList::_internal_tags() const {
  return tags_.Get();
}
inline void AppSignalList::_internal_set_tags(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  tags_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppSignalList::set_tags(std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  tags_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:Proto.AppSignalList.tags)
}
inline void AppSignalList::set_tags(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000004u;
  tags_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:Proto.AppSignalList.tags)
}
inline void AppSignalList::set_tags(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000004u;
  tags_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:Proto.AppSignalList.tags)
}
inline std::string* AppSignalList::_internal_mutable_tags() {
  _has_bits_[0] |= 0x00000004u;
  return tags_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppSignalList::release_tags() {
  // @@protoc_insertion_point(field_release:Proto.AppSignalList.tags)
  if (!_internal_has_tags()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return tags_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppSignalList::set_allocated_tags(std::string* tags) {
  if (tags != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  tags_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), tags,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:Proto.AppSignalList.tags)
}

// optional string customAppSignalIDMasks = 6;
inline bool AppSignalList::_internal_has_customappsignalidmasks() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool AppSignalList::has_customappsignalidmasks() const {
  return _internal_has_customappsignalidmasks();
}
inline void AppSignalList::clear_customappsignalidmasks() {
  customappsignalidmasks_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000008u;
}
inline const std::string& AppSignalList::customappsignalidmasks() const {
  // @@protoc_insertion_point(field_get:Proto.AppSignalList.customAppSignalIDMasks)
  return _internal_customappsignalidmasks();
}
inline void AppSignalList::set_customappsignalidmasks(const std::string& value) {
  _internal_set_customappsignalidmasks(value);
  // @@protoc_insertion_point(field_set:Proto.AppSignalList.customAppSignalIDMasks)
}
inline std::string* AppSignalList::mutable_customappsignalidmasks() {
  // @@protoc_insertion_point(field_mutable:Proto.AppSignalList.customAppSignalIDMasks)
  return _internal_mutable_customappsignalidmasks();
}
inline const std::string& AppSignalList::_internal_customappsignalidmasks() const {
  return customappsignalidmasks_.Get();
}
inline void AppSignalList::_internal_set_customappsignalidmasks(const std::string& value) {
  _has_bits_[0] |= 0x00000008u;
  customappsignalidmasks_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppSignalList::set_customappsignalidmasks(std::string&& value) {
  _has_bits_[0] |= 0x00000008u;
  customappsignalidmasks_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:Proto.AppSignalList.customAppSignalIDMasks)
}
inline void AppSignalList::set_customappsignalidmasks(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000008u;
  customappsignalidmasks_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:Proto.AppSignalList.customAppSignalIDMasks)
}
inline void AppSignalList::set_customappsignalidmasks(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000008u;
  customappsignalidmasks_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:Proto.AppSignalList.customAppSignalIDMasks)
}
inline std::string* AppSignalList::_internal_mutable_customappsignalidmasks() {
  _has_bits_[0] |= 0x00000008u;
  return customappsignalidmasks_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppSignalList::release_customappsignalidmasks() {
  // @@protoc_insertion_point(field_release:Proto.AppSignalList.customAppSignalIDMasks)
  if (!_internal_has_customappsignalidmasks()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000008u;
  return customappsignalidmasks_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppSignalList::set_allocated_customappsignalidmasks(std::string* customappsignalidmasks) {
  if (customappsignalidmasks != nullptr) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  customappsignalidmasks_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), customappsignalidmasks,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:Proto.AppSignalList.customAppSignalIDMasks)
}

// optional string equipmentIDMasks = 7;
inline bool AppSignalList::_internal_has_equipmentidmasks() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool AppSignalList::has_equipmentidmasks() const {
  return _internal_has_equipmentidmasks();
}
inline void AppSignalList::clear_equipmentidmasks() {
  equipmentidmasks_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000010u;
}
inline const std::string& AppSignalList::equipmentidmasks() const {
  // @@protoc_insertion_point(field_get:Proto.AppSignalList.equipmentIDMasks)
  return _internal_equipmentidmasks();
}
inline void AppSignalList::set_equipmentidmasks(const std::string& value) {
  _internal_set_equipmentidmasks(value);
  // @@protoc_insertion_point(field_set:Proto.AppSignalList.equipmentIDMasks)
}
inline std::string* AppSignalList::mutable_equipmentidmasks() {
  // @@protoc_insertion_point(field_mutable:Proto.AppSignalList.equipmentIDMasks)
  return _internal_mutable_equipmentidmasks();
}
inline const std::string& AppSignalList::_internal_equipmentidmasks() const {
  return equipmentidmasks_.Get();
}
inline void AppSignalList::_internal_set_equipmentidmasks(const std::string& value) {
  _has_bits_[0] |= 0x00000010u;
  equipmentidmasks_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppSignalList::set_equipmentidmasks(std::string&& value) {
  _has_bits_[0] |= 0x00000010u;
  equipmentidmasks_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:Proto.AppSignalList.equipmentIDMasks)
}
inline void AppSignalList::set_equipmentidmasks(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000010u;
  equipmentidmasks_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:Proto.AppSignalList.equipmentIDMasks)
}
inline void AppSignalList::set_equipmentidmasks(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000010u;
  equipmentidmasks_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:Proto.AppSignalList.equipmentIDMasks)
}
inline std::string* AppSignalList::_internal_mutable_equipmentidmasks() {
  _has_bits_[0] |= 0x00000010u;
  return equipmentidmasks_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppSignalList::release_equipmentidmasks() {
  // @@protoc_insertion_point(field_release:Proto.AppSignalList.equipmentIDMasks)
  if (!_internal_has_equipmentidmasks()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000010u;
  return equipmentidmasks_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppSignalList::set_allocated_equipmentidmasks(std::string* equipmentidmasks) {
  if (equipmentidmasks != nullptr) {
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  equipmentidmasks_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), equipmentidmasks,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:Proto.AppSignalList.equipmentIDMasks)
}

// optional string appSignalIDMasks = 8;
inline bool AppSignalList::_internal_has_appsignalidmasks() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool AppSignalList::has_appsignalidmasks() const {
  return _internal_has_appsignalidmasks();
}
inline void AppSignalList::clear_appsignalidmasks() {
  appsignalidmasks_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000020u;
}
inline const std::string& AppSignalList::appsignalidmasks() const {
  // @@protoc_insertion_point(field_get:Proto.AppSignalList.appSignalIDMasks)
  return _internal_appsignalidmasks();
}
inline void AppSignalList::set_appsignalidmasks(const std::string& value) {
  _internal_set_appsignalidmasks(value);
  // @@protoc_insertion_point(field_set:Proto.AppSignalList.appSignalIDMasks)
}
inline std::string* AppSignalList::mutable_appsignalidmasks() {
  // @@protoc_insertion_point(field_mutable:Proto.AppSignalList.appSignalIDMasks)
  return _internal_mutable_appsignalidmasks();
}
inline const std::string& AppSignalList::_internal_appsignalidmasks() const {
  return appsignalidmasks_.Get();
}
inline void AppSignalList::_internal_set_appsignalidmasks(const std::string& value) {
  _has_bits_[0] |= 0x00000020u;
  appsignalidmasks_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppSignalList::set_appsignalidmasks(std::string&& value) {
  _has_bits_[0] |= 0x00000020u;
  appsignalidmasks_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:Proto.AppSignalList.appSignalIDMasks)
}
inline void AppSignalList::set_appsignalidmasks(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000020u;
  appsignalidmasks_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:Proto.AppSignalList.appSignalIDMasks)
}
inline void AppSignalList::set_appsignalidmasks(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000020u;
  appsignalidmasks_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:Proto.AppSignalList.appSignalIDMasks)
}
inline std::string* AppSignalList::_internal_mutable_appsignalidmasks() {
  _has_bits_[0] |= 0x00000020u;
  return appsignalidmasks_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppSignalList::release_appsignalidmasks() {
  // @@protoc_insertion_point(field_release:Proto.AppSignalList.appSignalIDMasks)
  if (!_internal_has_appsignalidmasks()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000020u;
  return appsignalidmasks_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppSignalList::set_allocated_appsignalidmasks(std::string* appsignalidmasks) {
  if (appsignalidmasks != nullptr) {
    _has_bits_[0] |= 0x00000020u;
  } else {
    _has_bits_[0] &= ~0x00000020u;
  }
  appsignalidmasks_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), appsignalidmasks,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:Proto.AppSignalList.appSignalIDMasks)
}

// optional string appSignalTags = 9;
inline bool AppSignalList::_internal_has_appsignaltags() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool AppSignalList::has_appsignaltags() const {
  return _internal_has_appsignaltags();
}
inline void AppSignalList::clear_appsignaltags() {
  appsignaltags_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000040u;
}
inline const std::string& AppSignalList::appsignaltags() const {
  // @@protoc_insertion_point(field_get:Proto.AppSignalList.appSignalTags)
  return _internal_appsignaltags();
}
inline void AppSignalList::set_appsignaltags(const std::string& value) {
  _internal_set_appsignaltags(value);
  // @@protoc_insertion_point(field_set:Proto.AppSignalList.appSignalTags)
}
inline std::string* AppSignalList::mutable_appsignaltags() {
  // @@protoc_insertion_point(field_mutable:Proto.AppSignalList.appSignalTags)
  return _internal_mutable_appsignaltags();
}
inline const std::string& AppSignalList::_internal_appsignaltags() const {
  return appsignaltags_.Get();
}
inline void AppSignalList::_internal_set_appsignaltags(const std::string& value) {
  _has_bits_[0] |= 0x00000040u;
  appsignaltags_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppSignalList::set_appsignaltags(std::string&& value) {
  _has_bits_[0] |= 0x00000040u;
  appsignaltags_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:Proto.AppSignalList.appSignalTags)
}
inline void AppSignalList::set_appsignaltags(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000040u;
  appsignaltags_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:Proto.AppSignalList.appSignalTags)
}
inline void AppSignalList::set_appsignaltags(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000040u;
  appsignaltags_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:Proto.AppSignalList.appSignalTags)
}
inline std::string* AppSignalList::_internal_mutable_appsignaltags() {
  _has_bits_[0] |= 0x00000040u;
  return appsignaltags_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppSignalList::release_appsignaltags() {
  // @@protoc_insertion_point(field_release:Proto.AppSignalList.appSignalTags)
  if (!_internal_has_appsignaltags()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000040u;
  return appsignaltags_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppSignalList::set_allocated_appsignaltags(std::string* appsignaltags) {
  if (appsignaltags != nullptr) {
    _has_bits_[0] |= 0x00000040u;
  } else {
    _has_bits_[0] &= ~0x00000040u;
  }
  appsignaltags_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), appsignaltags,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:Proto.AppSignalList.appSignalTags)
}

// repeated .Proto.AppSignalListSignal listSignals = 10;
inline int AppSignalList::_internal_listsignals_size() const {
  return listsignals_.size();
}
inline int AppSignalList::listsignals_size() const {
  return _internal_listsignals_size();
}
inline void AppSignalList::clear_listsignals() {
  listsignals_.Clear();
}
inline ::Proto::AppSignalListSignal* AppSignalList::mutable_listsignals(int index) {
  // @@protoc_insertion_point(field_mutable:Proto.AppSignalList.listSignals)
  return listsignals_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::AppSignalListSignal >*
AppSignalList::mutable_listsignals() {
  // @@protoc_insertion_point(field_mutable_list:Proto.AppSignalList.listSignals)
  return &listsignals_;
}
inline const ::Proto::AppSignalListSignal& AppSignalList::_internal_listsignals(int index) const {
  return listsignals_.Get(index);
}
inline const ::Proto::AppSignalListSignal& AppSignalList::listsignals(int index) const {
  // @@protoc_insertion_point(field_get:Proto.AppSignalList.listSignals)
  return _internal_listsignals(index);
}
inline ::Proto::AppSignalListSignal* AppSignalList::_internal_add_listsignals() {
  return listsignals_.Add();
}
inline ::Proto::AppSignalListSignal* AppSignalList::add_listsignals() {
  // @@protoc_insertion_point(field_add:Proto.AppSignalList.listSignals)
  return _internal_add_listsignals();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::AppSignalListSignal >&
AppSignalList::listsignals() const {
  // @@protoc_insertion_point(field_list:Proto.AppSignalList.listSignals)
  return listsignals_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_AppSignalList_2eproto

#ifdef _MSC_VER
#pragma warning(pop)
#endif