#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable : 4100)
#pragma warning(disable : 4244)
#pragma warning(disable : 4125)
#pragma warning(disable : 4127)
#pragma warning(disable : 4267)
#pragma warning(disable : 4512)
#pragma warning(disable : 4996)
#pragma warning(disable : 6011)
#pragma warning(disable : 6326)
#pragma warning(disable : 6385)
#pragma warning(disable : 6387)
#endif
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ArchSignal.proto

#include "ArchSignal.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace Proto {
constexpr ArchSignal::ArchSignal(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : appsignalid_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , unit_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , lowlimit_(0)
  , highlimit_(0)
  , fineaperture_(0)
  , coarseaperture_(0)
  , signaltype_(0){}
struct ArchSignalDefaultTypeInternal {
  constexpr ArchSignalDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ArchSignalDefaultTypeInternal() {}
  union {
    ArchSignal _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ArchSignalDefaultTypeInternal _ArchSignal_default_instance_;
constexpr ArchInfo::ArchInfo(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : archsignal_()
  , archiveserviceid_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , buildinfo_(nullptr){}
struct ArchInfoDefaultTypeInternal {
  constexpr ArchInfoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ArchInfoDefaultTypeInternal() {}
  union {
    ArchInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ArchInfoDefaultTypeInternal _ArchInfo_default_instance_;
}  // namespace Proto
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_ArchSignal_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_ArchSignal_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_ArchSignal_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_ArchSignal_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::Proto::ArchSignal, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::Proto::ArchSignal, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Proto::ArchSignal, appsignalid_),
  PROTOBUF_FIELD_OFFSET(::Proto::ArchSignal, signaltype_),
  PROTOBUF_FIELD_OFFSET(::Proto::ArchSignal, lowlimit_),
  PROTOBUF_FIELD_OFFSET(::Proto::ArchSignal, highlimit_),
  PROTOBUF_FIELD_OFFSET(::Proto::ArchSignal, unit_),
  PROTOBUF_FIELD_OFFSET(::Proto::ArchSignal, fineaperture_),
  PROTOBUF_FIELD_OFFSET(::Proto::ArchSignal, coarseaperture_),
  0,
  6,
  2,
  3,
  1,
  4,
  5,
  PROTOBUF_FIELD_OFFSET(::Proto::ArchInfo, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::Proto::ArchInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Proto::ArchInfo, buildinfo_),
  PROTOBUF_FIELD_OFFSET(::Proto::ArchInfo, archiveserviceid_),
  PROTOBUF_FIELD_OFFSET(::Proto::ArchInfo, archsignal_),
  1,
  0,
  ~0u,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 12, sizeof(::Proto::ArchSignal)},
  { 19, 27, sizeof(::Proto::ArchInfo)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Proto::_ArchSignal_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Proto::_ArchInfo_default_instance_),
};

const char descriptor_table_protodef_ArchSignal_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020ArchSignal.proto\022\005Proto\032\017BuildInfo.pro"
  "to\"\242\001\n\nArchSignal\022\023\n\013appSignalID\030\001 \002(\t\022\022"
  "\n\nsignalType\030\002 \002(\005\022\023\n\010lowLimit\030\003 \001(\001:\0010\022"
  "\024\n\thighLimit\030\004 \001(\001:\0010\022\014\n\004unit\030\005 \001(\t\022\027\n\014f"
  "ineAperture\030\006 \001(\001:\0010\022\031\n\016coarseAperture\030\007"
  " \001(\001:\0010\"p\n\010ArchInfo\022#\n\tbuildInfo\030\001 \002(\0132\020"
  ".Proto.BuildInfo\022\030\n\020archiveServiceID\030\002 \002"
  "(\t\022%\n\narchSignal\030\003 \003(\0132\021.Proto.ArchSigna"
  "l"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_ArchSignal_2eproto_deps[1] = {
  &::descriptor_table_BuildInfo_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_ArchSignal_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ArchSignal_2eproto = {
  false, false, 321, descriptor_table_protodef_ArchSignal_2eproto, "ArchSignal.proto", 
  &descriptor_table_ArchSignal_2eproto_once, descriptor_table_ArchSignal_2eproto_deps, 1, 2,
  schemas, file_default_instances, TableStruct_ArchSignal_2eproto::offsets,
  file_level_metadata_ArchSignal_2eproto, file_level_enum_descriptors_ArchSignal_2eproto, file_level_service_descriptors_ArchSignal_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_ArchSignal_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ArchSignal_2eproto);
  return descriptor_table_ArchSignal_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_ArchSignal_2eproto(&descriptor_table_ArchSignal_2eproto);
namespace Proto {

// ===================================================================

class ArchSignal::_Internal {
 public:
  using HasBits = decltype(std::declval<ArchSignal>()._has_bits_);
  static void set_has_appsignalid(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_signaltype(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_lowlimit(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_highlimit(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_unit(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_fineaperture(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_coarseaperture(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000041) ^ 0x00000041) != 0;
  }
};

ArchSignal::ArchSignal(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Proto.ArchSignal)
}
ArchSignal::ArchSignal(const ArchSignal& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  appsignalid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_appsignalid()) {
    appsignalid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_appsignalid(), 
      GetArena());
  }
  unit_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_unit()) {
    unit_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_unit(), 
      GetArena());
  }
  ::memcpy(&lowlimit_, &from.lowlimit_,
    static_cast<size_t>(reinterpret_cast<char*>(&signaltype_) -
    reinterpret_cast<char*>(&lowlimit_)) + sizeof(signaltype_));
  // @@protoc_insertion_point(copy_constructor:Proto.ArchSignal)
}

void ArchSignal::SharedCtor() {
appsignalid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
unit_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&lowlimit_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&signaltype_) -
    reinterpret_cast<char*>(&lowlimit_)) + sizeof(signaltype_));
}

ArchSignal::~ArchSignal() {
  // @@protoc_insertion_point(destructor:Proto.ArchSignal)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ArchSignal::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  appsignalid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  unit_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ArchSignal::ArenaDtor(void* object) {
  ArchSignal* _this = reinterpret_cast< ArchSignal* >(object);
  (void)_this;
}
void ArchSignal::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ArchSignal::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ArchSignal::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto.ArchSignal)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      appsignalid_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      unit_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x0000007cu) {
    ::memset(&lowlimit_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&signaltype_) -
        reinterpret_cast<char*>(&lowlimit_)) + sizeof(signaltype_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ArchSignal::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required string appSignalID = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_appsignalid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Proto.ArchSignal.appSignalID");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required int32 signalType = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_signaltype(&has_bits);
          signaltype_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional double lowLimit = 3 [default = 0];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 25)) {
          _Internal::set_has_lowlimit(&has_bits);
          lowlimit_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double highLimit = 4 [default = 0];
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 33)) {
          _Internal::set_has_highlimit(&has_bits);
          highlimit_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional string unit = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_unit();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Proto.ArchSignal.unit");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional double fineAperture = 6 [default = 0];
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 49)) {
          _Internal::set_has_fineaperture(&has_bits);
          fineaperture_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double coarseAperture = 7 [default = 0];
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 57)) {
          _Internal::set_has_coarseaperture(&has_bits);
          coarseaperture_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ArchSignal::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Proto.ArchSignal)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string appSignalID = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_appsignalid().data(), static_cast<int>(this->_internal_appsignalid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "Proto.ArchSignal.appSignalID");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_appsignalid(), target);
  }

  // required int32 signalType = 2;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_signaltype(), target);
  }

  // optional double lowLimit = 3 [default = 0];
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(3, this->_internal_lowlimit(), target);
  }

  // optional double highLimit = 4 [default = 0];
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(4, this->_internal_highlimit(), target);
  }

  // optional string unit = 5;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_unit().data(), static_cast<int>(this->_internal_unit().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "Proto.ArchSignal.unit");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_unit(), target);
  }

  // optional double fineAperture = 6 [default = 0];
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(6, this->_internal_fineaperture(), target);
  }

  // optional double coarseAperture = 7 [default = 0];
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(7, this->_internal_coarseaperture(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto.ArchSignal)
  return target;
}

size_t ArchSignal::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:Proto.ArchSignal)
  size_t total_size = 0;

  if (_internal_has_appsignalid()) {
    // required string appSignalID = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_appsignalid());
  }

  if (_internal_has_signaltype()) {
    // required int32 signalType = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_signaltype());
  }

  return total_size;
}
size_t ArchSignal::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Proto.ArchSignal)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000041) ^ 0x00000041) == 0) {  // All required fields are present.
    // required string appSignalID = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_appsignalid());

    // required int32 signalType = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_signaltype());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000003eu) {
    // optional string unit = 5;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_unit());
    }

    // optional double lowLimit = 3 [default = 0];
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 8;
    }

    // optional double highLimit = 4 [default = 0];
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 8;
    }

    // optional double fineAperture = 6 [default = 0];
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 8;
    }

    // optional double coarseAperture = 7 [default = 0];
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + 8;
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ArchSignal::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Proto.ArchSignal)
  GOOGLE_DCHECK_NE(&from, this);
  const ArchSignal* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ArchSignal>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Proto.ArchSignal)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Proto.ArchSignal)
    MergeFrom(*source);
  }
}

void ArchSignal::MergeFrom(const ArchSignal& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Proto.ArchSignal)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_appsignalid(from._internal_appsignalid());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_unit(from._internal_unit());
    }
    if (cached_has_bits & 0x00000004u) {
      lowlimit_ = from.lowlimit_;
    }
    if (cached_has_bits & 0x00000008u) {
      highlimit_ = from.highlimit_;
    }
    if (cached_has_bits & 0x00000010u) {
      fineaperture_ = from.fineaperture_;
    }
    if (cached_has_bits & 0x00000020u) {
      coarseaperture_ = from.coarseaperture_;
    }
    if (cached_has_bits & 0x00000040u) {
      signaltype_ = from.signaltype_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ArchSignal::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Proto.ArchSignal)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ArchSignal::CopyFrom(const ArchSignal& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto.ArchSignal)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ArchSignal::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  return true;
}

void ArchSignal::InternalSwap(ArchSignal* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  appsignalid_.Swap(&other->appsignalid_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  unit_.Swap(&other->unit_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ArchSignal, signaltype_)
      + sizeof(ArchSignal::signaltype_)
      - PROTOBUF_FIELD_OFFSET(ArchSignal, lowlimit_)>(
          reinterpret_cast<char*>(&lowlimit_),
          reinterpret_cast<char*>(&other->lowlimit_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ArchSignal::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class ArchInfo::_Internal {
 public:
  using HasBits = decltype(std::declval<ArchInfo>()._has_bits_);
  static const ::Proto::BuildInfo& buildinfo(const ArchInfo* msg);
  static void set_has_buildinfo(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_archiveserviceid(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000003) ^ 0x00000003) != 0;
  }
};

const ::Proto::BuildInfo&
ArchInfo::_Internal::buildinfo(const ArchInfo* msg) {
  return *msg->buildinfo_;
}
void ArchInfo::clear_buildinfo() {
  if (buildinfo_ != nullptr) buildinfo_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
ArchInfo::ArchInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  archsignal_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Proto.ArchInfo)
}
ArchInfo::ArchInfo(const ArchInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      archsignal_(from.archsignal_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  archiveserviceid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_archiveserviceid()) {
    archiveserviceid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_archiveserviceid(), 
      GetArena());
  }
  if (from._internal_has_buildinfo()) {
    buildinfo_ = new ::Proto::BuildInfo(*from.buildinfo_);
  } else {
    buildinfo_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:Proto.ArchInfo)
}

void ArchInfo::SharedCtor() {
archiveserviceid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
buildinfo_ = nullptr;
}

ArchInfo::~ArchInfo() {
  // @@protoc_insertion_point(destructor:Proto.ArchInfo)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ArchInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  archiveserviceid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete buildinfo_;
}

void ArchInfo::ArenaDtor(void* object) {
  ArchInfo* _this = reinterpret_cast< ArchInfo* >(object);
  (void)_this;
}
void ArchInfo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ArchInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ArchInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto.ArchInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  archsignal_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      archiveserviceid_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(buildinfo_ != nullptr);
      buildinfo_->Clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ArchInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required .Proto.BuildInfo buildInfo = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_buildinfo(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required string archiveServiceID = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_archiveserviceid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Proto.ArchInfo.archiveServiceID");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .Proto.ArchSignal archSignal = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_archsignal(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ArchInfo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Proto.ArchInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .Proto.BuildInfo buildInfo = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::buildinfo(this), target, stream);
  }

  // required string archiveServiceID = 2;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_archiveserviceid().data(), static_cast<int>(this->_internal_archiveserviceid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "Proto.ArchInfo.archiveServiceID");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_archiveserviceid(), target);
  }

  // repeated .Proto.ArchSignal archSignal = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_archsignal_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, this->_internal_archsignal(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto.ArchInfo)
  return target;
}

size_t ArchInfo::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:Proto.ArchInfo)
  size_t total_size = 0;

  if (_internal_has_archiveserviceid()) {
    // required string archiveServiceID = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_archiveserviceid());
  }

  if (_internal_has_buildinfo()) {
    // required .Proto.BuildInfo buildInfo = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *buildinfo_);
  }

  return total_size;
}
size_t ArchInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Proto.ArchInfo)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required string archiveServiceID = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_archiveserviceid());

    // required .Proto.BuildInfo buildInfo = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *buildinfo_);

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Proto.ArchSignal archSignal = 3;
  total_size += 1UL * this->_internal_archsignal_size();
  for (const auto& msg : this->archsignal_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ArchInfo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Proto.ArchInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const ArchInfo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ArchInfo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Proto.ArchInfo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Proto.ArchInfo)
    MergeFrom(*source);
  }
}

void ArchInfo::MergeFrom(const ArchInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Proto.ArchInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  archsignal_.MergeFrom(from.archsignal_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_archiveserviceid(from._internal_archiveserviceid());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_buildinfo()->::Proto::BuildInfo::MergeFrom(from._internal_buildinfo());
    }
  }
}

void ArchInfo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Proto.ArchInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ArchInfo::CopyFrom(const ArchInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto.ArchInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ArchInfo::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(archsignal_)) return false;
  return true;
}

void ArchInfo::InternalSwap(ArchInfo* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  archsignal_.InternalSwap(&other->archsignal_);
  archiveserviceid_.Swap(&other->archiveserviceid_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(buildinfo_, other->buildinfo_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ArchInfo::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Proto
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Proto::ArchSignal* Arena::CreateMaybeMessage< ::Proto::ArchSignal >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Proto::ArchSignal >(arena);
}
template<> PROTOBUF_NOINLINE ::Proto::ArchInfo* Arena::CreateMaybeMessage< ::Proto::ArchInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Proto::ArchInfo >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>

#ifdef _MSC_VER
#pragma warning(pop)
#endif