// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Comparator.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Comparator_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Comparator_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Common.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Comparator_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Comparator_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Comparator_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_Comparator_2eproto_metadata_getter(int index);
namespace Proto {
class Comparator;
struct ComparatorDefaultTypeInternal;
extern ComparatorDefaultTypeInternal _Comparator_default_instance_;
class ComparatorSet;
struct ComparatorSetDefaultTypeInternal;
extern ComparatorSetDefaultTypeInternal _ComparatorSet_default_instance_;
class ComparatorSignal;
struct ComparatorSignalDefaultTypeInternal;
extern ComparatorSignalDefaultTypeInternal _ComparatorSignal_default_instance_;
class LmComparatorSet;
struct LmComparatorSetDefaultTypeInternal;
extern LmComparatorSetDefaultTypeInternal _LmComparatorSet_default_instance_;
}  // namespace Proto
PROTOBUF_NAMESPACE_OPEN
template<> ::Proto::Comparator* Arena::CreateMaybeMessage<::Proto::Comparator>(Arena*);
template<> ::Proto::ComparatorSet* Arena::CreateMaybeMessage<::Proto::ComparatorSet>(Arena*);
template<> ::Proto::ComparatorSignal* Arena::CreateMaybeMessage<::Proto::ComparatorSignal>(Arena*);
template<> ::Proto::LmComparatorSet* Arena::CreateMaybeMessage<::Proto::LmComparatorSet>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Proto {

// ===================================================================

class ComparatorSignal PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.ComparatorSignal) */ {
 public:
  inline ComparatorSignal() : ComparatorSignal(nullptr) {}
  virtual ~ComparatorSignal();
  explicit constexpr ComparatorSignal(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ComparatorSignal(const ComparatorSignal& from);
  ComparatorSignal(ComparatorSignal&& from) noexcept
    : ComparatorSignal() {
    *this = ::std::move(from);
  }

  inline ComparatorSignal& operator=(const ComparatorSignal& from) {
    CopyFrom(from);
    return *this;
  }
  inline ComparatorSignal& operator=(ComparatorSignal&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ComparatorSignal& default_instance() {
    return *internal_default_instance();
  }
  static inline const ComparatorSignal* internal_default_instance() {
    return reinterpret_cast<const ComparatorSignal*>(
               &_ComparatorSignal_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ComparatorSignal& a, ComparatorSignal& b) {
    a.Swap(&b);
  }
  inline void Swap(ComparatorSignal* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ComparatorSignal* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ComparatorSignal* New() const final {
    return CreateMaybeMessage<ComparatorSignal>(nullptr);
  }

  ComparatorSignal* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ComparatorSignal>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ComparatorSignal& from);
  void MergeFrom(const ComparatorSignal& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ComparatorSignal* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.ComparatorSignal";
  }
  protected:
  explicit ComparatorSignal(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_Comparator_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAppSignalIdFieldNumber = 3,
    kConstValueFieldNumber = 2,
    kIsAcquiredFieldNumber = 4,
    kIsConstFieldNumber = 1,
  };
  // optional string appSignalId = 3;
  bool has_appsignalid() const;
  private:
  bool _internal_has_appsignalid() const;
  public:
  void clear_appsignalid();
  const std::string& appsignalid() const;
  void set_appsignalid(const std::string& value);
  void set_appsignalid(std::string&& value);
  void set_appsignalid(const char* value);
  void set_appsignalid(const char* value, size_t size);
  std::string* mutable_appsignalid();
  std::string* release_appsignalid();
  void set_allocated_appsignalid(std::string* appsignalid);
  private:
  const std::string& _internal_appsignalid() const;
  void _internal_set_appsignalid(const std::string& value);
  std::string* _internal_mutable_appsignalid();
  public:

  // optional double constValue = 2 [default = 0];
  bool has_constvalue() const;
  private:
  bool _internal_has_constvalue() const;
  public:
  void clear_constvalue();
  double constvalue() const;
  void set_constvalue(double value);
  private:
  double _internal_constvalue() const;
  void _internal_set_constvalue(double value);
  public:

  // optional bool isAcquired = 4 [default = false];
  bool has_isacquired() const;
  private:
  bool _internal_has_isacquired() const;
  public:
  void clear_isacquired();
  bool isacquired() const;
  void set_isacquired(bool value);
  private:
  bool _internal_isacquired() const;
  void _internal_set_isacquired(bool value);
  public:

  // optional bool isConst = 1 [default = true];
  bool has_isconst() const;
  private:
  bool _internal_has_isconst() const;
  public:
  void clear_isconst();
  bool isconst() const;
  void set_isconst(bool value);
  private:
  bool _internal_isconst() const;
  void _internal_set_isconst(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Proto.ComparatorSignal)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr appsignalid_;
  double constvalue_;
  bool isacquired_;
  bool isconst_;
  friend struct ::TableStruct_Comparator_2eproto;
};
// -------------------------------------------------------------------

class Comparator PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.Comparator) */ {
 public:
  inline Comparator() : Comparator(nullptr) {}
  virtual ~Comparator();
  explicit constexpr Comparator(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Comparator(const Comparator& from);
  Comparator(Comparator&& from) noexcept
    : Comparator() {
    *this = ::std::move(from);
  }

  inline Comparator& operator=(const Comparator& from) {
    CopyFrom(from);
    return *this;
  }
  inline Comparator& operator=(Comparator&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Comparator& default_instance() {
    return *internal_default_instance();
  }
  static inline const Comparator* internal_default_instance() {
    return reinterpret_cast<const Comparator*>(
               &_Comparator_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Comparator& a, Comparator& b) {
    a.Swap(&b);
  }
  inline void Swap(Comparator* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Comparator* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Comparator* New() const final {
    return CreateMaybeMessage<Comparator>(nullptr);
  }

  Comparator* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Comparator>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Comparator& from);
  void MergeFrom(const Comparator& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Comparator* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Comparator";
  }
  protected:
  explicit Comparator(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_Comparator_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLabelFieldNumber = 9,
    kSchemaIdFieldNumber = 10,
    kInputFieldNumber = 3,
    kCompareFieldNumber = 4,
    kHysteresisFieldNumber = 5,
    kOutputFieldNumber = 6,
    kSchemaItemUuidFieldNumber = 11,
    kAllSignalsIsAcquiredFieldNumber = 7,
    kPrecisionFieldNumber = 8,
    kCmpTypeFieldNumber = 1,
    kInAnalogSignalFormatFieldNumber = 2,
  };
  // optional string label = 9;
  bool has_label() const;
  private:
  bool _internal_has_label() const;
  public:
  void clear_label();
  const std::string& label() const;
  void set_label(const std::string& value);
  void set_label(std::string&& value);
  void set_label(const char* value);
  void set_label(const char* value, size_t size);
  std::string* mutable_label();
  std::string* release_label();
  void set_allocated_label(std::string* label);
  private:
  const std::string& _internal_label() const;
  void _internal_set_label(const std::string& value);
  std::string* _internal_mutable_label();
  public:

  // optional string schemaId = 10;
  bool has_schemaid() const;
  private:
  bool _internal_has_schemaid() const;
  public:
  void clear_schemaid();
  const std::string& schemaid() const;
  void set_schemaid(const std::string& value);
  void set_schemaid(std::string&& value);
  void set_schemaid(const char* value);
  void set_schemaid(const char* value, size_t size);
  std::string* mutable_schemaid();
  std::string* release_schemaid();
  void set_allocated_schemaid(std::string* schemaid);
  private:
  const std::string& _internal_schemaid() const;
  void _internal_set_schemaid(const std::string& value);
  std::string* _internal_mutable_schemaid();
  public:

  // optional .Proto.ComparatorSignal input = 3;
  bool has_input() const;
  private:
  bool _internal_has_input() const;
  public:
  void clear_input();
  const ::Proto::ComparatorSignal& input() const;
  ::Proto::ComparatorSignal* release_input();
  ::Proto::ComparatorSignal* mutable_input();
  void set_allocated_input(::Proto::ComparatorSignal* input);
  private:
  const ::Proto::ComparatorSignal& _internal_input() const;
  ::Proto::ComparatorSignal* _internal_mutable_input();
  public:
  void unsafe_arena_set_allocated_input(
      ::Proto::ComparatorSignal* input);
  ::Proto::ComparatorSignal* unsafe_arena_release_input();

  // optional .Proto.ComparatorSignal compare = 4;
  bool has_compare() const;
  private:
  bool _internal_has_compare() const;
  public:
  void clear_compare();
  const ::Proto::ComparatorSignal& compare() const;
  ::Proto::ComparatorSignal* release_compare();
  ::Proto::ComparatorSignal* mutable_compare();
  void set_allocated_compare(::Proto::ComparatorSignal* compare);
  private:
  const ::Proto::ComparatorSignal& _internal_compare() const;
  ::Proto::ComparatorSignal* _internal_mutable_compare();
  public:
  void unsafe_arena_set_allocated_compare(
      ::Proto::ComparatorSignal* compare);
  ::Proto::ComparatorSignal* unsafe_arena_release_compare();

  // optional .Proto.ComparatorSignal hysteresis = 5;
  bool has_hysteresis() const;
  private:
  bool _internal_has_hysteresis() const;
  public:
  void clear_hysteresis();
  const ::Proto::ComparatorSignal& hysteresis() const;
  ::Proto::ComparatorSignal* release_hysteresis();
  ::Proto::ComparatorSignal* mutable_hysteresis();
  void set_allocated_hysteresis(::Proto::ComparatorSignal* hysteresis);
  private:
  const ::Proto::ComparatorSignal& _internal_hysteresis() const;
  ::Proto::ComparatorSignal* _internal_mutable_hysteresis();
  public:
  void unsafe_arena_set_allocated_hysteresis(
      ::Proto::ComparatorSignal* hysteresis);
  ::Proto::ComparatorSignal* unsafe_arena_release_hysteresis();

  // optional .Proto.ComparatorSignal output = 6;
  bool has_output() const;
  private:
  bool _internal_has_output() const;
  public:
  void clear_output();
  const ::Proto::ComparatorSignal& output() const;
  ::Proto::ComparatorSignal* release_output();
  ::Proto::ComparatorSignal* mutable_output();
  void set_allocated_output(::Proto::ComparatorSignal* output);
  private:
  const ::Proto::ComparatorSignal& _internal_output() const;
  ::Proto::ComparatorSignal* _internal_mutable_output();
  public:
  void unsafe_arena_set_allocated_output(
      ::Proto::ComparatorSignal* output);
  ::Proto::ComparatorSignal* unsafe_arena_release_output();

  // optional .Proto.Uuid schemaItemUuid = 11;
  bool has_schemaitemuuid() const;
  private:
  bool _internal_has_schemaitemuuid() const;
  public:
  void clear_schemaitemuuid();
  const ::Proto::Uuid& schemaitemuuid() const;
  ::Proto::Uuid* release_schemaitemuuid();
  ::Proto::Uuid* mutable_schemaitemuuid();
  void set_allocated_schemaitemuuid(::Proto::Uuid* schemaitemuuid);
  private:
  const ::Proto::Uuid& _internal_schemaitemuuid() const;
  ::Proto::Uuid* _internal_mutable_schemaitemuuid();
  public:
  void unsafe_arena_set_allocated_schemaitemuuid(
      ::Proto::Uuid* schemaitemuuid);
  ::Proto::Uuid* unsafe_arena_release_schemaitemuuid();

  // optional bool allSignalsIsAcquired = 7 [default = false];
  bool has_allsignalsisacquired() const;
  private:
  bool _internal_has_allsignalsisacquired() const;
  public:
  void clear_allsignalsisacquired();
  bool allsignalsisacquired() const;
  void set_allsignalsisacquired(bool value);
  private:
  bool _internal_allsignalsisacquired() const;
  void _internal_set_allsignalsisacquired(bool value);
  public:

  // optional int32 precision = 8 [default = 2];
  bool has_precision() const;
  private:
  bool _internal_has_precision() const;
  public:
  void clear_precision();
  ::PROTOBUF_NAMESPACE_ID::int32 precision() const;
  void set_precision(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_precision() const;
  void _internal_set_precision(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 cmpType = 1 [default = 1];
  bool has_cmptype() const;
  private:
  bool _internal_has_cmptype() const;
  public:
  void clear_cmptype();
  ::PROTOBUF_NAMESPACE_ID::int32 cmptype() const;
  void set_cmptype(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_cmptype() const;
  void _internal_set_cmptype(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 inAnalogSignalFormat = 2 [default = 1];
  bool has_inanalogsignalformat() const;
  private:
  bool _internal_has_inanalogsignalformat() const;
  public:
  void clear_inanalogsignalformat();
  ::PROTOBUF_NAMESPACE_ID::int32 inanalogsignalformat() const;
  void set_inanalogsignalformat(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_inanalogsignalformat() const;
  void _internal_set_inanalogsignalformat(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:Proto.Comparator)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr label_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr schemaid_;
  ::Proto::ComparatorSignal* input_;
  ::Proto::ComparatorSignal* compare_;
  ::Proto::ComparatorSignal* hysteresis_;
  ::Proto::ComparatorSignal* output_;
  ::Proto::Uuid* schemaitemuuid_;
  bool allsignalsisacquired_;
  ::PROTOBUF_NAMESPACE_ID::int32 precision_;
  ::PROTOBUF_NAMESPACE_ID::int32 cmptype_;
  ::PROTOBUF_NAMESPACE_ID::int32 inanalogsignalformat_;
  friend struct ::TableStruct_Comparator_2eproto;
};
// -------------------------------------------------------------------

class LmComparatorSet PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.LmComparatorSet) */ {
 public:
  inline LmComparatorSet() : LmComparatorSet(nullptr) {}
  virtual ~LmComparatorSet();
  explicit constexpr LmComparatorSet(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LmComparatorSet(const LmComparatorSet& from);
  LmComparatorSet(LmComparatorSet&& from) noexcept
    : LmComparatorSet() {
    *this = ::std::move(from);
  }

  inline LmComparatorSet& operator=(const LmComparatorSet& from) {
    CopyFrom(from);
    return *this;
  }
  inline LmComparatorSet& operator=(LmComparatorSet&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LmComparatorSet& default_instance() {
    return *internal_default_instance();
  }
  static inline const LmComparatorSet* internal_default_instance() {
    return reinterpret_cast<const LmComparatorSet*>(
               &_LmComparatorSet_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(LmComparatorSet& a, LmComparatorSet& b) {
    a.Swap(&b);
  }
  inline void Swap(LmComparatorSet* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LmComparatorSet* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LmComparatorSet* New() const final {
    return CreateMaybeMessage<LmComparatorSet>(nullptr);
  }

  LmComparatorSet* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LmComparatorSet>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LmComparatorSet& from);
  void MergeFrom(const LmComparatorSet& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LmComparatorSet* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.LmComparatorSet";
  }
  protected:
  explicit LmComparatorSet(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_Comparator_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kComparatorFieldNumber = 2,
    kLmEquipmentIDFieldNumber = 1,
  };
  // repeated .Proto.Comparator comparator = 2;
  int comparator_size() const;
  private:
  int _internal_comparator_size() const;
  public:
  void clear_comparator();
  ::Proto::Comparator* mutable_comparator(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::Comparator >*
      mutable_comparator();
  private:
  const ::Proto::Comparator& _internal_comparator(int index) const;
  ::Proto::Comparator* _internal_add_comparator();
  public:
  const ::Proto::Comparator& comparator(int index) const;
  ::Proto::Comparator* add_comparator();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::Comparator >&
      comparator() const;

  // optional string lmEquipmentID = 1;
  bool has_lmequipmentid() const;
  private:
  bool _internal_has_lmequipmentid() const;
  public:
  void clear_lmequipmentid();
  const std::string& lmequipmentid() const;
  void set_lmequipmentid(const std::string& value);
  void set_lmequipmentid(std::string&& value);
  void set_lmequipmentid(const char* value);
  void set_lmequipmentid(const char* value, size_t size);
  std::string* mutable_lmequipmentid();
  std::string* release_lmequipmentid();
  void set_allocated_lmequipmentid(std::string* lmequipmentid);
  private:
  const std::string& _internal_lmequipmentid() const;
  void _internal_set_lmequipmentid(const std::string& value);
  std::string* _internal_mutable_lmequipmentid();
  public:

  // @@protoc_insertion_point(class_scope:Proto.LmComparatorSet)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::Comparator > comparator_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr lmequipmentid_;
  friend struct ::TableStruct_Comparator_2eproto;
};
// -------------------------------------------------------------------

class ComparatorSet PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.ComparatorSet) */ {
 public:
  inline ComparatorSet() : ComparatorSet(nullptr) {}
  virtual ~ComparatorSet();
  explicit constexpr ComparatorSet(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ComparatorSet(const ComparatorSet& from);
  ComparatorSet(ComparatorSet&& from) noexcept
    : ComparatorSet() {
    *this = ::std::move(from);
  }

  inline ComparatorSet& operator=(const ComparatorSet& from) {
    CopyFrom(from);
    return *this;
  }
  inline ComparatorSet& operator=(ComparatorSet&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ComparatorSet& default_instance() {
    return *internal_default_instance();
  }
  static inline const ComparatorSet* internal_default_instance() {
    return reinterpret_cast<const ComparatorSet*>(
               &_ComparatorSet_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ComparatorSet& a, ComparatorSet& b) {
    a.Swap(&b);
  }
  inline void Swap(ComparatorSet* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ComparatorSet* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ComparatorSet* New() const final {
    return CreateMaybeMessage<ComparatorSet>(nullptr);
  }

  ComparatorSet* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ComparatorSet>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ComparatorSet& from);
  void MergeFrom(const ComparatorSet& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ComparatorSet* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.ComparatorSet";
  }
  protected:
  explicit ComparatorSet(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_Comparator_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLmComparatorSetFieldNumber = 1,
  };
  // repeated .Proto.LmComparatorSet lmComparatorSet = 1;
  int lmcomparatorset_size() const;
  private:
  int _internal_lmcomparatorset_size() const;
  public:
  void clear_lmcomparatorset();
  ::Proto::LmComparatorSet* mutable_lmcomparatorset(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::LmComparatorSet >*
      mutable_lmcomparatorset();
  private:
  const ::Proto::LmComparatorSet& _internal_lmcomparatorset(int index) const;
  ::Proto::LmComparatorSet* _internal_add_lmcomparatorset();
  public:
  const ::Proto::LmComparatorSet& lmcomparatorset(int index) const;
  ::Proto::LmComparatorSet* add_lmcomparatorset();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::LmComparatorSet >&
      lmcomparatorset() const;

  // @@protoc_insertion_point(class_scope:Proto.ComparatorSet)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::LmComparatorSet > lmcomparatorset_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Comparator_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ComparatorSignal

// optional bool isConst = 1 [default = true];
inline bool ComparatorSignal::_internal_has_isconst() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool ComparatorSignal::has_isconst() const {
  return _internal_has_isconst();
}
inline void ComparatorSignal::clear_isconst() {
  isconst_ = true;
  _has_bits_[0] &= ~0x00000008u;
}
inline bool ComparatorSignal::_internal_isconst() const {
  return isconst_;
}
inline bool ComparatorSignal::isconst() const {
  // @@protoc_insertion_point(field_get:Proto.ComparatorSignal.isConst)
  return _internal_isconst();
}
inline void ComparatorSignal::_internal_set_isconst(bool value) {
  _has_bits_[0] |= 0x00000008u;
  isconst_ = value;
}
inline void ComparatorSignal::set_isconst(bool value) {
  _internal_set_isconst(value);
  // @@protoc_insertion_point(field_set:Proto.ComparatorSignal.isConst)
}

// optional double constValue = 2 [default = 0];
inline bool ComparatorSignal::_internal_has_constvalue() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool ComparatorSignal::has_constvalue() const {
  return _internal_has_constvalue();
}
inline void ComparatorSignal::clear_constvalue() {
  constvalue_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline double ComparatorSignal::_internal_constvalue() const {
  return constvalue_;
}
inline double ComparatorSignal::constvalue() const {
  // @@protoc_insertion_point(field_get:Proto.ComparatorSignal.constValue)
  return _internal_constvalue();
}
inline void ComparatorSignal::_internal_set_constvalue(double value) {
  _has_bits_[0] |= 0x00000002u;
  constvalue_ = value;
}
inline void ComparatorSignal::set_constvalue(double value) {
  _internal_set_constvalue(value);
  // @@protoc_insertion_point(field_set:Proto.ComparatorSignal.constValue)
}

// optional string appSignalId = 3;
inline bool ComparatorSignal::_internal_has_appsignalid() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ComparatorSignal::has_appsignalid() const {
  return _internal_has_appsignalid();
}
inline void ComparatorSignal::clear_appsignalid() {
  appsignalid_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ComparatorSignal::appsignalid() const {
  // @@protoc_insertion_point(field_get:Proto.ComparatorSignal.appSignalId)
  return _internal_appsignalid();
}
inline void ComparatorSignal::set_appsignalid(const std::string& value) {
  _internal_set_appsignalid(value);
  // @@protoc_insertion_point(field_set:Proto.ComparatorSignal.appSignalId)
}
inline std::string* ComparatorSignal::mutable_appsignalid() {
  // @@protoc_insertion_point(field_mutable:Proto.ComparatorSignal.appSignalId)
  return _internal_mutable_appsignalid();
}
inline const std::string& ComparatorSignal::_internal_appsignalid() const {
  return appsignalid_.Get();
}
inline void ComparatorSignal::_internal_set_appsignalid(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  appsignalid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ComparatorSignal::set_appsignalid(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  appsignalid_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:Proto.ComparatorSignal.appSignalId)
}
inline void ComparatorSignal::set_appsignalid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  appsignalid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:Proto.ComparatorSignal.appSignalId)
}
inline void ComparatorSignal::set_appsignalid(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  appsignalid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:Proto.ComparatorSignal.appSignalId)
}
inline std::string* ComparatorSignal::_internal_mutable_appsignalid() {
  _has_bits_[0] |= 0x00000001u;
  return appsignalid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ComparatorSignal::release_appsignalid() {
  // @@protoc_insertion_point(field_release:Proto.ComparatorSignal.appSignalId)
  if (!_internal_has_appsignalid()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return appsignalid_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ComparatorSignal::set_allocated_appsignalid(std::string* appsignalid) {
  if (appsignalid != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  appsignalid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), appsignalid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:Proto.ComparatorSignal.appSignalId)
}

// optional bool isAcquired = 4 [default = false];
inline bool ComparatorSignal::_internal_has_isacquired() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool ComparatorSignal::has_isacquired() const {
  return _internal_has_isacquired();
}
inline void ComparatorSignal::clear_isacquired() {
  isacquired_ = false;
  _has_bits_[0] &= ~0x00000004u;
}
inline bool ComparatorSignal::_internal_isacquired() const {
  return isacquired_;
}
inline bool ComparatorSignal::isacquired() const {
  // @@protoc_insertion_point(field_get:Proto.ComparatorSignal.isAcquired)
  return _internal_isacquired();
}
inline void ComparatorSignal::_internal_set_isacquired(bool value) {
  _has_bits_[0] |= 0x00000004u;
  isacquired_ = value;
}
inline void ComparatorSignal::set_isacquired(bool value) {
  _internal_set_isacquired(value);
  // @@protoc_insertion_point(field_set:Proto.ComparatorSignal.isAcquired)
}

// -------------------------------------------------------------------

// Comparator

// optional int32 cmpType = 1 [default = 1];
inline bool Comparator::_internal_has_cmptype() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool Comparator::has_cmptype() const {
  return _internal_has_cmptype();
}
inline void Comparator::clear_cmptype() {
  cmptype_ = 1;
  _has_bits_[0] &= ~0x00000200u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Comparator::_internal_cmptype() const {
  return cmptype_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Comparator::cmptype() const {
  // @@protoc_insertion_point(field_get:Proto.Comparator.cmpType)
  return _internal_cmptype();
}
inline void Comparator::_internal_set_cmptype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000200u;
  cmptype_ = value;
}
inline void Comparator::set_cmptype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_cmptype(value);
  // @@protoc_insertion_point(field_set:Proto.Comparator.cmpType)
}

// optional int32 inAnalogSignalFormat = 2 [default = 1];
inline bool Comparator::_internal_has_inanalogsignalformat() const {
  bool value = (_has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline bool Comparator::has_inanalogsignalformat() const {
  return _internal_has_inanalogsignalformat();
}
inline void Comparator::clear_inanalogsignalformat() {
  inanalogsignalformat_ = 1;
  _has_bits_[0] &= ~0x00000400u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Comparator::_internal_inanalogsignalformat() const {
  return inanalogsignalformat_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Comparator::inanalogsignalformat() const {
  // @@protoc_insertion_point(field_get:Proto.Comparator.inAnalogSignalFormat)
  return _internal_inanalogsignalformat();
}
inline void Comparator::_internal_set_inanalogsignalformat(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000400u;
  inanalogsignalformat_ = value;
}
inline void Comparator::set_inanalogsignalformat(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_inanalogsignalformat(value);
  // @@protoc_insertion_point(field_set:Proto.Comparator.inAnalogSignalFormat)
}

// optional .Proto.ComparatorSignal input = 3;
inline bool Comparator::_internal_has_input() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || input_ != nullptr);
  return value;
}
inline bool Comparator::has_input() const {
  return _internal_has_input();
}
inline void Comparator::clear_input() {
  if (input_ != nullptr) input_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
inline const ::Proto::ComparatorSignal& Comparator::_internal_input() const {
  const ::Proto::ComparatorSignal* p = input_;
  return p != nullptr ? *p : reinterpret_cast<const ::Proto::ComparatorSignal&>(
      ::Proto::_ComparatorSignal_default_instance_);
}
inline const ::Proto::ComparatorSignal& Comparator::input() const {
  // @@protoc_insertion_point(field_get:Proto.Comparator.input)
  return _internal_input();
}
inline void Comparator::unsafe_arena_set_allocated_input(
    ::Proto::ComparatorSignal* input) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(input_);
  }
  input_ = input;
  if (input) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.Comparator.input)
}
inline ::Proto::ComparatorSignal* Comparator::release_input() {
  _has_bits_[0] &= ~0x00000004u;
  ::Proto::ComparatorSignal* temp = input_;
  input_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Proto::ComparatorSignal* Comparator::unsafe_arena_release_input() {
  // @@protoc_insertion_point(field_release:Proto.Comparator.input)
  _has_bits_[0] &= ~0x00000004u;
  ::Proto::ComparatorSignal* temp = input_;
  input_ = nullptr;
  return temp;
}
inline ::Proto::ComparatorSignal* Comparator::_internal_mutable_input() {
  _has_bits_[0] |= 0x00000004u;
  if (input_ == nullptr) {
    auto* p = CreateMaybeMessage<::Proto::ComparatorSignal>(GetArena());
    input_ = p;
  }
  return input_;
}
inline ::Proto::ComparatorSignal* Comparator::mutable_input() {
  // @@protoc_insertion_point(field_mutable:Proto.Comparator.input)
  return _internal_mutable_input();
}
inline void Comparator::set_allocated_input(::Proto::ComparatorSignal* input) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete input_;
  }
  if (input) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(input);
    if (message_arena != submessage_arena) {
      input = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, input, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  input_ = input;
  // @@protoc_insertion_point(field_set_allocated:Proto.Comparator.input)
}

// optional .Proto.ComparatorSignal compare = 4;
inline bool Comparator::_internal_has_compare() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || compare_ != nullptr);
  return value;
}
inline bool Comparator::has_compare() const {
  return _internal_has_compare();
}
inline void Comparator::clear_compare() {
  if (compare_ != nullptr) compare_->Clear();
  _has_bits_[0] &= ~0x00000008u;
}
inline const ::Proto::ComparatorSignal& Comparator::_internal_compare() const {
  const ::Proto::ComparatorSignal* p = compare_;
  return p != nullptr ? *p : reinterpret_cast<const ::Proto::ComparatorSignal&>(
      ::Proto::_ComparatorSignal_default_instance_);
}
inline const ::Proto::ComparatorSignal& Comparator::compare() const {
  // @@protoc_insertion_point(field_get:Proto.Comparator.compare)
  return _internal_compare();
}
inline void Comparator::unsafe_arena_set_allocated_compare(
    ::Proto::ComparatorSignal* compare) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(compare_);
  }
  compare_ = compare;
  if (compare) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.Comparator.compare)
}
inline ::Proto::ComparatorSignal* Comparator::release_compare() {
  _has_bits_[0] &= ~0x00000008u;
  ::Proto::ComparatorSignal* temp = compare_;
  compare_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Proto::ComparatorSignal* Comparator::unsafe_arena_release_compare() {
  // @@protoc_insertion_point(field_release:Proto.Comparator.compare)
  _has_bits_[0] &= ~0x00000008u;
  ::Proto::ComparatorSignal* temp = compare_;
  compare_ = nullptr;
  return temp;
}
inline ::Proto::ComparatorSignal* Comparator::_internal_mutable_compare() {
  _has_bits_[0] |= 0x00000008u;
  if (compare_ == nullptr) {
    auto* p = CreateMaybeMessage<::Proto::ComparatorSignal>(GetArena());
    compare_ = p;
  }
  return compare_;
}
inline ::Proto::ComparatorSignal* Comparator::mutable_compare() {
  // @@protoc_insertion_point(field_mutable:Proto.Comparator.compare)
  return _internal_mutable_compare();
}
inline void Comparator::set_allocated_compare(::Proto::ComparatorSignal* compare) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete compare_;
  }
  if (compare) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(compare);
    if (message_arena != submessage_arena) {
      compare = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, compare, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  compare_ = compare;
  // @@protoc_insertion_point(field_set_allocated:Proto.Comparator.compare)
}

// optional .Proto.ComparatorSignal hysteresis = 5;
inline bool Comparator::_internal_has_hysteresis() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  PROTOBUF_ASSUME(!value || hysteresis_ != nullptr);
  return value;
}
inline bool Comparator::has_hysteresis() const {
  return _internal_has_hysteresis();
}
inline void Comparator::clear_hysteresis() {
  if (hysteresis_ != nullptr) hysteresis_->Clear();
  _has_bits_[0] &= ~0x00000010u;
}
inline const ::Proto::ComparatorSignal& Comparator::_internal_hysteresis() const {
  const ::Proto::ComparatorSignal* p = hysteresis_;
  return p != nullptr ? *p : reinterpret_cast<const ::Proto::ComparatorSignal&>(
      ::Proto::_ComparatorSignal_default_instance_);
}
inline const ::Proto::ComparatorSignal& Comparator::hysteresis() const {
  // @@protoc_insertion_point(field_get:Proto.Comparator.hysteresis)
  return _internal_hysteresis();
}
inline void Comparator::unsafe_arena_set_allocated_hysteresis(
    ::Proto::ComparatorSignal* hysteresis) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(hysteresis_);
  }
  hysteresis_ = hysteresis;
  if (hysteresis) {
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.Comparator.hysteresis)
}
inline ::Proto::ComparatorSignal* Comparator::release_hysteresis() {
  _has_bits_[0] &= ~0x00000010u;
  ::Proto::ComparatorSignal* temp = hysteresis_;
  hysteresis_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Proto::ComparatorSignal* Comparator::unsafe_arena_release_hysteresis() {
  // @@protoc_insertion_point(field_release:Proto.Comparator.hysteresis)
  _has_bits_[0] &= ~0x00000010u;
  ::Proto::ComparatorSignal* temp = hysteresis_;
  hysteresis_ = nullptr;
  return temp;
}
inline ::Proto::ComparatorSignal* Comparator::_internal_mutable_hysteresis() {
  _has_bits_[0] |= 0x00000010u;
  if (hysteresis_ == nullptr) {
    auto* p = CreateMaybeMessage<::Proto::ComparatorSignal>(GetArena());
    hysteresis_ = p;
  }
  return hysteresis_;
}
inline ::Proto::ComparatorSignal* Comparator::mutable_hysteresis() {
  // @@protoc_insertion_point(field_mutable:Proto.Comparator.hysteresis)
  return _internal_mutable_hysteresis();
}
inline void Comparator::set_allocated_hysteresis(::Proto::ComparatorSignal* hysteresis) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete hysteresis_;
  }
  if (hysteresis) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(hysteresis);
    if (message_arena != submessage_arena) {
      hysteresis = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, hysteresis, submessage_arena);
    }
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  hysteresis_ = hysteresis;
  // @@protoc_insertion_point(field_set_allocated:Proto.Comparator.hysteresis)
}

// optional .Proto.ComparatorSignal output = 6;
inline bool Comparator::_internal_has_output() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  PROTOBUF_ASSUME(!value || output_ != nullptr);
  return value;
}
inline bool Comparator::has_output() const {
  return _internal_has_output();
}
inline void Comparator::clear_output() {
  if (output_ != nullptr) output_->Clear();
  _has_bits_[0] &= ~0x00000020u;
}
inline const ::Proto::ComparatorSignal& Comparator::_internal_output() const {
  const ::Proto::ComparatorSignal* p = output_;
  return p != nullptr ? *p : reinterpret_cast<const ::Proto::ComparatorSignal&>(
      ::Proto::_ComparatorSignal_default_instance_);
}
inline const ::Proto::ComparatorSignal& Comparator::output() const {
  // @@protoc_insertion_point(field_get:Proto.Comparator.output)
  return _internal_output();
}
inline void Comparator::unsafe_arena_set_allocated_output(
    ::Proto::ComparatorSignal* output) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(output_);
  }
  output_ = output;
  if (output) {
    _has_bits_[0] |= 0x00000020u;
  } else {
    _has_bits_[0] &= ~0x00000020u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.Comparator.output)
}
inline ::Proto::ComparatorSignal* Comparator::release_output() {
  _has_bits_[0] &= ~0x00000020u;
  ::Proto::ComparatorSignal* temp = output_;
  output_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Proto::ComparatorSignal* Comparator::unsafe_arena_release_output() {
  // @@protoc_insertion_point(field_release:Proto.Comparator.output)
  _has_bits_[0] &= ~0x00000020u;
  ::Proto::ComparatorSignal* temp = output_;
  output_ = nullptr;
  return temp;
}
inline ::Proto::ComparatorSignal* Comparator::_internal_mutable_output() {
  _has_bits_[0] |= 0x00000020u;
  if (output_ == nullptr) {
    auto* p = CreateMaybeMessage<::Proto::ComparatorSignal>(GetArena());
    output_ = p;
  }
  return output_;
}
inline ::Proto::ComparatorSignal* Comparator::mutable_output() {
  // @@protoc_insertion_point(field_mutable:Proto.Comparator.output)
  return _internal_mutable_output();
}
inline void Comparator::set_allocated_output(::Proto::ComparatorSignal* output) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete output_;
  }
  if (output) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(output);
    if (message_arena != submessage_arena) {
      output = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, output, submessage_arena);
    }
    _has_bits_[0] |= 0x00000020u;
  } else {
    _has_bits_[0] &= ~0x00000020u;
  }
  output_ = output;
  // @@protoc_insertion_point(field_set_allocated:Proto.Comparator.output)
}

// optional bool allSignalsIsAcquired = 7 [default = false];
inline bool Comparator::_internal_has_allsignalsisacquired() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool Comparator::has_allsignalsisacquired() const {
  return _internal_has_allsignalsisacquired();
}
inline void Comparator::clear_allsignalsisacquired() {
  allsignalsisacquired_ = false;
  _has_bits_[0] &= ~0x00000080u;
}
inline bool Comparator::_internal_allsignalsisacquired() const {
  return allsignalsisacquired_;
}
inline bool Comparator::allsignalsisacquired() const {
  // @@protoc_insertion_point(field_get:Proto.Comparator.allSignalsIsAcquired)
  return _internal_allsignalsisacquired();
}
inline void Comparator::_internal_set_allsignalsisacquired(bool value) {
  _has_bits_[0] |= 0x00000080u;
  allsignalsisacquired_ = value;
}
inline void Comparator::set_allsignalsisacquired(bool value) {
  _internal_set_allsignalsisacquired(value);
  // @@protoc_insertion_point(field_set:Proto.Comparator.allSignalsIsAcquired)
}

// optional int32 precision = 8 [default = 2];
inline bool Comparator::_internal_has_precision() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool Comparator::has_precision() const {
  return _internal_has_precision();
}
inline void Comparator::clear_precision() {
  precision_ = 2;
  _has_bits_[0] &= ~0x00000100u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Comparator::_internal_precision() const {
  return precision_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Comparator::precision() const {
  // @@protoc_insertion_point(field_get:Proto.Comparator.precision)
  return _internal_precision();
}
inline void Comparator::_internal_set_precision(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000100u;
  precision_ = value;
}
inline void Comparator::set_precision(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_precision(value);
  // @@protoc_insertion_point(field_set:Proto.Comparator.precision)
}

// optional string label = 9;
inline bool Comparator::_internal_has_label() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Comparator::has_label() const {
  return _internal_has_label();
}
inline void Comparator::clear_label() {
  label_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Comparator::label() const {
  // @@protoc_insertion_point(field_get:Proto.Comparator.label)
  return _internal_label();
}
inline void Comparator::set_label(const std::string& value) {
  _internal_set_label(value);
  // @@protoc_insertion_point(field_set:Proto.Comparator.label)
}
inline std::string* Comparator::mutable_label() {
  // @@protoc_insertion_point(field_mutable:Proto.Comparator.label)
  return _internal_mutable_label();
}
inline const std::string& Comparator::_internal_label() const {
  return label_.Get();
}
inline void Comparator::_internal_set_label(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  label_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Comparator::set_label(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  label_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:Proto.Comparator.label)
}
inline void Comparator::set_label(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  label_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:Proto.Comparator.label)
}
inline void Comparator::set_label(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  label_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:Proto.Comparator.label)
}
inline std::string* Comparator::_internal_mutable_label() {
  _has_bits_[0] |= 0x00000001u;
  return label_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Comparator::release_label() {
  // @@protoc_insertion_point(field_release:Proto.Comparator.label)
  if (!_internal_has_label()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return label_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Comparator::set_allocated_label(std::string* label) {
  if (label != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  label_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), label,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:Proto.Comparator.label)
}

// optional string schemaId = 10;
inline bool Comparator::_internal_has_schemaid() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Comparator::has_schemaid() const {
  return _internal_has_schemaid();
}
inline void Comparator::clear_schemaid() {
  schemaid_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Comparator::schemaid() const {
  // @@protoc_insertion_point(field_get:Proto.Comparator.schemaId)
  return _internal_schemaid();
}
inline void Comparator::set_schemaid(const std::string& value) {
  _internal_set_schemaid(value);
  // @@protoc_insertion_point(field_set:Proto.Comparator.schemaId)
}
inline std::string* Comparator::mutable_schemaid() {
  // @@protoc_insertion_point(field_mutable:Proto.Comparator.schemaId)
  return _internal_mutable_schemaid();
}
inline const std::string& Comparator::_internal_schemaid() const {
  return schemaid_.Get();
}
inline void Comparator::_internal_set_schemaid(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  schemaid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Comparator::set_schemaid(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  schemaid_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:Proto.Comparator.schemaId)
}
inline void Comparator::set_schemaid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  schemaid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:Proto.Comparator.schemaId)
}
inline void Comparator::set_schemaid(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  schemaid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:Proto.Comparator.schemaId)
}
inline std::string* Comparator::_internal_mutable_schemaid() {
  _has_bits_[0] |= 0x00000002u;
  return schemaid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Comparator::release_schemaid() {
  // @@protoc_insertion_point(field_release:Proto.Comparator.schemaId)
  if (!_internal_has_schemaid()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return schemaid_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Comparator::set_allocated_schemaid(std::string* schemaid) {
  if (schemaid != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  schemaid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), schemaid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:Proto.Comparator.schemaId)
}

// optional .Proto.Uuid schemaItemUuid = 11;
inline bool Comparator::_internal_has_schemaitemuuid() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  PROTOBUF_ASSUME(!value || schemaitemuuid_ != nullptr);
  return value;
}
inline bool Comparator::has_schemaitemuuid() const {
  return _internal_has_schemaitemuuid();
}
inline const ::Proto::Uuid& Comparator::_internal_schemaitemuuid() const {
  const ::Proto::Uuid* p = schemaitemuuid_;
  return p != nullptr ? *p : reinterpret_cast<const ::Proto::Uuid&>(
      ::Proto::_Uuid_default_instance_);
}
inline const ::Proto::Uuid& Comparator::schemaitemuuid() const {
  // @@protoc_insertion_point(field_get:Proto.Comparator.schemaItemUuid)
  return _internal_schemaitemuuid();
}
inline void Comparator::unsafe_arena_set_allocated_schemaitemuuid(
    ::Proto::Uuid* schemaitemuuid) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(schemaitemuuid_);
  }
  schemaitemuuid_ = schemaitemuuid;
  if (schemaitemuuid) {
    _has_bits_[0] |= 0x00000040u;
  } else {
    _has_bits_[0] &= ~0x00000040u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.Comparator.schemaItemUuid)
}
inline ::Proto::Uuid* Comparator::release_schemaitemuuid() {
  _has_bits_[0] &= ~0x00000040u;
  ::Proto::Uuid* temp = schemaitemuuid_;
  schemaitemuuid_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Proto::Uuid* Comparator::unsafe_arena_release_schemaitemuuid() {
  // @@protoc_insertion_point(field_release:Proto.Comparator.schemaItemUuid)
  _has_bits_[0] &= ~0x00000040u;
  ::Proto::Uuid* temp = schemaitemuuid_;
  schemaitemuuid_ = nullptr;
  return temp;
}
inline ::Proto::Uuid* Comparator::_internal_mutable_schemaitemuuid() {
  _has_bits_[0] |= 0x00000040u;
  if (schemaitemuuid_ == nullptr) {
    auto* p = CreateMaybeMessage<::Proto::Uuid>(GetArena());
    schemaitemuuid_ = p;
  }
  return schemaitemuuid_;
}
inline ::Proto::Uuid* Comparator::mutable_schemaitemuuid() {
  // @@protoc_insertion_point(field_mutable:Proto.Comparator.schemaItemUuid)
  return _internal_mutable_schemaitemuuid();
}
inline void Comparator::set_allocated_schemaitemuuid(::Proto::Uuid* schemaitemuuid) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(schemaitemuuid_);
  }
  if (schemaitemuuid) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(schemaitemuuid)->GetArena();
    if (message_arena != submessage_arena) {
      schemaitemuuid = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, schemaitemuuid, submessage_arena);
    }
    _has_bits_[0] |= 0x00000040u;
  } else {
    _has_bits_[0] &= ~0x00000040u;
  }
  schemaitemuuid_ = schemaitemuuid;
  // @@protoc_insertion_point(field_set_allocated:Proto.Comparator.schemaItemUuid)
}

// -------------------------------------------------------------------

// LmComparatorSet

// optional string lmEquipmentID = 1;
inline bool LmComparatorSet::_internal_has_lmequipmentid() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool LmComparatorSet::has_lmequipmentid() const {
  return _internal_has_lmequipmentid();
}
inline void LmComparatorSet::clear_lmequipmentid() {
  lmequipmentid_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& LmComparatorSet::lmequipmentid() const {
  // @@protoc_insertion_point(field_get:Proto.LmComparatorSet.lmEquipmentID)
  return _internal_lmequipmentid();
}
inline void LmComparatorSet::set_lmequipmentid(const std::string& value) {
  _internal_set_lmequipmentid(value);
  // @@protoc_insertion_point(field_set:Proto.LmComparatorSet.lmEquipmentID)
}
inline std::string* LmComparatorSet::mutable_lmequipmentid() {
  // @@protoc_insertion_point(field_mutable:Proto.LmComparatorSet.lmEquipmentID)
  return _internal_mutable_lmequipmentid();
}
inline const std::string& LmComparatorSet::_internal_lmequipmentid() const {
  return lmequipmentid_.Get();
}
inline void LmComparatorSet::_internal_set_lmequipmentid(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  lmequipmentid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void LmComparatorSet::set_lmequipmentid(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  lmequipmentid_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:Proto.LmComparatorSet.lmEquipmentID)
}
inline void LmComparatorSet::set_lmequipmentid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  lmequipmentid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:Proto.LmComparatorSet.lmEquipmentID)
}
inline void LmComparatorSet::set_lmequipmentid(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  lmequipmentid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:Proto.LmComparatorSet.lmEquipmentID)
}
inline std::string* LmComparatorSet::_internal_mutable_lmequipmentid() {
  _has_bits_[0] |= 0x00000001u;
  return lmequipmentid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* LmComparatorSet::release_lmequipmentid() {
  // @@protoc_insertion_point(field_release:Proto.LmComparatorSet.lmEquipmentID)
  if (!_internal_has_lmequipmentid()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return lmequipmentid_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LmComparatorSet::set_allocated_lmequipmentid(std::string* lmequipmentid) {
  if (lmequipmentid != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  lmequipmentid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), lmequipmentid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:Proto.LmComparatorSet.lmEquipmentID)
}

// repeated .Proto.Comparator comparator = 2;
inline int LmComparatorSet::_internal_comparator_size() const {
  return comparator_.size();
}
inline int LmComparatorSet::comparator_size() const {
  return _internal_comparator_size();
}
inline void LmComparatorSet::clear_comparator() {
  comparator_.Clear();
}
inline ::Proto::Comparator* LmComparatorSet::mutable_comparator(int index) {
  // @@protoc_insertion_point(field_mutable:Proto.LmComparatorSet.comparator)
  return comparator_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::Comparator >*
LmComparatorSet::mutable_comparator() {
  // @@protoc_insertion_point(field_mutable_list:Proto.LmComparatorSet.comparator)
  return &comparator_;
}
inline const ::Proto::Comparator& LmComparatorSet::_internal_comparator(int index) const {
  return comparator_.Get(index);
}
inline const ::Proto::Comparator& LmComparatorSet::comparator(int index) const {
  // @@protoc_insertion_point(field_get:Proto.LmComparatorSet.comparator)
  return _internal_comparator(index);
}
inline ::Proto::Comparator* LmComparatorSet::_internal_add_comparator() {
  return comparator_.Add();
}
inline ::Proto::Comparator* LmComparatorSet::add_comparator() {
  // @@protoc_insertion_point(field_add:Proto.LmComparatorSet.comparator)
  return _internal_add_comparator();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::Comparator >&
LmComparatorSet::comparator() const {
  // @@protoc_insertion_point(field_list:Proto.LmComparatorSet.comparator)
  return comparator_;
}

// -------------------------------------------------------------------

// ComparatorSet

// repeated .Proto.LmComparatorSet lmComparatorSet = 1;
inline int ComparatorSet::_internal_lmcomparatorset_size() const {
  return lmcomparatorset_.size();
}
inline int ComparatorSet::lmcomparatorset_size() const {
  return _internal_lmcomparatorset_size();
}
inline void ComparatorSet::clear_lmcomparatorset() {
  lmcomparatorset_.Clear();
}
inline ::Proto::LmComparatorSet* ComparatorSet::mutable_lmcomparatorset(int index) {
  // @@protoc_insertion_point(field_mutable:Proto.ComparatorSet.lmComparatorSet)
  return lmcomparatorset_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::LmComparatorSet >*
ComparatorSet::mutable_lmcomparatorset() {
  // @@protoc_insertion_point(field_mutable_list:Proto.ComparatorSet.lmComparatorSet)
  return &lmcomparatorset_;
}
inline const ::Proto::LmComparatorSet& ComparatorSet::_internal_lmcomparatorset(int index) const {
  return lmcomparatorset_.Get(index);
}
inline const ::Proto::LmComparatorSet& ComparatorSet::lmcomparatorset(int index) const {
  // @@protoc_insertion_point(field_get:Proto.ComparatorSet.lmComparatorSet)
  return _internal_lmcomparatorset(index);
}
inline ::Proto::LmComparatorSet* ComparatorSet::_internal_add_lmcomparatorset() {
  return lmcomparatorset_.Add();
}
inline ::Proto::LmComparatorSet* ComparatorSet::add_lmcomparatorset() {
  // @@protoc_insertion_point(field_add:Proto.ComparatorSet.lmComparatorSet)
  return _internal_add_lmcomparatorset();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::LmComparatorSet >&
ComparatorSet::lmcomparatorset() const {
  // @@protoc_insertion_point(field_list:Proto.ComparatorSet.lmComparatorSet)
  return lmcomparatorset_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Comparator_2eproto
