syntax = "proto2";

package Proto;

import "Common.proto";

//
// Comparator
//
message ComparatorSignal
{
    optional bool isConst = 1 [default = true];
	optional double constValue = 2 [default = 0.0];
	optional string appSignalId = 3;
	optional bool isAcquired = 4 [default = false];
}

message Comparator
{
    optional int32 cmpType = 1 [default = 1];				// Comparator::CmpType::Equ;

    optional int32 inAnalogSignalFormat = 2 [default = 1];	// E::AnalogSignalFormat::SignedInt32

    optional ComparatorSignal input = 3;
	optional ComparatorSignal compare = 4;
	optional ComparatorSignal hysteresis = 5;
	optional ComparatorSignal output = 6;

    optional bool allSignalsIsAcquired = 7 [default = false];

    optional int32 precision = 8 [default = 2];
	optional string label = 9;
	optional string schemaId = 10;
	optional Uuid schemaItemUuid = 11;
}

message LmComparatorSet
{
    optional string lmEquipmentID = 1;
	repeated Comparator comparator = 2;
}

message ComparatorSet
{
    repeated LmComparatorSet lmComparatorSet = 1;
}


