#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable : 4100)
#pragma warning(disable : 4244)
#pragma warning(disable : 4125)
#pragma warning(disable : 4127)
#pragma warning(disable : 4267)
#pragma warning(disable : 4512)
#pragma warning(disable : 4996)
#pragma warning(disable : 6011)
#pragma warning(disable : 6326)
#pragma warning(disable : 6385)
#pragma warning(disable : 6387)
#endif
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Envelope.proto

#include "Envelope.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace Proto {
constexpr Envelope::Envelope(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : compressedobject_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , classnamehash_(0u){}
struct EnvelopeDefaultTypeInternal {
  constexpr EnvelopeDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~EnvelopeDefaultTypeInternal() {}
  union {
    Envelope _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT EnvelopeDefaultTypeInternal _Envelope_default_instance_;
constexpr EnvelopeSet::EnvelopeSet(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : items_(){}
struct EnvelopeSetDefaultTypeInternal {
  constexpr EnvelopeSetDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~EnvelopeSetDefaultTypeInternal() {}
  union {
    EnvelopeSet _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT EnvelopeSetDefaultTypeInternal _EnvelopeSet_default_instance_;
constexpr EnvelopeSetShortDescription::EnvelopeSetShortDescription(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : classnamehash_()
  , devicetype_()
  , projectname_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , username_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , projectdbversion_(0u)
  , equipmenteditor_(false)
  , preseteditor_(false)
  , presetroot_(false)
  , exporttime_(PROTOBUF_ULONGLONG(0)){}
struct EnvelopeSetShortDescriptionDefaultTypeInternal {
  constexpr EnvelopeSetShortDescriptionDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~EnvelopeSetShortDescriptionDefaultTypeInternal() {}
  union {
    EnvelopeSetShortDescription _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT EnvelopeSetShortDescriptionDefaultTypeInternal _EnvelopeSetShortDescription_default_instance_;
constexpr ExportedDevicePreset2::ExportedDevicePreset2(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : compressedthis_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , description_(nullptr)
  , items_(nullptr){}
struct ExportedDevicePreset2DefaultTypeInternal {
  constexpr ExportedDevicePreset2DefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ExportedDevicePreset2DefaultTypeInternal() {}
  union {
    ExportedDevicePreset2 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ExportedDevicePreset2DefaultTypeInternal _ExportedDevicePreset2_default_instance_;
}  // namespace Proto
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_Envelope_2eproto[4];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_Envelope_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Envelope_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_Envelope_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::Proto::Envelope, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::Proto::Envelope, _internal_metadata_),
  PROTOBUF_FIELD_OFFSET(::Proto::Envelope, _extensions_),
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Proto::Envelope, classnamehash_),
  PROTOBUF_FIELD_OFFSET(::Proto::Envelope, compressedobject_),
  1,
  0,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Proto::EnvelopeSet, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Proto::EnvelopeSet, items_),
  PROTOBUF_FIELD_OFFSET(::Proto::EnvelopeSetShortDescription, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::Proto::EnvelopeSetShortDescription, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Proto::EnvelopeSetShortDescription, projectdbversion_),
  PROTOBUF_FIELD_OFFSET(::Proto::EnvelopeSetShortDescription, classnamehash_),
  PROTOBUF_FIELD_OFFSET(::Proto::EnvelopeSetShortDescription, devicetype_),
  PROTOBUF_FIELD_OFFSET(::Proto::EnvelopeSetShortDescription, equipmenteditor_),
  PROTOBUF_FIELD_OFFSET(::Proto::EnvelopeSetShortDescription, preseteditor_),
  PROTOBUF_FIELD_OFFSET(::Proto::EnvelopeSetShortDescription, presetroot_),
  PROTOBUF_FIELD_OFFSET(::Proto::EnvelopeSetShortDescription, projectname_),
  PROTOBUF_FIELD_OFFSET(::Proto::EnvelopeSetShortDescription, username_),
  PROTOBUF_FIELD_OFFSET(::Proto::EnvelopeSetShortDescription, exporttime_),
  2,
  ~0u,
  ~0u,
  3,
  4,
  5,
  0,
  1,
  6,
  PROTOBUF_FIELD_OFFSET(::Proto::ExportedDevicePreset2, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::Proto::ExportedDevicePreset2, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Proto::ExportedDevicePreset2, description_),
  PROTOBUF_FIELD_OFFSET(::Proto::ExportedDevicePreset2, items_),
  PROTOBUF_FIELD_OFFSET(::Proto::ExportedDevicePreset2, compressedthis_),
  1,
  2,
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::Proto::Envelope)},
  { 9, -1, sizeof(::Proto::EnvelopeSet)},
  { 15, 29, sizeof(::Proto::EnvelopeSetShortDescription)},
  { 38, 46, sizeof(::Proto::ExportedDevicePreset2)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Proto::_Envelope_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Proto::_EnvelopeSet_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Proto::_EnvelopeSetShortDescription_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Proto::_ExportedDevicePreset2_default_instance_),
};

const char descriptor_table_protodef_Envelope_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016Envelope.proto\022\005Proto\"B\n\010Envelope\022\025\n\rc"
  "lassnamehash\030\001 \002(\r\022\030\n\020compressedObject\030\002"
  " \001(\014*\005\010\006\020\364\003\"-\n\013EnvelopeSet\022\036\n\005items\030\001 \003("
  "\0132\017.Proto.Envelope\"\340\001\n\033EnvelopeSetShortD"
  "escription\022\030\n\020projectdbversion\030\001 \001(\r\022\025\n\r"
  "classnamehash\030\002 \003(\r\022\022\n\ndevicetype\030\n \003(\005\022"
  "\027\n\017equipmentEditor\030\003 \001(\010\022\024\n\014presetEditor"
  "\030\004 \001(\010\022\022\n\npresetRoot\030\005 \001(\010\022\023\n\013projectNam"
  "e\030\006 \001(\t\022\020\n\010userName\030\007 \001(\t\022\022\n\nexportTime\030"
  "\010 \001(\004\"\213\001\n\025ExportedDevicePreset2\0227\n\013descr"
  "iption\030\001 \001(\0132\".Proto.EnvelopeSetShortDes"
  "cription\022!\n\005items\030\002 \001(\0132\022.Proto.Envelope"
  "Set\022\026\n\016compressedThis\030\003 \001(\014"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Envelope_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Envelope_2eproto = {
  false, false, 507, descriptor_table_protodef_Envelope_2eproto, "Envelope.proto", 
  &descriptor_table_Envelope_2eproto_once, nullptr, 0, 4,
  schemas, file_default_instances, TableStruct_Envelope_2eproto::offsets,
  file_level_metadata_Envelope_2eproto, file_level_enum_descriptors_Envelope_2eproto, file_level_service_descriptors_Envelope_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_Envelope_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Envelope_2eproto);
  return descriptor_table_Envelope_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_Envelope_2eproto(&descriptor_table_Envelope_2eproto);
namespace Proto {

// ===================================================================

class Envelope::_Internal {
 public:
  using HasBits = decltype(std::declval<Envelope>()._has_bits_);
  static void set_has_classnamehash(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_compressedobject(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000002) ^ 0x00000002) != 0;
  }
};

Envelope::Envelope(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  _extensions_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Proto.Envelope)
}
Envelope::Envelope(const Envelope& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _extensions_.MergeFrom(from._extensions_);
  compressedobject_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_compressedobject()) {
    compressedobject_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_compressedobject(), 
      GetArena());
  }
  classnamehash_ = from.classnamehash_;
  // @@protoc_insertion_point(copy_constructor:Proto.Envelope)
}

void Envelope::SharedCtor() {
compressedobject_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
classnamehash_ = 0u;
}

Envelope::~Envelope() {
  // @@protoc_insertion_point(destructor:Proto.Envelope)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Envelope::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  compressedobject_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Envelope::ArenaDtor(void* object) {
  Envelope* _this = reinterpret_cast< Envelope* >(object);
  (void)_this;
}
void Envelope::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Envelope::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Envelope::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto.Envelope)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _extensions_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    compressedobject_.ClearNonDefaultToEmpty();
  }
  classnamehash_ = 0u;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Envelope::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required uint32 classnamehash = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_classnamehash(&has_bits);
          classnamehash_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bytes compressedObject = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_compressedobject();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
      if ((48u <= tag && tag < 4000u)) {
        ptr = _extensions_.ParseField(tag, ptr,
            internal_default_instance(), &_internal_metadata_, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Envelope::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Proto.Envelope)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint32 classnamehash = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_classnamehash(), target);
  }

  // optional bytes compressedObject = 2;
  if (cached_has_bits & 0x00000001u) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_compressedobject(), target);
  }

  // Extension range [6, 500)
  target = _extensions_._InternalSerialize(
      6, 500, target, stream);

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto.Envelope)
  return target;
}

size_t Envelope::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Proto.Envelope)
  size_t total_size = 0;

  total_size += _extensions_.ByteSize();

  // required uint32 classnamehash = 1;
  if (_internal_has_classnamehash()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_classnamehash());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional bytes compressedObject = 2;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_compressedobject());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Envelope::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Proto.Envelope)
  GOOGLE_DCHECK_NE(&from, this);
  const Envelope* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Envelope>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Proto.Envelope)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Proto.Envelope)
    MergeFrom(*source);
  }
}

void Envelope::MergeFrom(const Envelope& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Proto.Envelope)
  GOOGLE_DCHECK_NE(&from, this);
  _extensions_.MergeFrom(from._extensions_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_compressedobject(from._internal_compressedobject());
    }
    if (cached_has_bits & 0x00000002u) {
      classnamehash_ = from.classnamehash_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void Envelope::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Proto.Envelope)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Envelope::CopyFrom(const Envelope& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto.Envelope)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Envelope::IsInitialized() const {
  if (!_extensions_.IsInitialized()) {
    return false;
  }

  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  return true;
}

void Envelope::InternalSwap(Envelope* other) {
  using std::swap;
  _extensions_.Swap(&other->_extensions_);
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  compressedobject_.Swap(&other->compressedobject_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(classnamehash_, other->classnamehash_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Envelope::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class EnvelopeSet::_Internal {
 public:
};

EnvelopeSet::EnvelopeSet(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  items_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Proto.EnvelopeSet)
}
EnvelopeSet::EnvelopeSet(const EnvelopeSet& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      items_(from.items_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Proto.EnvelopeSet)
}

void EnvelopeSet::SharedCtor() {
}

EnvelopeSet::~EnvelopeSet() {
  // @@protoc_insertion_point(destructor:Proto.EnvelopeSet)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void EnvelopeSet::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void EnvelopeSet::ArenaDtor(void* object) {
  EnvelopeSet* _this = reinterpret_cast< EnvelopeSet* >(object);
  (void)_this;
}
void EnvelopeSet::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void EnvelopeSet::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void EnvelopeSet::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto.EnvelopeSet)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  items_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EnvelopeSet::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .Proto.Envelope items = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_items(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* EnvelopeSet::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Proto.EnvelopeSet)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Proto.Envelope items = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_items_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_items(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto.EnvelopeSet)
  return target;
}

size_t EnvelopeSet::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Proto.EnvelopeSet)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Proto.Envelope items = 1;
  total_size += 1UL * this->_internal_items_size();
  for (const auto& msg : this->items_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EnvelopeSet::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Proto.EnvelopeSet)
  GOOGLE_DCHECK_NE(&from, this);
  const EnvelopeSet* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<EnvelopeSet>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Proto.EnvelopeSet)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Proto.EnvelopeSet)
    MergeFrom(*source);
  }
}

void EnvelopeSet::MergeFrom(const EnvelopeSet& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Proto.EnvelopeSet)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  items_.MergeFrom(from.items_);
}

void EnvelopeSet::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Proto.EnvelopeSet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EnvelopeSet::CopyFrom(const EnvelopeSet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto.EnvelopeSet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EnvelopeSet::IsInitialized() const {
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(items_)) return false;
  return true;
}

void EnvelopeSet::InternalSwap(EnvelopeSet* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  items_.InternalSwap(&other->items_);
}

::PROTOBUF_NAMESPACE_ID::Metadata EnvelopeSet::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class EnvelopeSetShortDescription::_Internal {
 public:
  using HasBits = decltype(std::declval<EnvelopeSetShortDescription>()._has_bits_);
  static void set_has_projectdbversion(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_equipmenteditor(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_preseteditor(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_presetroot(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_projectname(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_username(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_exporttime(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
};

EnvelopeSetShortDescription::EnvelopeSetShortDescription(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  classnamehash_(arena),
  devicetype_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Proto.EnvelopeSetShortDescription)
}
EnvelopeSetShortDescription::EnvelopeSetShortDescription(const EnvelopeSetShortDescription& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      classnamehash_(from.classnamehash_),
      devicetype_(from.devicetype_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  projectname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_projectname()) {
    projectname_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_projectname(), 
      GetArena());
  }
  username_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_username()) {
    username_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_username(), 
      GetArena());
  }
  ::memcpy(&projectdbversion_, &from.projectdbversion_,
    static_cast<size_t>(reinterpret_cast<char*>(&exporttime_) -
    reinterpret_cast<char*>(&projectdbversion_)) + sizeof(exporttime_));
  // @@protoc_insertion_point(copy_constructor:Proto.EnvelopeSetShortDescription)
}

void EnvelopeSetShortDescription::SharedCtor() {
projectname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
username_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&projectdbversion_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&exporttime_) -
    reinterpret_cast<char*>(&projectdbversion_)) + sizeof(exporttime_));
}

EnvelopeSetShortDescription::~EnvelopeSetShortDescription() {
  // @@protoc_insertion_point(destructor:Proto.EnvelopeSetShortDescription)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void EnvelopeSetShortDescription::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  projectname_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  username_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void EnvelopeSetShortDescription::ArenaDtor(void* object) {
  EnvelopeSetShortDescription* _this = reinterpret_cast< EnvelopeSetShortDescription* >(object);
  (void)_this;
}
void EnvelopeSetShortDescription::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void EnvelopeSetShortDescription::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void EnvelopeSetShortDescription::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto.EnvelopeSetShortDescription)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  classnamehash_.Clear();
  devicetype_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      projectname_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      username_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x0000007cu) {
    ::memset(&projectdbversion_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&exporttime_) -
        reinterpret_cast<char*>(&projectdbversion_)) + sizeof(exporttime_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EnvelopeSetShortDescription::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional uint32 projectdbversion = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_projectdbversion(&has_bits);
          projectdbversion_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated uint32 classnamehash = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ptr -= 1;
          do {
            ptr += 1;
            _internal_add_classnamehash(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<16>(ptr));
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt32Parser(_internal_mutable_classnamehash(), ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool equipmentEditor = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          _Internal::set_has_equipmenteditor(&has_bits);
          equipmenteditor_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool presetEditor = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          _Internal::set_has_preseteditor(&has_bits);
          preseteditor_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool presetRoot = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          _Internal::set_has_presetroot(&has_bits);
          presetroot_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional string projectName = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          auto str = _internal_mutable_projectname();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Proto.EnvelopeSetShortDescription.projectName");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional string userName = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          auto str = _internal_mutable_username();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Proto.EnvelopeSetShortDescription.userName");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint64 exportTime = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 64)) {
          _Internal::set_has_exporttime(&has_bits);
          exporttime_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated int32 devicetype = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 80)) {
          ptr -= 1;
          do {
            ptr += 1;
            _internal_add_devicetype(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<80>(ptr));
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 82) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_devicetype(), ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* EnvelopeSetShortDescription::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Proto.EnvelopeSetShortDescription)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 projectdbversion = 1;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_projectdbversion(), target);
  }

  // repeated uint32 classnamehash = 2;
  for (int i = 0, n = this->_internal_classnamehash_size(); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_classnamehash(i), target);
  }

  // optional bool equipmentEditor = 3;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_equipmenteditor(), target);
  }

  // optional bool presetEditor = 4;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(4, this->_internal_preseteditor(), target);
  }

  // optional bool presetRoot = 5;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(5, this->_internal_presetroot(), target);
  }

  // optional string projectName = 6;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_projectname().data(), static_cast<int>(this->_internal_projectname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "Proto.EnvelopeSetShortDescription.projectName");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_projectname(), target);
  }

  // optional string userName = 7;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_username().data(), static_cast<int>(this->_internal_username().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "Proto.EnvelopeSetShortDescription.userName");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_username(), target);
  }

  // optional uint64 exportTime = 8;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(8, this->_internal_exporttime(), target);
  }

  // repeated int32 devicetype = 10;
  for (int i = 0, n = this->_internal_devicetype_size(); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(10, this->_internal_devicetype(i), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto.EnvelopeSetShortDescription)
  return target;
}

size_t EnvelopeSetShortDescription::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Proto.EnvelopeSetShortDescription)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint32 classnamehash = 2;
  {
    size_t data_size = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      UInt32Size(this->classnamehash_);
    total_size += 1 *
                  ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_classnamehash_size());
    total_size += data_size;
  }

  // repeated int32 devicetype = 10;
  {
    size_t data_size = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      Int32Size(this->devicetype_);
    total_size += 1 *
                  ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_devicetype_size());
    total_size += data_size;
  }

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    // optional string projectName = 6;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_projectname());
    }

    // optional string userName = 7;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_username());
    }

    // optional uint32 projectdbversion = 1;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_projectdbversion());
    }

    // optional bool equipmentEditor = 3;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 1;
    }

    // optional bool presetEditor = 4;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 1;
    }

    // optional bool presetRoot = 5;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + 1;
    }

    // optional uint64 exportTime = 8;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
          this->_internal_exporttime());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EnvelopeSetShortDescription::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Proto.EnvelopeSetShortDescription)
  GOOGLE_DCHECK_NE(&from, this);
  const EnvelopeSetShortDescription* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<EnvelopeSetShortDescription>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Proto.EnvelopeSetShortDescription)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Proto.EnvelopeSetShortDescription)
    MergeFrom(*source);
  }
}

void EnvelopeSetShortDescription::MergeFrom(const EnvelopeSetShortDescription& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Proto.EnvelopeSetShortDescription)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  classnamehash_.MergeFrom(from.classnamehash_);
  devicetype_.MergeFrom(from.devicetype_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_projectname(from._internal_projectname());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_username(from._internal_username());
    }
    if (cached_has_bits & 0x00000004u) {
      projectdbversion_ = from.projectdbversion_;
    }
    if (cached_has_bits & 0x00000008u) {
      equipmenteditor_ = from.equipmenteditor_;
    }
    if (cached_has_bits & 0x00000010u) {
      preseteditor_ = from.preseteditor_;
    }
    if (cached_has_bits & 0x00000020u) {
      presetroot_ = from.presetroot_;
    }
    if (cached_has_bits & 0x00000040u) {
      exporttime_ = from.exporttime_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void EnvelopeSetShortDescription::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Proto.EnvelopeSetShortDescription)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EnvelopeSetShortDescription::CopyFrom(const EnvelopeSetShortDescription& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto.EnvelopeSetShortDescription)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EnvelopeSetShortDescription::IsInitialized() const {
  return true;
}

void EnvelopeSetShortDescription::InternalSwap(EnvelopeSetShortDescription* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  classnamehash_.InternalSwap(&other->classnamehash_);
  devicetype_.InternalSwap(&other->devicetype_);
  projectname_.Swap(&other->projectname_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  username_.Swap(&other->username_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(EnvelopeSetShortDescription, exporttime_)
      + sizeof(EnvelopeSetShortDescription::exporttime_)
      - PROTOBUF_FIELD_OFFSET(EnvelopeSetShortDescription, projectdbversion_)>(
          reinterpret_cast<char*>(&projectdbversion_),
          reinterpret_cast<char*>(&other->projectdbversion_));
}

::PROTOBUF_NAMESPACE_ID::Metadata EnvelopeSetShortDescription::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class ExportedDevicePreset2::_Internal {
 public:
  using HasBits = decltype(std::declval<ExportedDevicePreset2>()._has_bits_);
  static const ::Proto::EnvelopeSetShortDescription& description(const ExportedDevicePreset2* msg);
  static void set_has_description(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::Proto::EnvelopeSet& items(const ExportedDevicePreset2* msg);
  static void set_has_items(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_compressedthis(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::Proto::EnvelopeSetShortDescription&
ExportedDevicePreset2::_Internal::description(const ExportedDevicePreset2* msg) {
  return *msg->description_;
}
const ::Proto::EnvelopeSet&
ExportedDevicePreset2::_Internal::items(const ExportedDevicePreset2* msg) {
  return *msg->items_;
}
ExportedDevicePreset2::ExportedDevicePreset2(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Proto.ExportedDevicePreset2)
}
ExportedDevicePreset2::ExportedDevicePreset2(const ExportedDevicePreset2& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  compressedthis_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_compressedthis()) {
    compressedthis_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_compressedthis(), 
      GetArena());
  }
  if (from._internal_has_description()) {
    description_ = new ::Proto::EnvelopeSetShortDescription(*from.description_);
  } else {
    description_ = nullptr;
  }
  if (from._internal_has_items()) {
    items_ = new ::Proto::EnvelopeSet(*from.items_);
  } else {
    items_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:Proto.ExportedDevicePreset2)
}

void ExportedDevicePreset2::SharedCtor() {
compressedthis_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&description_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&items_) -
    reinterpret_cast<char*>(&description_)) + sizeof(items_));
}

ExportedDevicePreset2::~ExportedDevicePreset2() {
  // @@protoc_insertion_point(destructor:Proto.ExportedDevicePreset2)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ExportedDevicePreset2::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  compressedthis_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete description_;
  if (this != internal_default_instance()) delete items_;
}

void ExportedDevicePreset2::ArenaDtor(void* object) {
  ExportedDevicePreset2* _this = reinterpret_cast< ExportedDevicePreset2* >(object);
  (void)_this;
}
void ExportedDevicePreset2::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ExportedDevicePreset2::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ExportedDevicePreset2::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto.ExportedDevicePreset2)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      compressedthis_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(description_ != nullptr);
      description_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(items_ != nullptr);
      items_->Clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ExportedDevicePreset2::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional .Proto.EnvelopeSetShortDescription description = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_description(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .Proto.EnvelopeSet items = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_items(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bytes compressedThis = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_compressedthis();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ExportedDevicePreset2::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Proto.ExportedDevicePreset2)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .Proto.EnvelopeSetShortDescription description = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::description(this), target, stream);
  }

  // optional .Proto.EnvelopeSet items = 2;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::items(this), target, stream);
  }

  // optional bytes compressedThis = 3;
  if (cached_has_bits & 0x00000001u) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_compressedthis(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto.ExportedDevicePreset2)
  return target;
}

size_t ExportedDevicePreset2::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Proto.ExportedDevicePreset2)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional bytes compressedThis = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_compressedthis());
    }

    // optional .Proto.EnvelopeSetShortDescription description = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *description_);
    }

    // optional .Proto.EnvelopeSet items = 2;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *items_);
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ExportedDevicePreset2::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Proto.ExportedDevicePreset2)
  GOOGLE_DCHECK_NE(&from, this);
  const ExportedDevicePreset2* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ExportedDevicePreset2>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Proto.ExportedDevicePreset2)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Proto.ExportedDevicePreset2)
    MergeFrom(*source);
  }
}

void ExportedDevicePreset2::MergeFrom(const ExportedDevicePreset2& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Proto.ExportedDevicePreset2)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_compressedthis(from._internal_compressedthis());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_description()->::Proto::EnvelopeSetShortDescription::MergeFrom(from._internal_description());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_mutable_items()->::Proto::EnvelopeSet::MergeFrom(from._internal_items());
    }
  }
}

void ExportedDevicePreset2::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Proto.ExportedDevicePreset2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExportedDevicePreset2::CopyFrom(const ExportedDevicePreset2& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto.ExportedDevicePreset2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExportedDevicePreset2::IsInitialized() const {
  if (_internal_has_items()) {
    if (!items_->IsInitialized()) return false;
  }
  return true;
}

void ExportedDevicePreset2::InternalSwap(ExportedDevicePreset2* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  compressedthis_.Swap(&other->compressedthis_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ExportedDevicePreset2, items_)
      + sizeof(ExportedDevicePreset2::items_)
      - PROTOBUF_FIELD_OFFSET(ExportedDevicePreset2, description_)>(
          reinterpret_cast<char*>(&description_),
          reinterpret_cast<char*>(&other->description_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ExportedDevicePreset2::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Proto
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Proto::Envelope* Arena::CreateMaybeMessage< ::Proto::Envelope >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Proto::Envelope >(arena);
}
template<> PROTOBUF_NOINLINE ::Proto::EnvelopeSet* Arena::CreateMaybeMessage< ::Proto::EnvelopeSet >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Proto::EnvelopeSet >(arena);
}
template<> PROTOBUF_NOINLINE ::Proto::EnvelopeSetShortDescription* Arena::CreateMaybeMessage< ::Proto::EnvelopeSetShortDescription >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Proto::EnvelopeSetShortDescription >(arena);
}
template<> PROTOBUF_NOINLINE ::Proto::ExportedDevicePreset2* Arena::CreateMaybeMessage< ::Proto::ExportedDevicePreset2 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Proto::ExportedDevicePreset2 >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>

#ifdef _MSC_VER
#pragma warning(pop)
#endif