// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network.proto

#ifndef PROTOBUF_network_2eproto__INCLUDED
#define PROTOBUF_network_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "serialization.pb.h"
// @@protoc_insertion_point(includes)

namespace Network {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_network_2eproto();
void protobuf_AssignDesc_network_2eproto();
void protobuf_ShutdownFile_network_2eproto();

class GetSignalListStartRequest;
class GetSignalListStartReply;
class GetSignalListNextRequest;
class GetSignalListNextReply;
class GetSignalParamRequest;
class GetSignalParamReply;
class AppSignalState;

// ===================================================================

class GetSignalListStartRequest : public ::google::protobuf::Message {
 public:
  GetSignalListStartRequest();
  virtual ~GetSignalListStartRequest();

  GetSignalListStartRequest(const GetSignalListStartRequest& from);

  inline GetSignalListStartRequest& operator=(const GetSignalListStartRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetSignalListStartRequest& default_instance();

  void Swap(GetSignalListStartRequest* other);

  // implements Message ----------------------------------------------

  GetSignalListStartRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetSignalListStartRequest& from);
  void MergeFrom(const GetSignalListStartRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Network.GetSignalListStartRequest)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();

  void InitAsDefaultInstance();
  static GetSignalListStartRequest* default_instance_;
};
// -------------------------------------------------------------------

class GetSignalListStartReply : public ::google::protobuf::Message {
 public:
  GetSignalListStartReply();
  virtual ~GetSignalListStartReply();

  GetSignalListStartReply(const GetSignalListStartReply& from);

  inline GetSignalListStartReply& operator=(const GetSignalListStartReply& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetSignalListStartReply& default_instance();

  void Swap(GetSignalListStartReply* other);

  // implements Message ----------------------------------------------

  GetSignalListStartReply* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetSignalListStartReply& from);
  void MergeFrom(const GetSignalListStartReply& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 error = 1 [default = 0];
  inline bool has_error() const;
  inline void clear_error();
  static const int kErrorFieldNumber = 1;
  inline ::google::protobuf::int32 error() const;
  inline void set_error(::google::protobuf::int32 value);

  // optional int32 totalItemCount = 2;
  inline bool has_totalitemcount() const;
  inline void clear_totalitemcount();
  static const int kTotalItemCountFieldNumber = 2;
  inline ::google::protobuf::int32 totalitemcount() const;
  inline void set_totalitemcount(::google::protobuf::int32 value);

  // optional int32 partCount = 3;
  inline bool has_partcount() const;
  inline void clear_partcount();
  static const int kPartCountFieldNumber = 3;
  inline ::google::protobuf::int32 partcount() const;
  inline void set_partcount(::google::protobuf::int32 value);

  // optional int32 itemsPerPart = 4;
  inline bool has_itemsperpart() const;
  inline void clear_itemsperpart();
  static const int kItemsPerPartFieldNumber = 4;
  inline ::google::protobuf::int32 itemsperpart() const;
  inline void set_itemsperpart(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Network.GetSignalListStartReply)
 private:
  inline void set_has_error();
  inline void clear_has_error();
  inline void set_has_totalitemcount();
  inline void clear_has_totalitemcount();
  inline void set_has_partcount();
  inline void clear_has_partcount();
  inline void set_has_itemsperpart();
  inline void clear_has_itemsperpart();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 error_;
  ::google::protobuf::int32 totalitemcount_;
  ::google::protobuf::int32 partcount_;
  ::google::protobuf::int32 itemsperpart_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();

  void InitAsDefaultInstance();
  static GetSignalListStartReply* default_instance_;
};
// -------------------------------------------------------------------

class GetSignalListNextRequest : public ::google::protobuf::Message {
 public:
  GetSignalListNextRequest();
  virtual ~GetSignalListNextRequest();

  GetSignalListNextRequest(const GetSignalListNextRequest& from);

  inline GetSignalListNextRequest& operator=(const GetSignalListNextRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetSignalListNextRequest& default_instance();

  void Swap(GetSignalListNextRequest* other);

  // implements Message ----------------------------------------------

  GetSignalListNextRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetSignalListNextRequest& from);
  void MergeFrom(const GetSignalListNextRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 part = 1;
  inline bool has_part() const;
  inline void clear_part();
  static const int kPartFieldNumber = 1;
  inline ::google::protobuf::int32 part() const;
  inline void set_part(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Network.GetSignalListNextRequest)
 private:
  inline void set_has_part();
  inline void clear_has_part();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 part_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();

  void InitAsDefaultInstance();
  static GetSignalListNextRequest* default_instance_;
};
// -------------------------------------------------------------------

class GetSignalListNextReply : public ::google::protobuf::Message {
 public:
  GetSignalListNextReply();
  virtual ~GetSignalListNextReply();

  GetSignalListNextReply(const GetSignalListNextReply& from);

  inline GetSignalListNextReply& operator=(const GetSignalListNextReply& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetSignalListNextReply& default_instance();

  void Swap(GetSignalListNextReply* other);

  // implements Message ----------------------------------------------

  GetSignalListNextReply* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetSignalListNextReply& from);
  void MergeFrom(const GetSignalListNextReply& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 error = 1 [default = 0];
  inline bool has_error() const;
  inline void clear_error();
  static const int kErrorFieldNumber = 1;
  inline ::google::protobuf::int32 error() const;
  inline void set_error(::google::protobuf::int32 value);

  // optional int32 part = 2;
  inline bool has_part() const;
  inline void clear_part();
  static const int kPartFieldNumber = 2;
  inline ::google::protobuf::int32 part() const;
  inline void set_part(::google::protobuf::int32 value);

  // repeated string appSignalIds = 3;
  inline int appsignalids_size() const;
  inline void clear_appsignalids();
  static const int kAppSignalIdsFieldNumber = 3;
  inline const ::std::string& appsignalids(int index) const;
  inline ::std::string* mutable_appsignalids(int index);
  inline void set_appsignalids(int index, const ::std::string& value);
  inline void set_appsignalids(int index, const char* value);
  inline void set_appsignalids(int index, const char* value, size_t size);
  inline ::std::string* add_appsignalids();
  inline void add_appsignalids(const ::std::string& value);
  inline void add_appsignalids(const char* value);
  inline void add_appsignalids(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& appsignalids() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_appsignalids();

  // @@protoc_insertion_point(class_scope:Network.GetSignalListNextReply)
 private:
  inline void set_has_error();
  inline void clear_has_error();
  inline void set_has_part();
  inline void clear_has_part();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 error_;
  ::google::protobuf::int32 part_;
  ::google::protobuf::RepeatedPtrField< ::std::string> appsignalids_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();

  void InitAsDefaultInstance();
  static GetSignalListNextReply* default_instance_;
};
// -------------------------------------------------------------------

class GetSignalParamRequest : public ::google::protobuf::Message {
 public:
  GetSignalParamRequest();
  virtual ~GetSignalParamRequest();

  GetSignalParamRequest(const GetSignalParamRequest& from);

  inline GetSignalParamRequest& operator=(const GetSignalParamRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetSignalParamRequest& default_instance();

  void Swap(GetSignalParamRequest* other);

  // implements Message ----------------------------------------------

  GetSignalParamRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetSignalParamRequest& from);
  void MergeFrom(const GetSignalParamRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 signalHashes = 1;
  inline int signalhashes_size() const;
  inline void clear_signalhashes();
  static const int kSignalHashesFieldNumber = 1;
  inline ::google::protobuf::uint64 signalhashes(int index) const;
  inline void set_signalhashes(int index, ::google::protobuf::uint64 value);
  inline void add_signalhashes(::google::protobuf::uint64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      signalhashes() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_signalhashes();

  // @@protoc_insertion_point(class_scope:Network.GetSignalParamRequest)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > signalhashes_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();

  void InitAsDefaultInstance();
  static GetSignalParamRequest* default_instance_;
};
// -------------------------------------------------------------------

class GetSignalParamReply : public ::google::protobuf::Message {
 public:
  GetSignalParamReply();
  virtual ~GetSignalParamReply();

  GetSignalParamReply(const GetSignalParamReply& from);

  inline GetSignalParamReply& operator=(const GetSignalParamReply& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetSignalParamReply& default_instance();

  void Swap(GetSignalParamReply* other);

  // implements Message ----------------------------------------------

  GetSignalParamReply* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetSignalParamReply& from);
  void MergeFrom(const GetSignalParamReply& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 error = 1 [default = 0];
  inline bool has_error() const;
  inline void clear_error();
  static const int kErrorFieldNumber = 1;
  inline ::google::protobuf::int32 error() const;
  inline void set_error(::google::protobuf::int32 value);

  // repeated .Proto.Signal signalParams = 2;
  inline int signalparams_size() const;
  inline void clear_signalparams();
  static const int kSignalParamsFieldNumber = 2;
  inline const ::Proto::Signal& signalparams(int index) const;
  inline ::Proto::Signal* mutable_signalparams(int index);
  inline ::Proto::Signal* add_signalparams();
  inline const ::google::protobuf::RepeatedPtrField< ::Proto::Signal >&
      signalparams() const;
  inline ::google::protobuf::RepeatedPtrField< ::Proto::Signal >*
      mutable_signalparams();

  // @@protoc_insertion_point(class_scope:Network.GetSignalParamReply)
 private:
  inline void set_has_error();
  inline void clear_has_error();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::Proto::Signal > signalparams_;
  ::google::protobuf::int32 error_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();

  void InitAsDefaultInstance();
  static GetSignalParamReply* default_instance_;
};
// -------------------------------------------------------------------

class AppSignalState : public ::google::protobuf::Message {
 public:
  AppSignalState();
  virtual ~AppSignalState();

  AppSignalState(const AppSignalState& from);

  inline AppSignalState& operator=(const AppSignalState& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AppSignalState& default_instance();

  void Swap(AppSignalState* other);

  // implements Message ----------------------------------------------

  AppSignalState* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AppSignalState& from);
  void MergeFrom(const AppSignalState& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 hash = 1;
  inline bool has_hash() const;
  inline void clear_hash();
  static const int kHashFieldNumber = 1;
  inline ::google::protobuf::uint64 hash() const;
  inline void set_hash(::google::protobuf::uint64 value);

  // optional double value = 2;
  inline bool has_value() const;
  inline void clear_value();
  static const int kValueFieldNumber = 2;
  inline double value() const;
  inline void set_value(double value);

  // optional uint32 flags = 3;
  inline bool has_flags() const;
  inline void clear_flags();
  static const int kFlagsFieldNumber = 3;
  inline ::google::protobuf::uint32 flags() const;
  inline void set_flags(::google::protobuf::uint32 value);

  // optional sint64 systemTime = 4;
  inline bool has_systemtime() const;
  inline void clear_systemtime();
  static const int kSystemTimeFieldNumber = 4;
  inline ::google::protobuf::int64 systemtime() const;
  inline void set_systemtime(::google::protobuf::int64 value);

  // optional sint64 localTime = 5;
  inline bool has_localtime() const;
  inline void clear_localtime();
  static const int kLocalTimeFieldNumber = 5;
  inline ::google::protobuf::int64 localtime() const;
  inline void set_localtime(::google::protobuf::int64 value);

  // optional sint64 plantTime = 6;
  inline bool has_planttime() const;
  inline void clear_planttime();
  static const int kPlantTimeFieldNumber = 6;
  inline ::google::protobuf::int64 planttime() const;
  inline void set_planttime(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Network.AppSignalState)
 private:
  inline void set_has_hash();
  inline void clear_has_hash();
  inline void set_has_value();
  inline void clear_has_value();
  inline void set_has_flags();
  inline void clear_has_flags();
  inline void set_has_systemtime();
  inline void clear_has_systemtime();
  inline void set_has_localtime();
  inline void clear_has_localtime();
  inline void set_has_planttime();
  inline void clear_has_planttime();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 hash_;
  double value_;
  ::google::protobuf::int64 systemtime_;
  ::google::protobuf::int64 localtime_;
  ::google::protobuf::int64 planttime_;
  ::google::protobuf::uint32 flags_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();

  void InitAsDefaultInstance();
  static AppSignalState* default_instance_;
};
// ===================================================================


// ===================================================================

// GetSignalListStartRequest

// -------------------------------------------------------------------

// GetSignalListStartReply

// optional int32 error = 1 [default = 0];
inline bool GetSignalListStartReply::has_error() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetSignalListStartReply::set_has_error() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetSignalListStartReply::clear_has_error() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetSignalListStartReply::clear_error() {
  error_ = 0;
  clear_has_error();
}
inline ::google::protobuf::int32 GetSignalListStartReply::error() const {
  return error_;
}
inline void GetSignalListStartReply::set_error(::google::protobuf::int32 value) {
  set_has_error();
  error_ = value;
}

// optional int32 totalItemCount = 2;
inline bool GetSignalListStartReply::has_totalitemcount() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GetSignalListStartReply::set_has_totalitemcount() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GetSignalListStartReply::clear_has_totalitemcount() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GetSignalListStartReply::clear_totalitemcount() {
  totalitemcount_ = 0;
  clear_has_totalitemcount();
}
inline ::google::protobuf::int32 GetSignalListStartReply::totalitemcount() const {
  return totalitemcount_;
}
inline void GetSignalListStartReply::set_totalitemcount(::google::protobuf::int32 value) {
  set_has_totalitemcount();
  totalitemcount_ = value;
}

// optional int32 partCount = 3;
inline bool GetSignalListStartReply::has_partcount() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GetSignalListStartReply::set_has_partcount() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GetSignalListStartReply::clear_has_partcount() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GetSignalListStartReply::clear_partcount() {
  partcount_ = 0;
  clear_has_partcount();
}
inline ::google::protobuf::int32 GetSignalListStartReply::partcount() const {
  return partcount_;
}
inline void GetSignalListStartReply::set_partcount(::google::protobuf::int32 value) {
  set_has_partcount();
  partcount_ = value;
}

// optional int32 itemsPerPart = 4;
inline bool GetSignalListStartReply::has_itemsperpart() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void GetSignalListStartReply::set_has_itemsperpart() {
  _has_bits_[0] |= 0x00000008u;
}
inline void GetSignalListStartReply::clear_has_itemsperpart() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void GetSignalListStartReply::clear_itemsperpart() {
  itemsperpart_ = 0;
  clear_has_itemsperpart();
}
inline ::google::protobuf::int32 GetSignalListStartReply::itemsperpart() const {
  return itemsperpart_;
}
inline void GetSignalListStartReply::set_itemsperpart(::google::protobuf::int32 value) {
  set_has_itemsperpart();
  itemsperpart_ = value;
}

// -------------------------------------------------------------------

// GetSignalListNextRequest

// optional int32 part = 1;
inline bool GetSignalListNextRequest::has_part() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetSignalListNextRequest::set_has_part() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetSignalListNextRequest::clear_has_part() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetSignalListNextRequest::clear_part() {
  part_ = 0;
  clear_has_part();
}
inline ::google::protobuf::int32 GetSignalListNextRequest::part() const {
  return part_;
}
inline void GetSignalListNextRequest::set_part(::google::protobuf::int32 value) {
  set_has_part();
  part_ = value;
}

// -------------------------------------------------------------------

// GetSignalListNextReply

// optional int32 error = 1 [default = 0];
inline bool GetSignalListNextReply::has_error() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetSignalListNextReply::set_has_error() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetSignalListNextReply::clear_has_error() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetSignalListNextReply::clear_error() {
  error_ = 0;
  clear_has_error();
}
inline ::google::protobuf::int32 GetSignalListNextReply::error() const {
  return error_;
}
inline void GetSignalListNextReply::set_error(::google::protobuf::int32 value) {
  set_has_error();
  error_ = value;
}

// optional int32 part = 2;
inline bool GetSignalListNextReply::has_part() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GetSignalListNextReply::set_has_part() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GetSignalListNextReply::clear_has_part() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GetSignalListNextReply::clear_part() {
  part_ = 0;
  clear_has_part();
}
inline ::google::protobuf::int32 GetSignalListNextReply::part() const {
  return part_;
}
inline void GetSignalListNextReply::set_part(::google::protobuf::int32 value) {
  set_has_part();
  part_ = value;
}

// repeated string appSignalIds = 3;
inline int GetSignalListNextReply::appsignalids_size() const {
  return appsignalids_.size();
}
inline void GetSignalListNextReply::clear_appsignalids() {
  appsignalids_.Clear();
}
inline const ::std::string& GetSignalListNextReply::appsignalids(int index) const {
  return appsignalids_.Get(index);
}
inline ::std::string* GetSignalListNextReply::mutable_appsignalids(int index) {
  return appsignalids_.Mutable(index);
}
inline void GetSignalListNextReply::set_appsignalids(int index, const ::std::string& value) {
  appsignalids_.Mutable(index)->assign(value);
}
inline void GetSignalListNextReply::set_appsignalids(int index, const char* value) {
  appsignalids_.Mutable(index)->assign(value);
}
inline void GetSignalListNextReply::set_appsignalids(int index, const char* value, size_t size) {
  appsignalids_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* GetSignalListNextReply::add_appsignalids() {
  return appsignalids_.Add();
}
inline void GetSignalListNextReply::add_appsignalids(const ::std::string& value) {
  appsignalids_.Add()->assign(value);
}
inline void GetSignalListNextReply::add_appsignalids(const char* value) {
  appsignalids_.Add()->assign(value);
}
inline void GetSignalListNextReply::add_appsignalids(const char* value, size_t size) {
  appsignalids_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
GetSignalListNextReply::appsignalids() const {
  return appsignalids_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
GetSignalListNextReply::mutable_appsignalids() {
  return &appsignalids_;
}

// -------------------------------------------------------------------

// GetSignalParamRequest

// repeated uint64 signalHashes = 1;
inline int GetSignalParamRequest::signalhashes_size() const {
  return signalhashes_.size();
}
inline void GetSignalParamRequest::clear_signalhashes() {
  signalhashes_.Clear();
}
inline ::google::protobuf::uint64 GetSignalParamRequest::signalhashes(int index) const {
  return signalhashes_.Get(index);
}
inline void GetSignalParamRequest::set_signalhashes(int index, ::google::protobuf::uint64 value) {
  signalhashes_.Set(index, value);
}
inline void GetSignalParamRequest::add_signalhashes(::google::protobuf::uint64 value) {
  signalhashes_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
GetSignalParamRequest::signalhashes() const {
  return signalhashes_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
GetSignalParamRequest::mutable_signalhashes() {
  return &signalhashes_;
}

// -------------------------------------------------------------------

// GetSignalParamReply

// optional int32 error = 1 [default = 0];
inline bool GetSignalParamReply::has_error() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetSignalParamReply::set_has_error() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetSignalParamReply::clear_has_error() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetSignalParamReply::clear_error() {
  error_ = 0;
  clear_has_error();
}
inline ::google::protobuf::int32 GetSignalParamReply::error() const {
  return error_;
}
inline void GetSignalParamReply::set_error(::google::protobuf::int32 value) {
  set_has_error();
  error_ = value;
}

// repeated .Proto.Signal signalParams = 2;
inline int GetSignalParamReply::signalparams_size() const {
  return signalparams_.size();
}
inline void GetSignalParamReply::clear_signalparams() {
  signalparams_.Clear();
}
inline const ::Proto::Signal& GetSignalParamReply::signalparams(int index) const {
  return signalparams_.Get(index);
}
inline ::Proto::Signal* GetSignalParamReply::mutable_signalparams(int index) {
  return signalparams_.Mutable(index);
}
inline ::Proto::Signal* GetSignalParamReply::add_signalparams() {
  return signalparams_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Proto::Signal >&
GetSignalParamReply::signalparams() const {
  return signalparams_;
}
inline ::google::protobuf::RepeatedPtrField< ::Proto::Signal >*
GetSignalParamReply::mutable_signalparams() {
  return &signalparams_;
}

// -------------------------------------------------------------------

// AppSignalState

// optional uint64 hash = 1;
inline bool AppSignalState::has_hash() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AppSignalState::set_has_hash() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AppSignalState::clear_has_hash() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AppSignalState::clear_hash() {
  hash_ = GOOGLE_ULONGLONG(0);
  clear_has_hash();
}
inline ::google::protobuf::uint64 AppSignalState::hash() const {
  return hash_;
}
inline void AppSignalState::set_hash(::google::protobuf::uint64 value) {
  set_has_hash();
  hash_ = value;
}

// optional double value = 2;
inline bool AppSignalState::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AppSignalState::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AppSignalState::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AppSignalState::clear_value() {
  value_ = 0;
  clear_has_value();
}
inline double AppSignalState::value() const {
  return value_;
}
inline void AppSignalState::set_value(double value) {
  set_has_value();
  value_ = value;
}

// optional uint32 flags = 3;
inline bool AppSignalState::has_flags() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AppSignalState::set_has_flags() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AppSignalState::clear_has_flags() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AppSignalState::clear_flags() {
  flags_ = 0u;
  clear_has_flags();
}
inline ::google::protobuf::uint32 AppSignalState::flags() const {
  return flags_;
}
inline void AppSignalState::set_flags(::google::protobuf::uint32 value) {
  set_has_flags();
  flags_ = value;
}

// optional sint64 systemTime = 4;
inline bool AppSignalState::has_systemtime() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void AppSignalState::set_has_systemtime() {
  _has_bits_[0] |= 0x00000008u;
}
inline void AppSignalState::clear_has_systemtime() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void AppSignalState::clear_systemtime() {
  systemtime_ = GOOGLE_LONGLONG(0);
  clear_has_systemtime();
}
inline ::google::protobuf::int64 AppSignalState::systemtime() const {
  return systemtime_;
}
inline void AppSignalState::set_systemtime(::google::protobuf::int64 value) {
  set_has_systemtime();
  systemtime_ = value;
}

// optional sint64 localTime = 5;
inline bool AppSignalState::has_localtime() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void AppSignalState::set_has_localtime() {
  _has_bits_[0] |= 0x00000010u;
}
inline void AppSignalState::clear_has_localtime() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void AppSignalState::clear_localtime() {
  localtime_ = GOOGLE_LONGLONG(0);
  clear_has_localtime();
}
inline ::google::protobuf::int64 AppSignalState::localtime() const {
  return localtime_;
}
inline void AppSignalState::set_localtime(::google::protobuf::int64 value) {
  set_has_localtime();
  localtime_ = value;
}

// optional sint64 plantTime = 6;
inline bool AppSignalState::has_planttime() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void AppSignalState::set_has_planttime() {
  _has_bits_[0] |= 0x00000020u;
}
inline void AppSignalState::clear_has_planttime() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void AppSignalState::clear_planttime() {
  planttime_ = GOOGLE_LONGLONG(0);
  clear_has_planttime();
}
inline ::google::protobuf::int64 AppSignalState::planttime() const {
  return planttime_;
}
inline void AppSignalState::set_planttime(::google::protobuf::int64 value) {
  set_has_planttime();
  planttime_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Network

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_network_2eproto__INCLUDED
