// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Simulator.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Simulator_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Simulator_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Common.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Simulator_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Simulator_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Simulator_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_Simulator_2eproto_metadata_getter(int index);
namespace Proto {
class SimOverrideSignal;
struct SimOverrideSignalDefaultTypeInternal;
extern SimOverrideSignalDefaultTypeInternal _SimOverrideSignal_default_instance_;
class SimOverrideSignalWorkspace;
struct SimOverrideSignalWorkspaceDefaultTypeInternal;
extern SimOverrideSignalWorkspaceDefaultTypeInternal _SimOverrideSignalWorkspace_default_instance_;
}  // namespace Proto
PROTOBUF_NAMESPACE_OPEN
template<> ::Proto::SimOverrideSignal* Arena::CreateMaybeMessage<::Proto::SimOverrideSignal>(Arena*);
template<> ::Proto::SimOverrideSignalWorkspace* Arena::CreateMaybeMessage<::Proto::SimOverrideSignalWorkspace>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Proto {

// ===================================================================

class SimOverrideSignal PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.SimOverrideSignal) */ {
 public:
  inline SimOverrideSignal() : SimOverrideSignal(nullptr) {}
  virtual ~SimOverrideSignal();
  explicit constexpr SimOverrideSignal(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SimOverrideSignal(const SimOverrideSignal& from);
  SimOverrideSignal(SimOverrideSignal&& from) noexcept
    : SimOverrideSignal() {
    *this = ::std::move(from);
  }

  inline SimOverrideSignal& operator=(const SimOverrideSignal& from) {
    CopyFrom(from);
    return *this;
  }
  inline SimOverrideSignal& operator=(SimOverrideSignal&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SimOverrideSignal& default_instance() {
    return *internal_default_instance();
  }
  static inline const SimOverrideSignal* internal_default_instance() {
    return reinterpret_cast<const SimOverrideSignal*>(
               &_SimOverrideSignal_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SimOverrideSignal& a, SimOverrideSignal& b) {
    a.Swap(&b);
  }
  inline void Swap(SimOverrideSignal* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SimOverrideSignal* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SimOverrideSignal* New() const final {
    return CreateMaybeMessage<SimOverrideSignal>(nullptr);
  }

  SimOverrideSignal* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SimOverrideSignal>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SimOverrideSignal& from);
  void MergeFrom(const SimOverrideSignal& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SimOverrideSignal* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.SimOverrideSignal";
  }
  protected:
  explicit SimOverrideSignal(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_Simulator_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAppSignalIdFieldNumber = 10,
    kOverrideScriptFieldNumber = 50,
    kOverrideValueFieldNumber = 40,
    kEnabledFieldNumber = 2,
    kIndexFieldNumber = 3,
    kOverrideMethodFieldNumber = 30,
  };
  // optional string appSignalId = 10;
  bool has_appsignalid() const;
  private:
  bool _internal_has_appsignalid() const;
  public:
  void clear_appsignalid();
  const std::string& appsignalid() const;
  void set_appsignalid(const std::string& value);
  void set_appsignalid(std::string&& value);
  void set_appsignalid(const char* value);
  void set_appsignalid(const char* value, size_t size);
  std::string* mutable_appsignalid();
  std::string* release_appsignalid();
  void set_allocated_appsignalid(std::string* appsignalid);
  private:
  const std::string& _internal_appsignalid() const;
  void _internal_set_appsignalid(const std::string& value);
  std::string* _internal_mutable_appsignalid();
  public:

  // optional string overrideScript = 50;
  bool has_overridescript() const;
  private:
  bool _internal_has_overridescript() const;
  public:
  void clear_overridescript();
  const std::string& overridescript() const;
  void set_overridescript(const std::string& value);
  void set_overridescript(std::string&& value);
  void set_overridescript(const char* value);
  void set_overridescript(const char* value, size_t size);
  std::string* mutable_overridescript();
  std::string* release_overridescript();
  void set_allocated_overridescript(std::string* overridescript);
  private:
  const std::string& _internal_overridescript() const;
  void _internal_set_overridescript(const std::string& value);
  std::string* _internal_mutable_overridescript();
  public:

  // optional .Proto.qvariant overrideValue = 40;
  bool has_overridevalue() const;
  private:
  bool _internal_has_overridevalue() const;
  public:
  void clear_overridevalue();
  const ::Proto::qvariant& overridevalue() const;
  ::Proto::qvariant* release_overridevalue();
  ::Proto::qvariant* mutable_overridevalue();
  void set_allocated_overridevalue(::Proto::qvariant* overridevalue);
  private:
  const ::Proto::qvariant& _internal_overridevalue() const;
  ::Proto::qvariant* _internal_mutable_overridevalue();
  public:
  void unsafe_arena_set_allocated_overridevalue(
      ::Proto::qvariant* overridevalue);
  ::Proto::qvariant* unsafe_arena_release_overridevalue();

  // optional bool enabled = 2;
  bool has_enabled() const;
  private:
  bool _internal_has_enabled() const;
  public:
  void clear_enabled();
  bool enabled() const;
  void set_enabled(bool value);
  private:
  bool _internal_enabled() const;
  void _internal_set_enabled(bool value);
  public:

  // optional int32 index = 3;
  bool has_index() const;
  private:
  bool _internal_has_index() const;
  public:
  void clear_index();
  ::PROTOBUF_NAMESPACE_ID::int32 index() const;
  void set_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_index() const;
  void _internal_set_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 overrideMethod = 30;
  bool has_overridemethod() const;
  private:
  bool _internal_has_overridemethod() const;
  public:
  void clear_overridemethod();
  ::PROTOBUF_NAMESPACE_ID::int32 overridemethod() const;
  void set_overridemethod(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_overridemethod() const;
  void _internal_set_overridemethod(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:Proto.SimOverrideSignal)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr appsignalid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr overridescript_;
  ::Proto::qvariant* overridevalue_;
  bool enabled_;
  ::PROTOBUF_NAMESPACE_ID::int32 index_;
  ::PROTOBUF_NAMESPACE_ID::int32 overridemethod_;
  friend struct ::TableStruct_Simulator_2eproto;
};
// -------------------------------------------------------------------

class SimOverrideSignalWorkspace PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.SimOverrideSignalWorkspace) */ {
 public:
  inline SimOverrideSignalWorkspace() : SimOverrideSignalWorkspace(nullptr) {}
  virtual ~SimOverrideSignalWorkspace();
  explicit constexpr SimOverrideSignalWorkspace(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SimOverrideSignalWorkspace(const SimOverrideSignalWorkspace& from);
  SimOverrideSignalWorkspace(SimOverrideSignalWorkspace&& from) noexcept
    : SimOverrideSignalWorkspace() {
    *this = ::std::move(from);
  }

  inline SimOverrideSignalWorkspace& operator=(const SimOverrideSignalWorkspace& from) {
    CopyFrom(from);
    return *this;
  }
  inline SimOverrideSignalWorkspace& operator=(SimOverrideSignalWorkspace&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SimOverrideSignalWorkspace& default_instance() {
    return *internal_default_instance();
  }
  static inline const SimOverrideSignalWorkspace* internal_default_instance() {
    return reinterpret_cast<const SimOverrideSignalWorkspace*>(
               &_SimOverrideSignalWorkspace_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SimOverrideSignalWorkspace& a, SimOverrideSignalWorkspace& b) {
    a.Swap(&b);
  }
  inline void Swap(SimOverrideSignalWorkspace* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SimOverrideSignalWorkspace* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SimOverrideSignalWorkspace* New() const final {
    return CreateMaybeMessage<SimOverrideSignalWorkspace>(nullptr);
  }

  SimOverrideSignalWorkspace* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SimOverrideSignalWorkspace>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SimOverrideSignalWorkspace& from);
  void MergeFrom(const SimOverrideSignalWorkspace& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SimOverrideSignalWorkspace* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.SimOverrideSignalWorkspace";
  }
  protected:
  explicit SimOverrideSignalWorkspace(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_Simulator_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOverrideSignalsFieldNumber = 2,
  };
  // repeated .Proto.SimOverrideSignal overrideSignals = 2;
  int overridesignals_size() const;
  private:
  int _internal_overridesignals_size() const;
  public:
  void clear_overridesignals();
  ::Proto::SimOverrideSignal* mutable_overridesignals(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::SimOverrideSignal >*
      mutable_overridesignals();
  private:
  const ::Proto::SimOverrideSignal& _internal_overridesignals(int index) const;
  ::Proto::SimOverrideSignal* _internal_add_overridesignals();
  public:
  const ::Proto::SimOverrideSignal& overridesignals(int index) const;
  ::Proto::SimOverrideSignal* add_overridesignals();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::SimOverrideSignal >&
      overridesignals() const;

  // @@protoc_insertion_point(class_scope:Proto.SimOverrideSignalWorkspace)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::SimOverrideSignal > overridesignals_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Simulator_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SimOverrideSignal

// optional bool enabled = 2;
inline bool SimOverrideSignal::_internal_has_enabled() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool SimOverrideSignal::has_enabled() const {
  return _internal_has_enabled();
}
inline void SimOverrideSignal::clear_enabled() {
  enabled_ = false;
  _has_bits_[0] &= ~0x00000008u;
}
inline bool SimOverrideSignal::_internal_enabled() const {
  return enabled_;
}
inline bool SimOverrideSignal::enabled() const {
  // @@protoc_insertion_point(field_get:Proto.SimOverrideSignal.enabled)
  return _internal_enabled();
}
inline void SimOverrideSignal::_internal_set_enabled(bool value) {
  _has_bits_[0] |= 0x00000008u;
  enabled_ = value;
}
inline void SimOverrideSignal::set_enabled(bool value) {
  _internal_set_enabled(value);
  // @@protoc_insertion_point(field_set:Proto.SimOverrideSignal.enabled)
}

// optional int32 index = 3;
inline bool SimOverrideSignal::_internal_has_index() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool SimOverrideSignal::has_index() const {
  return _internal_has_index();
}
inline void SimOverrideSignal::clear_index() {
  index_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SimOverrideSignal::_internal_index() const {
  return index_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SimOverrideSignal::index() const {
  // @@protoc_insertion_point(field_get:Proto.SimOverrideSignal.index)
  return _internal_index();
}
inline void SimOverrideSignal::_internal_set_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000010u;
  index_ = value;
}
inline void SimOverrideSignal::set_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_index(value);
  // @@protoc_insertion_point(field_set:Proto.SimOverrideSignal.index)
}

// optional string appSignalId = 10;
inline bool SimOverrideSignal::_internal_has_appsignalid() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool SimOverrideSignal::has_appsignalid() const {
  return _internal_has_appsignalid();
}
inline void SimOverrideSignal::clear_appsignalid() {
  appsignalid_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& SimOverrideSignal::appsignalid() const {
  // @@protoc_insertion_point(field_get:Proto.SimOverrideSignal.appSignalId)
  return _internal_appsignalid();
}
inline void SimOverrideSignal::set_appsignalid(const std::string& value) {
  _internal_set_appsignalid(value);
  // @@protoc_insertion_point(field_set:Proto.SimOverrideSignal.appSignalId)
}
inline std::string* SimOverrideSignal::mutable_appsignalid() {
  // @@protoc_insertion_point(field_mutable:Proto.SimOverrideSignal.appSignalId)
  return _internal_mutable_appsignalid();
}
inline const std::string& SimOverrideSignal::_internal_appsignalid() const {
  return appsignalid_.Get();
}
inline void SimOverrideSignal::_internal_set_appsignalid(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  appsignalid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void SimOverrideSignal::set_appsignalid(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  appsignalid_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:Proto.SimOverrideSignal.appSignalId)
}
inline void SimOverrideSignal::set_appsignalid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  appsignalid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:Proto.SimOverrideSignal.appSignalId)
}
inline void SimOverrideSignal::set_appsignalid(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  appsignalid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:Proto.SimOverrideSignal.appSignalId)
}
inline std::string* SimOverrideSignal::_internal_mutable_appsignalid() {
  _has_bits_[0] |= 0x00000001u;
  return appsignalid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* SimOverrideSignal::release_appsignalid() {
  // @@protoc_insertion_point(field_release:Proto.SimOverrideSignal.appSignalId)
  if (!_internal_has_appsignalid()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return appsignalid_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SimOverrideSignal::set_allocated_appsignalid(std::string* appsignalid) {
  if (appsignalid != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  appsignalid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), appsignalid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:Proto.SimOverrideSignal.appSignalId)
}

// optional int32 overrideMethod = 30;
inline bool SimOverrideSignal::_internal_has_overridemethod() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool SimOverrideSignal::has_overridemethod() const {
  return _internal_has_overridemethod();
}
inline void SimOverrideSignal::clear_overridemethod() {
  overridemethod_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SimOverrideSignal::_internal_overridemethod() const {
  return overridemethod_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SimOverrideSignal::overridemethod() const {
  // @@protoc_insertion_point(field_get:Proto.SimOverrideSignal.overrideMethod)
  return _internal_overridemethod();
}
inline void SimOverrideSignal::_internal_set_overridemethod(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000020u;
  overridemethod_ = value;
}
inline void SimOverrideSignal::set_overridemethod(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_overridemethod(value);
  // @@protoc_insertion_point(field_set:Proto.SimOverrideSignal.overrideMethod)
}

// optional .Proto.qvariant overrideValue = 40;
inline bool SimOverrideSignal::_internal_has_overridevalue() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || overridevalue_ != nullptr);
  return value;
}
inline bool SimOverrideSignal::has_overridevalue() const {
  return _internal_has_overridevalue();
}
inline const ::Proto::qvariant& SimOverrideSignal::_internal_overridevalue() const {
  const ::Proto::qvariant* p = overridevalue_;
  return p != nullptr ? *p : reinterpret_cast<const ::Proto::qvariant&>(
      ::Proto::_qvariant_default_instance_);
}
inline const ::Proto::qvariant& SimOverrideSignal::overridevalue() const {
  // @@protoc_insertion_point(field_get:Proto.SimOverrideSignal.overrideValue)
  return _internal_overridevalue();
}
inline void SimOverrideSignal::unsafe_arena_set_allocated_overridevalue(
    ::Proto::qvariant* overridevalue) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(overridevalue_);
  }
  overridevalue_ = overridevalue;
  if (overridevalue) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.SimOverrideSignal.overrideValue)
}
inline ::Proto::qvariant* SimOverrideSignal::release_overridevalue() {
  _has_bits_[0] &= ~0x00000004u;
  ::Proto::qvariant* temp = overridevalue_;
  overridevalue_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Proto::qvariant* SimOverrideSignal::unsafe_arena_release_overridevalue() {
  // @@protoc_insertion_point(field_release:Proto.SimOverrideSignal.overrideValue)
  _has_bits_[0] &= ~0x00000004u;
  ::Proto::qvariant* temp = overridevalue_;
  overridevalue_ = nullptr;
  return temp;
}
inline ::Proto::qvariant* SimOverrideSignal::_internal_mutable_overridevalue() {
  _has_bits_[0] |= 0x00000004u;
  if (overridevalue_ == nullptr) {
    auto* p = CreateMaybeMessage<::Proto::qvariant>(GetArena());
    overridevalue_ = p;
  }
  return overridevalue_;
}
inline ::Proto::qvariant* SimOverrideSignal::mutable_overridevalue() {
  // @@protoc_insertion_point(field_mutable:Proto.SimOverrideSignal.overrideValue)
  return _internal_mutable_overridevalue();
}
inline void SimOverrideSignal::set_allocated_overridevalue(::Proto::qvariant* overridevalue) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(overridevalue_);
  }
  if (overridevalue) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(overridevalue)->GetArena();
    if (message_arena != submessage_arena) {
      overridevalue = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, overridevalue, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  overridevalue_ = overridevalue;
  // @@protoc_insertion_point(field_set_allocated:Proto.SimOverrideSignal.overrideValue)
}

// optional string overrideScript = 50;
inline bool SimOverrideSignal::_internal_has_overridescript() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool SimOverrideSignal::has_overridescript() const {
  return _internal_has_overridescript();
}
inline void SimOverrideSignal::clear_overridescript() {
  overridescript_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& SimOverrideSignal::overridescript() const {
  // @@protoc_insertion_point(field_get:Proto.SimOverrideSignal.overrideScript)
  return _internal_overridescript();
}
inline void SimOverrideSignal::set_overridescript(const std::string& value) {
  _internal_set_overridescript(value);
  // @@protoc_insertion_point(field_set:Proto.SimOverrideSignal.overrideScript)
}
inline std::string* SimOverrideSignal::mutable_overridescript() {
  // @@protoc_insertion_point(field_mutable:Proto.SimOverrideSignal.overrideScript)
  return _internal_mutable_overridescript();
}
inline const std::string& SimOverrideSignal::_internal_overridescript() const {
  return overridescript_.Get();
}
inline void SimOverrideSignal::_internal_set_overridescript(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  overridescript_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void SimOverrideSignal::set_overridescript(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  overridescript_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:Proto.SimOverrideSignal.overrideScript)
}
inline void SimOverrideSignal::set_overridescript(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  overridescript_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:Proto.SimOverrideSignal.overrideScript)
}
inline void SimOverrideSignal::set_overridescript(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  overridescript_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:Proto.SimOverrideSignal.overrideScript)
}
inline std::string* SimOverrideSignal::_internal_mutable_overridescript() {
  _has_bits_[0] |= 0x00000002u;
  return overridescript_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* SimOverrideSignal::release_overridescript() {
  // @@protoc_insertion_point(field_release:Proto.SimOverrideSignal.overrideScript)
  if (!_internal_has_overridescript()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return overridescript_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SimOverrideSignal::set_allocated_overridescript(std::string* overridescript) {
  if (overridescript != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  overridescript_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), overridescript,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:Proto.SimOverrideSignal.overrideScript)
}

// -------------------------------------------------------------------

// SimOverrideSignalWorkspace

// repeated .Proto.SimOverrideSignal overrideSignals = 2;
inline int SimOverrideSignalWorkspace::_internal_overridesignals_size() const {
  return overridesignals_.size();
}
inline int SimOverrideSignalWorkspace::overridesignals_size() const {
  return _internal_overridesignals_size();
}
inline void SimOverrideSignalWorkspace::clear_overridesignals() {
  overridesignals_.Clear();
}
inline ::Proto::SimOverrideSignal* SimOverrideSignalWorkspace::mutable_overridesignals(int index) {
  // @@protoc_insertion_point(field_mutable:Proto.SimOverrideSignalWorkspace.overrideSignals)
  return overridesignals_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::SimOverrideSignal >*
SimOverrideSignalWorkspace::mutable_overridesignals() {
  // @@protoc_insertion_point(field_mutable_list:Proto.SimOverrideSignalWorkspace.overrideSignals)
  return &overridesignals_;
}
inline const ::Proto::SimOverrideSignal& SimOverrideSignalWorkspace::_internal_overridesignals(int index) const {
  return overridesignals_.Get(index);
}
inline const ::Proto::SimOverrideSignal& SimOverrideSignalWorkspace::overridesignals(int index) const {
  // @@protoc_insertion_point(field_get:Proto.SimOverrideSignalWorkspace.overrideSignals)
  return _internal_overridesignals(index);
}
inline ::Proto::SimOverrideSignal* SimOverrideSignalWorkspace::_internal_add_overridesignals() {
  return overridesignals_.Add();
}
inline ::Proto::SimOverrideSignal* SimOverrideSignalWorkspace::add_overridesignals() {
  // @@protoc_insertion_point(field_add:Proto.SimOverrideSignalWorkspace.overrideSignals)
  return _internal_add_overridesignals();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::SimOverrideSignal >&
SimOverrideSignalWorkspace::overridesignals() const {
  // @@protoc_insertion_point(field_list:Proto.SimOverrideSignalWorkspace.overrideSignals)
  return overridesignals_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Simulator_2eproto
