@startuml VFrame30
!include ../../doc/uml/Namespace.puml

!include ../../AppSignalLib/uml/AppSignalLib.puml


together {
	class VFrame30::AppSignalController #F0FFF0 
	class VFrame30::ScriptAppSignalController #F0FFF0 
}

'
'
'
class VFrame30::AppSignalController #F0FFF0
{
	public QObject
	--
	-IAppSignalManager : m_appSignalManager
}

AppSignalLib::IAppSignalManager "1" ..o  "1" VFrame30::AppSignalController


'
'
'
class VFrame30::ScriptAppSignalController #F0FFF0
{
	public QObject
	--
	-IAppSignalManager m_appSignalManager
}

AppSignalLib::IAppSignalManager "1" ..o "1" VFrame30::ScriptAppSignalController

@enduml