@startuml VFrame30
!include ../../doc/uml/Namespace.puml

class VFrame30::ClientSchemaWidget #F0FFF0 extends VFrame30::BaseSchemaWidget implements VFrame30::ISchemaViewHistory
{
	VFrame30::SchemaManager* m_schemaManager
	
	std::list<SchemaHistoryItem> : m_backHistory
	std::list<SchemaHistoryItem> : m_forwardHistory
}

VFrame30::SchemaManager ..o VFrame30::ClientSchemaWidget

@enduml