@startuml VFrame30
!include ../../doc/uml/Namespace.puml

'
' class ScriptSchemaLayer
'
class VFrame30::ScriptSchemaLayer #F0FFF0
{
	public QObject
	--
	SchemaLayerPtr : m_schemaLayer
}

VFrame30::SchemaLayer .o VFrame30::ScriptSchemaLayer

'
' class ScriptSchemaLayer
'
class VFrame30::SchemaLayer #F0FFF0
{
	public QObject
	--
	std::vector<SchemaItemPtr> : m_items
}

VFrame30::SchemaItem "*" ..* "1" VFrame30::SchemaLayer


'
together {
  class VFrame30::ScriptSchemaLayer #F0FFF0
  class VFrame30::SchemaLayer #F0FFF0
}

@enduml
