@startuml VFrame30

'!include SchemaItem.puml
!include AppSignalController.puml
!include SchemaView.puml
!include ClientSchemaView.puml
!include BaseSchemaWidget.puml
!include ClientSchemaWidget.puml
!include Schema.puml
!include SchemaLayer.puml
!include SchemaManager.puml

!include LogController.puml

!include TuningController.puml

@enduml