@startuml
!include ../../doc/uml/Namespace.puml

class MonitorConfigController
{
    public QObject
    public HasLogFile

    CfgLoaderThread : m_cfgLoaderThread
    ConfigSettings : m_configuration
}

() CfgService

MonitorConfigController -up- CfgService

@enduml