@startuml
!include ../../doc/uml/Namespace.puml

!include MonitorSchemaWidget.puml

class MonitorCentralWidget
{
    public TabWidgetEx
    --
	MonitorSchemaManager* : m_schemaManager;

	VFrame30::AppSignalController* : m_appSignalController;
	VFrame30::TuningController* : m_tuningController;
	VFrame30::LogController* : m_logController;
}

MonitorSchemaWidget "*" --* "1" MonitorCentralWidget : Tabs

@enduml