@startuml
!include ../../doc/uml/Namespace.puml

!include ../../UtilsLib/uml/LogFile.puml
!include ../../VFrame30/uml/AppSignalController.puml
!include MonitorSchemaManager.puml
!include MonitorCentralWidget.puml

class MonitorMainWindow
{
    public QMainWindow
    --
    Log::LogFile : m_LogFile
    TuningLog::TuningLog : m_tuningLogFile

    MonitorConfigController : m_configController
	MonitorSchemaManager : m_schemaManager

	std::unique_ptr<VFrame30::AppSignalController> : appSignalController
	std::unique_ptr<MonitorTuningController> : tuningController
	std::unique_ptr<VFrame30::LogController> : logController
}

Log::LogFile --* MonitorMainWindow
TuningLog::TuningLog ---* MonitorMainWindow

MonitorConfigController --* MonitorMainWindow
MonitorSchemaManager --* MonitorMainWindow

VFrame30::AppSignalController --* MonitorMainWindow

MonitorCentralWidget --* MonitorMainWindow

@enduml