@startuml
!include ../../doc/uml/Namespace.puml

!include ../../VFrame30/uml/SchemaManager.puml
!include MonitorConfigController.puml

class MonitorSchemaManager extends VFrame30::SchemaManager 
{
	MonitorConfigController* : m_configController

	RtTrendSchema : m_rtTrendSchemas
}

MonitorConfigController --o MonitorSchemaManager : GetSchema


@enduml