cmake_minimum_required(VERSION 3.16)

add_subdirectory(asio)

add_subdirectory(Behavior)
add_subdirectory(ClientLib)
add_subdirectory(DbLib)
add_subdirectory(DiagClientLib)
add_subdirectory(DiagStateLib)
add_subdirectory(HardwareLib)
add_subdirectory(Protobuf)
add_subdirectory(SchemaClientLib)
add_subdirectory(ServiceLib)
add_subdirectory(Simulator)
add_subdirectory(TrendView)
