windows_build_job:
  stage: build
  needs: ["project_backup_job"]
  only:
    - master
    - /^release.*$/
    - develop
    - /experimental/
    - /^.*exp.*$/
    - /^.*rpct-.*$/
    - /^.*RPCT-.*$/
  tags:
    - vs2017
  before_script:
    - $Env:VCPKG_ROOT="C:/data/vcpkg/vcpkg"
    - $Env:VCPKG_DEFAULT_BINARY_CACHE="C:/data/vcpkg/cache_windows_build"
    - $env:Path += ";C:/data/vcpkg/vcpkg"
  script:
    - "dir env:"
    - "echo $Env:CI_COMMIT_SHA"
    - "git status"
    - "git log -1"
    - $Env:QT_BIN_DIR="C:\\Qt\\${Env:QT_VERSION}\\msvc2022_64"
    - $Env:BIN_OUT_DIR="$Env:CI_PROJECT_DIR\bin\release"
    - $Env:INSTALL_OUT_DIR="$Env:CI_PROJECT_DIR\\dev"
#Build Project
    - "# ----------------------------------------------"
    - "#               Build Project"
    - "# ----------------------------------------------"    
    - "& './gitlab_ci_build_licenser.bat'"
    - "& './gitlab_ci_build.bat'"
#Copy Qt DLLs to bin/release
    - "# ----------------------------------------------"
    - "#               Copy Qt DLL's"
    - "# ----------------------------------------------"
    - "& './CI/windeploy.bat'"
#Copy FTDI Drivers to release
    - "mkdir \"$Env:BIN_OUT_DIR/ftdi\""
    - "copy C:\\ftdi\\CDM-v2.12.36.4-WHQL-Certified.zip $Env:BIN_OUT_DIR\\ftdi\\"
# Copy documents
    - "mkdir \"$Env:BIN_OUT_DIR/docs\""
    - "copy $Env:CI_PROJECT_DIR\\Metrology\\docs\\Metrology_User_Manual.pdf $Env:BIN_OUT_DIR\\docs\\"
    - "copy $Env:CI_PROJECT_DIR\\doc\\AdsGatewayProtocolSpec.md $Env:BIN_OUT_DIR\\docs\\"
    - "copy $Env:CI_PROJECT_DIR\\doc\\VduScriptApi.md $Env:BIN_OUT_DIR\\docs\\"
# Copy GlobalScript library
    - "mkdir \"$Env:BIN_OUT_DIR/scripting\""
    - "copy $Env:CI_PROJECT_DIR\\Scripts\\GlobalScript\\*.* $Env:BIN_OUT_DIR\\scripting\\"

#Remove some files not requiered for releases
    - "# ----------------------------------------------"
    - "#               Remove some files not requiered for releases"
    - "# ----------------------------------------------"
    - "del -Force $Env:BIN_OUT_DIR/DiagDataSrv.exe"

#Signing Files
    - "# ----------------------------------------------"
    - "#               Sign Files"
    - "# ----------------------------------------------"
#    - "$SIGNTOOL='C:/Program Files (x86)/Windows Kits/10/App Certification Kit/signtool.exe'"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\AppDataSrv.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\ArchSrv.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\CfgSrv.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\mconf.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\PacketSource.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\PacketViewer.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\Metrology.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\Monitor.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\scm.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\TuningClient.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\TuningSrv.exe"
#    - "&$SIGNTOOL sign /v /a /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\u7.exe"    

#Request documents from SVN
    - "# ----------------------------------------------"
    - "#               Request documents from SVN"
    - "# ----------------------------------------------"
    - "pushd ."	
    - "cd $Env:CI_PROJECT_DIR/doc"
    - "&./SvnGetDocs.bat"
    - "popd"

#Build Installer
    - "# ----------------------------------------------"
    - "#               Build Installer"
    - "# ----------------------------------------------"
    - "cmake --build ./build --target create_install"	
#    - "&$SIGNTOOL sign /v /a  /tr http://timestamp.digicert.com /fd SHA256 /f c:\\radiy-code-signing\\radiy-code-signing.pfx /p $SIGN_PASSWORD $Env:BIN_OUT_DIR\\..\\*.exe"

  artifacts:
    name: "u7set-win-x64-${CI_MAJOR_VERSION}.${CI_MINOR_VERSION}.${CI_PATCH_VERSION}-p${CI_PIPELINE_ID}-${CI_RELEASE_TYPE}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}"
    paths:
      - bin/*.exe
      - bin/*.exe
      - bin/release/*.exe
      - bin/release/*.dll
      - bin/release/iconengines/*.dll
      - bin/release/imageformats/*.dll
      - bin/release/networkinformation/*.dll
      - bin/release/platforms/*.dll
      - bin/release/sqldrivers/*.dll
      - bin/release/styles/*.dll
      - bin/release/tls/*.dll
      - bin/release/translations/*.qm
      - bin/release/scripting/*.*
      - bin/release/scripthelp/*.*
      - bin/release/scripthelp/search/*.*
      - bin/release/docs/*.pdf
      - bin/release/docs/*.md
      - bin/release/docs/Appendixes/*.pdf
      - bin/release/ftdi/**/*
      - bin/release/license/**/*
