project_backup_job:
  stage: prepare
  variables:
    GIT_STRATEGY: none
  only:
    - master
    - /^release.*$/
    - develop
    - /experimental/
    - /^.*exp.*$/
    - /^.*rpct-.*$/
    - /^.*RPCT-.*$/
  tags:
    - projectbackup
  script:
    - "# ----------------------------------------------"
    - "#               Create backup of database files "
    - "# ----------------------------------------------"
    - "if (Test-Path \"f:\\u7_${Env:COMPILER_TESTS_PROJECT_NAME}.sql.1\") {  Remove-Item -Verbose -Force \"f:\\TestDatabase\\u7_${Env:COMPILER_TESTS_PROJECT_NAME}.sql.1\" }"
    - "if (Test-Path \"f:\\u7_${Env:SIMULATOR_PROJECT_NAME}.sql.1\") {  Remove-Item -Verbose -Force \"f:\\TestDatabase\\u7_${Env:SIMULATOR_PROJECT_NAME}.sql.1\" }"
    - "pg_dump -h 192.168.75.10 -U u7 -f f:\\TestDatabase\\u7_${Env:COMPILER_TESTS_PROJECT_NAME}.sql.1 u7_${Env:COMPILER_TESTS_PROJECT_NAME}"
    - "pg_dump -h 192.168.75.10 -U u7 -f f:\\TestDatabase\\u7_${Env:SIMULATOR_PROJECT_NAME}.sql.1 u7_${Env:SIMULATOR_PROJECT_NAME}"
    - "f:\\TestDatabase\\UpdateFileIfDifferent.ps1 f:\\TestDatabase\\u7_${Env:COMPILER_TESTS_PROJECT_NAME}.sql.1 f:\\TestDatabase\\u7_${Env:COMPILER_TESTS_PROJECT_NAME}.sql"
    - "f:\\TestDatabase\\UpdateFileIfDifferent.ps1 f:\\TestDatabase\\u7_${Env:SIMULATOR_PROJECT_NAME}.sql.1 f:\\TestDatabase\\u7_${Env:SIMULATOR_PROJECT_NAME}.sql"
