syntax = "proto2";

//import "Common.proto";

package Proto;

message Address16
{
    // Changes in Address16 fields numbering are FORBIDDEN !!!
    // Only new numbers adding is allowed!
    //
    // This protobuf messages already stored in database.
    //

    required int32 offset = 1 [default = -1];
    required int32 bit = 2 [default = -1];
}

message StateFlagSignal
{
	optional int32 flagType = 1 [default = 0	/* E::AppSignalStateFlagType::Validity */];		// E::AppSignalStateFlagType values
	optional string flagSignalID = 2;
}

message AppSignalDbField
{
    optional int32 ID = 1 [default = -1];
    optional int32 signalGroupID = 2 [default = -1];
    optional int32 signalInstanceID = 3 [default = -1];
    optional int32 changesetID = 4 [default = -1];
    optional bool checkedOut = 5 [default = false];
    optional int32 userID = 6 [default = -1];
    optional int64 created = 7 [default = 0];
    optional bool deleted = 8 [default = false];
    optional int64 instanceCreated = 9 [default = 0];
    optional int32 instanceAction = 10 [default = 0];		// VcsItemActionType::Unknown
}

message AppSignalCalculatedParam
{
    optional uint64 hash = 1 [default = 0];
    optional Address16 ioBufAddr = 2;
    optional Address16 tuningAddr = 3;
    optional Address16 ualAddr = 4;
    optional Address16 regBufAddr = 5;
    optional Address16 regValueAddr = 6;
    optional Address16 regValidityAddr = 7;
	optional int32 lmRamAccess = 8 [default = 0 /* E::LogicModuleRamAccess::Undefined */];		// E::LogicModuleRamAccess values
    optional bool isConst = 9 [default = false];
    optional double constValue = 10 [default = 0];
	repeated StateFlagSignal stateFlagsSignals = 11;
	optional bool isEndpoint = 12 [default = false];
}

message TuningValue
{
    optional int32 type = 1;					// enum TuningValueType values
    optional int64 intValue = 2 [default = 0];
    optional double doubleValue = 3 [default = 0.0];
}

message AppSignal
{
    // Signal identificators

    optional string appSignalID = 1;
    optional string customAppSignalID = 2;
    optional string caption = 3;
    optional string equipmentID = 4;				// should be transformed to portEquipmentID
    optional string lmEquipmentID = 5;
    optional string busTypeID = 6;
    optional int32 channel = 7 [default = 0];
	optional bool excludeFromBuild = 8 [default = false];

	optional bool invertSignal = 9 [default = false];
	optional bool reserved = 10 [default = false];

    // Signal type

    optional int32 signalType = 16 [default = 1];		// E::SignalType::Discrete
    optional int32 inOutType = 17 [default = 2];		// E::SignalInOutType::Internal
	optional int32 swCalcFunction = 18 [default = 0];	// E::SoftwareCalcFunction

    // Signal format

    optional int32 dataSize = 21 [default = 0];
    optional int32 byteOrder = 22 [default = 1];		// E::ByteOrder::BigEndian

    // Analog signal properties

    optional int32 analogSignalFormat = 26 [default = 1];	// E::AnalogSignalFormat::SignedInt32
    optional string unit = 27;

    // Tuning signal properties

    optional bool enableTuning = 71 [default = false];

    optional TuningValue tuningDefaultValue = 72;
    optional TuningValue tuningLowBound = 73;
    optional TuningValue tuningHighBound = 74;

    // Signal properties for MATS

    optional bool acquire = 81 [default = false];
    optional bool archive = 82 [default = false];

    optional int32 decimalPlaces = 83 [default = 2];
    optional double coarseAperture = 84 [default = 1];
    optional double fineAperture = 85 [default = 0.5];
	//optional bool obsolete_adaptiveAperture = 86 [default = false];
	optional int32 apertureType = 86 [default = 0 /* E::ApertureType::RangePercent */];

	optional bool log = 87 [default = false];

    // Signal specific properties

    optional string specPropStruct = 90;
    optional bytes specPropValues = 91;				// serialized message Proto::SignalSpecPropValues

    repeated string tags = 92;

    // Signal fields from database

    optional AppSignalDbField dbField = 120;

    // Signal properties calculated in compile-time

    optional AppSignalCalculatedParam calcParam = 121;
}


message AppSignalSet
{
    repeated AppSignal appSignal = 1;
}

// Fields of AppSignal serialized and saved in field ProtoData of table SignalInstance
//
//  After adding or removing fields - check Signal::saveProtoData, Signal::loadProtoData !!!
//
message ProtoAppSignalData
{
	optional string busTypeID = 1;
	optional string caption = 2;
	optional int32 channel = 3 [default = 0 /* E::Channel::A */];

	optional int32 dataSize = 4 [default = 32];
	optional int32 byteOrder = 5 [default = 1 /* E::ByteOrder::BigEndian */];
	optional int32 analogSignalFormat = 6 [default = 2 /* E::AnalogAppSignalFormat::Float32 */];
	optional string unit = 7;
	
	optional bool enableTuning = 8 [default = false];
	optional TuningValue tuningDefaultValue = 9;
	optional TuningValue tuningLowBound = 10;
	optional TuningValue tuningHighBound = 11;
	
	optional bool acquire = 12 [default = true];
	optional bool archive = 13 [default = true];
	optional int32 decimalPlaces = 14 [default = 2];
	optional double coarseAperture = 15 [default = 1.0];
	optional double fineAperture = 16 [default = 0.5];
	optional bool obsolete_adaptiveAperture = 17 [default = false];		// not used from 395 DB version
																		// ApertureType used instead
	optional bool excludefromBuild = 18 [default = false];

    optional string tags = 19;

    optional string userSpecPropStruct = 20;
	optional bytes userSpecPropValues = 21;					// serialized message Proto::SignalSpecPropValues

	optional int32 apertureType = 22 [default = 0 /* E::ApertureType::RangePercent */];
	
	optional bool invertSignal = 23 [default = false];
	optional bool reserved = 24 [default = false];

	optional int32 swCalcFunction = 25 [default = 0 /* E::SoftwareCalcFunction::None */];

	optional bool log = 26 [default = false];
}

// Data structs
//
message AppSignalState
{
    optional uint64 hash = 1 [default = 0];
    optional double value = 2 [default = 0];
    optional uint32 flags = 3 [default = 0];
    optional sfixed64 systemTime = 4 [default = 0];
    optional sfixed64 localTime = 5 [default = 0];
    optional sfixed64 plantTime = 6 [default = 0];
    optional sfixed64 archiveId = 7 [default = -1];
	optional uint32 packetNo = 8 [default = 0];
}

//
// Metrology signals
//

message MetrologySignalLocation
{
    optional string rackID = 1;

    optional string chassisID = 2;
	optional int32 chassis = 3 [default = -1];

    optional string moduleCaption = 9;
    optional string moduleID = 4;
	optional int32 module = 5 [default = -1];

    optional int32 place = 6 [default = -1];
	optional string contact = 7;

    optional bool shownOnSchemas = 8 [default = false];

    // maximun 9
}

message MetrologySignal
{
    optional AppSignal appSignal = 1;

    optional MetrologySignalLocation location = 2;

    optional double electricLowLimit = 3 [default = 0.0];
	optional double electricHighLimit = 4 [default = 0.0];
	optional int32 electricUnitID = 5 [default = 1];			// E::ElectricUnit::NoUnit;
	optional int32 electricSensorType = 6 [default = 1];		// E::SensorType::NoSensor;
    optional double electricRload = 11 [default = 0];
	optional double electricR0 = 7 [default = 0];
	optional int32 electricPrecision = 8 [default = 4];
	
    optional double physicalLowLimit = 9 [default = 0.0];
	optional double physicalHighLimit = 10 [default = 0.0];

    // maximun 11
}

message MetrologySignalSet
{
    repeated MetrologySignal metrologySignal = 1;
}

message SignalSpecPropValue
{
    required string name = 1;
    required int32 type = 2 [default = 0 /* QVariant::Invalid */];	// values of enum QVariant::Type
    required bool isEnum = 3 [default = false];

    optional int32  int32Val = 10;
    optional uint32 uint32Val = 11;
    optional int64  int64Val = 12;
    optional uint64 uint64Val = 13;
    optional double doubleVal = 14;
    optional bool   boolVal = 15;
    optional string stringVal = 16;
}

message SignalSpecPropValues
{
    repeated SignalSpecPropValue value = 1;
}
