syntax = "proto2";

package ProtoSim;

import "Common.proto";

// Simulator
//
message SimOverrideSignal
{
    optional bool enabled = 2;
    optional int32 index = 3;

    optional string appSignalId = 10;
    optional int32 overrideMethod = 30;

    optional Proto.qvariant overrideValue = 40;
    optional string overrideScript = 50;		// if method == OverrideSignalMethod::Script
}

message SimOverrideSignalWorkspace
{
    repeated SimOverrideSignal overrideSignals = 2;
}

//
// Snapshot
//

message OverrideRamRecord
{
    optional uint32 mask = 2;
    optional uint32 data = 3;
}

message SnapshotLmRamArea
{
    // RamAreaInfo
    //
    optional string name = 5;
    optional int32 access = 7; // E::LogicModuleRamAccess
    optional uint64 offset = 9;
    optional uint64 size = 10;

    // RamArea
    //
	optional bool clearOnStartCycle = 20;					// Clear memory area on start of work cycle
    optional bytes data = 25;
    repeated OverrideRamRecord overrideData = 28;
}

// Sim::Ram
//
message SnapshotLmRam
{
    repeated SnapshotLmRamArea memoryAreas = 5; 
    optional int32 overrideSignalsLastCounter = 7;
}

// Sim::LogicUnitData
//
message SnapshotLogicUnitData 
{
}

message AfbComponentParam
{
    optional uint64 data = 2 [default = 0xFFFFFFFFFFFFFFFF];
    optional uint32 paramOpIndex = 6 [default = 0xFFFF];
}

message AfbComponentInstance
{
    optional int32 instanceNo = 2;
    optional int32 versionOpIndex = 10;
    repeated AfbComponentParam params = 5;
}

message AfbComponent
{
    repeated AfbComponentInstance instances = 2;
}

message AfbComponentSet
{
    repeated AfbComponent afbs = 2;
}

// Sim::LogicModule + Sim::DeviceEmulator
//
message SnapshotLogicModule
{
    optional int64 lastStartTime = 8;
    optional int64 possibleToAdvanceTo = 9;
    optional int64 cyclesCounter = 11;

    optional string equipmentId = 14;

    optional fixed32 tuningEepromCrc = 15;
    optional fixed32 confEepromCrc = 16;
    optional fixed32 appLogicEepromCrc = 17;

    optional int32 runtimeMode = 26; // enum Sim::RuntimeMode
    optional int32 deviceState2 = 27; // enum Sim::DeviceState

    optional SnapshotLmRam ram = 50;
    optional AfbComponentSet afbSet = 70;

    optional bool armingKey = 80;
    optional bool tuningKey = 81;
    optional SnapshotLmRamArea m_tuningRamArea = 90;

    optional bool sorIsSet = 100;
    optional bool sorSetSwitch1 = 111;
    optional bool sorSetSwitch2 = 112;
    optional bool sorSetSwitch3 = 113;
}

// Sim::ConnectionImpl
//
message SnapshotConnectionData
{
    optional bytes data = 2;				// Raw data from LM memory
    optional int64 sentTime = 3;			// When packet was "sent". If 0 then buffer is not valid
}

message SnapshotConnectionImpl
{
    optional string id = 2;

    optional bool enable = 4;
    optional bool timeout = 5;

    optional string port1EquipmentId = 7;
    optional string port2EquipmentId = 8;

    // Port 1 data
    //
    optional SnapshotConnectionData port1sentData = 10;
    optional bytes port1receiveBuffer = 11;
    optional bytes port1sendBuffer = 12;

    // Port 2 data
    //
    optional SnapshotConnectionData port2sentData = 20;
    optional bytes port2receiveBuffer = 21;
    optional bytes port2sendBuffer = 22;
}

message Snapshot
{
    optional string snapshotId = 2;
    optional string projectName = 3;
    repeated SnapshotLogicModule logicModules = 10;
    repeated SnapshotConnectionImpl connections = 20;
}