if(CMAKE_BUILD_TYPE STREQUAL "Debug" AND MSVC)
	include_directories("C:/Program Files (x86)/Visual Leak Detector/include")
	link_directories("C:/Program Files (x86)/Visual Leak Detector/lib/Win64")
	#target_compile_definitions(my_app PRIVATE VLD_FORCE_ENABLE)
endif()
