/**
 * @file AdsBridge.h
 * @brief This file contains the declaration of functions and structures for the AdsBridge library.
 */

#ifndef ADSB_ADS_BRIDGE_H
#define ADSB_ADS_BRIDGE_H

#include "Common.h"

/// @cond DOXYGEN_IGNORE
#ifdef __cplusplus
	#define ADSB_INLINE inline        // C++
#else
	#define ADSB_INLINE static inline // C
#endif
/// @endcond

/* \cond INTERNAL */
ADSB_API bool AdsGetTcpConnectionStatusesPrivate1(size_t structSize, struct AdsConnectionStatus* out, size_t count);
ADSB_API size_t AdsGetSignalParamsPrivate1(size_t structSize,
										   const MatsSignalHash* signalHashes,
										   struct MatsAppSignalParam* out,
										   size_t count);
ADSB_API size_t AdsGetSignalStatesPrivate1(size_t structSize,
										   const MatsSignalHash* signalHashes,
										   struct MatsAppSignalState* out,
										   size_t count);
/* \endcond */

#ifdef __cplusplus
extern "C"
{
#endif

	/**
	 * \brief Returns the AdsBridge API interface version.
	 *
	 * Use this to verify API compatibility between the library and client code.
	 * Current version: 0x00000002.
	 * Thread-safe.
	 *
	 * \return The API version as a 32-bit unsigned integer (currently 0x00000002).
	 */
	ADSB_API uint32_t AdsGetInterfaceVersion(void);

	/**
	 * \brief Sets the log handler for the AdsBridge library.
	 *
	 * Configures a custom callback function to receive log messages from AdsBridge.
	 * Must be called before AdsInit() or any other AdsBridge functions.
	 * The provided handler function must be thread-safe as it may be called from multiple threads.
	 *
	 * \param handler Pointer to the log handler callback function.
	 */
	ADSB_API void AdsSetLogHandler(MatsLogHandler handler);

	/**
	 * \brief Sets the minimum log level for filtering log messages.
	 *
	 * Configures which log messages are passed to the log handler based on severity.
	 * Only messages at or above the specified level will be logged.
	 * Messages can also be filtered within the log handler itself for additional control.
	 * Available levels are defined in the MatsLogLevel enum.
	 * Default level: MATS_LOG_LEVEL_WARNING.
	 * Must be called before AdsInit() or any other AdsBridge functions.
	 *
	 * \param level The minimum log level (messages below this level are filtered out).
	 */
	ADSB_API void AdsSetLogLevel(enum MatsLogLevel level);

	/**
	 * \brief Tests the log handler by sending a test message.
	 *
	 * Sends a test message to the configured log handler at the specified level.
	 * Use this to verify that the log handler is correctly installed and functioning.
	 * The message is subject to the current log level filter set by AdsSetLogLevel().
	 * Thread-safe.
	 *
	 * \param level The log level for the test message.
	 * \param message The test message to send (null-terminated string).
	 */
	ADSB_API void AdsTestLogHandler(enum MatsLogLevel level, const char* message);

	/**
	 * \brief Initializes the AdsBridge library, initializes internal resources.
	 *
	 * \param equipmentId The equipment ID for this AdsBridge instance (null-terminated string).
	 */
	ADSB_API bool AdsInit(const char* equipmentId);

	/**
	 * \brief Shuts down the AdsBridge library.
	 *
	 * This function shuts down the AdsBridge library and releases all resources allocated by the library.
	 */
	ADSB_API void AdsShutdown();

	/**
	 * \brief Gets the software ID of the AdsBridge library.
	 *
	 * This function returns the software ID of the AdsBridge library set by AdsInit(), AdsLoadConfiguration() or AdsSetConfiguration().
	 *
	 * \return The software ID of the AdsBridge library.
	 */
	ADSB_API const char* AdsGetSoftwareId();

	/**
	 * \brief Loads the configuration from the specified file.
	 *
	 * This function loads the configuration for the AdsBridge library from the specified file. The configuration file is an XML file that
	 * contains the configuration settings for the library. This file can be generated by RPCT and usually has name
	 * {ADS_BRIDGE_ID}/Configuration.xml.
	 *
	 * \param fileName The name of the configuration file.
	 * \return True if the configuration was successfully loaded, false otherwise.
	 */
	ADSB_API bool AdsLoadConfiguration(const char* fileName);

	/**
	 * \brief Sets the configuration for the AdsBridge library.
	 *
	 * This function sets the configuration for the AdsBridge library using the provided XML string. The configuration file is an XML file
	 * that contains the configuration settings for the library.
	 *
	 * \param configurationXml The XML string containing the configuration.
	 * \param size The size of the XML string.
	 * \return True if the configuration was successfully set, false otherwise.
	 */
	ADSB_API bool AdsSetConfiguration(const char* configurationXml, size_t size);

	/**
	 * \brief Sets the configuration profile for the already loaded/set configuration.
	 *
	 * This function sets the configuration profile for the AdsBridge library. Default profile is "Default".
	 * This function can only be called after AdsLoadConfiguration() or AdsSetConfiguration() has been called.
	 *
	 * \param profile The configuration profile name to set.
	 */
	ADSB_API bool AdsSetConfigurationProfile(const char* profile);

	/**
	 * \brief Adds a connection to the AppDataService.
	 *
	 * This function adds a connection to the AppDataService. The connection is identified by the EquipmentID, and the IPv4 address/port of
	 * the service. The connection is not established until AdsConnect() is called.
	 *
	 * \param adsEquipmentId The equipment ID of the AppDataService.
	 * \param address The IPv4 address of the server.
	 * \param port The port number of the server.
	 */
	ADSB_API void AdsAddService(const char* adsEquipmentId, const char* address, int port);

	/**
	 * \brief Connects to the AppDataService.
	 *
	 * This function connects to the AppDataService(s) using the connections that have been added with AdsAddService(). The connection
	 * status can be checked with AdsGetTcpConnectionStatuses().
	 */
	ADSB_API void AdsConnect();

	/**
	 * \brief Closes all connections to the AppDataServices.
	 *
	 * This function closes the connection to the AppDataService(s).
	 */
	ADSB_API void AdsCloseConnection();

	/**
	 * \brief Returns the number of TCP connections to AppDataService instances.
	 *
	 * This function queries the current count of active connections. Connections must be added via
	 * AdsAddService() and established with AdsConnect() before they are counted.
	 * Thread-safe.
	 *
	 * \return The number of added connections.
	 */
	ADSB_API size_t AdsGetTcpConnectionCount();

	/**
	 * \brief Retrieves TCP connection statuses for all AppDataService connections.
	 *
	 * Returns the current status of each TCP connection added via AdsAddService() and AdsConnect().
	 * The caller must allocate the output array with size equal to AdsGetTcpConnectionCount().
	 * Thread-safe.
	 *
	 * \param out Pointer to pre-allocated array of AdsConnectionStatus structures.
	 * \param count Number of connection statuses to get.
	 * \return true if statuses were successfully retrieved, false on error (e.g., null pointer, count mismatch).
	 */
	ADSB_INLINE bool AdsGetTcpConnectionStatuses(struct AdsConnectionStatus* out, size_t count)
	{
		return AdsGetTcpConnectionStatusesPrivate1(sizeof(struct AdsConnectionStatus), out, count);
	}

	/**
	 * \brief Checks if all signal parameters have been loaded from AppDataService.
	 *
	 * Returns true only when parameters for all configured signals have been successfully received.
	 * Thread-safe.
	 *
	 * \return true if all signal parameters are loaded, false otherwise.
	 */
	ADSB_API bool AdsSignalParamsLoaded();

	/**
	 * \brief Checks if the signal states are loaded.
	 *
	 * This function checks if the signal states are loaded.
	 * Thread-safe.
	 *
	 * \return True if the all signal states are loaded, false otherwise.
	 */
	ADSB_API bool AdsSignalStatesLoaded();

	/**
	 * \brief Returns the total number of signal.
	 *
	 * Returns the count of all signals available from the connected AppDataService instances.
	 * This count is only valid after AdsConnect() has been called and signals have been received.
	 * Thread-safe.
	 *
	 * \return The number of signals.
	 */
	ADSB_API size_t AdsGetSignalCount();

	/**
	 * \brief Retrieves the list of all signal hashes.
	 *
	 * This function returns the list of signals that are available.
	 * The caller must allocate the output array with size equal to AdsGetSignalCount().
	 * Thread-safe.
	 *
	 * \param out Pointer to pre-allocated array of MatsSignalHash values.
	 * \param count Number of signal hashes to retrieve, must match AdsGetSignalCount().
	 * \return true if signal hashes were successfully retrieved, false on error (e.g., null pointer, count mismatch).
	 */
	ADSB_API bool AdsGetSignalList(MatsSignalHash* out, size_t count);

	/**
	 * \brief Retrieves parameters for the specified signals from AppDataService.
	 *
	 * Returns cached signal parameter data previously loaded from AppDataService.
	 * Check AdsSignalParamsLoaded() before calling to ensure parameters are available.
	 * For signals not found in the cache, the corresponding output entry is zeroed.
	 * Thread-safe.
	 *
	 * \param signalHashes Pointer to array of signal hashes to query.
	 * \param out Pointer to pre-allocated array of MatsAppSignalParam structures to fill. If signal is not found, the corresponding signal
	 * will be filled with zeros.
	 * \param count Number of signals to retrieve parameters for.
	 * \return Number of successfully retrieved signal parameters, or 0 on error (e.g., null pointer).
	 */
	ADSB_INLINE size_t AdsGetSignalParams(const MatsSignalHash* signalHashes, struct MatsAppSignalParam* out, size_t count)
	{
		return AdsGetSignalParamsPrivate1(sizeof(struct MatsAppSignalParam), signalHashes, out, count);
	}

	/**
	 * \brief Retrieves states for the specified signals from AppDataService.
	 *
	 * Returns cached signal state data previously loaded from AppDataService.
	 * Check AdsSignalStatesLoaded() before calling to ensure states are available.
	 * For signals not found in the cache, the corresponding output entry is zeroed.
	 * Thread-safe.
	 *
	 * \param signalHashes Pointer to array of signal hashes to query.
	 * \param out Pointer to pre-allocated array of MatsAppSignalState structures to fill. If signal is not found, the corresponding signal
	 * will be filled with zeros.
	 * \param count Number of signals to retrieve states for.
	 * \return Number of successfully retrieved signal states, or 0 on error (e.g., null pointer).
	 */
	ADSB_INLINE size_t AdsGetSignalStates(const MatsSignalHash* signalHashes, struct MatsAppSignalState* out, size_t count)
	{
		return AdsGetSignalStatesPrivate1(sizeof(struct MatsAppSignalState), signalHashes, out, count);
	}
	
	/**
	 * \brief Calculates hash value from AppSignalId string.
	 *
	 * Computes the MatsSignalHash value used to identify signals in AdsBridge API.
	 * Use this function to convert signal AppSignalId strings into hash values
	 * required by AdsGetSignalParams() and AdsGetSignalStates().
	 * Thread-safe.
	 *
	 * \param string The AppSignalId string to hash (null-terminated).
	 * \return The calculated MatsSignalHash value.
	 */
	ADSB_API MatsSignalHash AdsCalcHash(const char* string);

#ifdef __cplusplus
}
#endif

#endif // ADSB_ADS_BRIDGE_H