#pragma once

#if __has_include(<EmbeddedBlacklist.h>)
	#define HAVE_EMBEDDED_BLACKLIST
	#include <EmbeddedBlacklist.h> // Embedded blacklist is generated by CI pipeline.
	#pragma message("Embedded blacklist is enabled!")
#endif

#include <CommonLib/expected.hpp>

namespace LicenseLib
{
	class Blacklist
	{
	public:
		Blacklist();

	public:
		tl::expected<bool, BlacklistReason> check(const QUuid& licenseUuid) const;

	private:
		std::unordered_map<QUuid, BlacklistItem> m_blacklist;
	};

} // namespace LicenseLib